export default class m_BomEntry {
      columnArr=['cCode','iInterID','iEntryID','iSeqID','iSubItemID','cSubInvCode','iBatQty','iParentQty','iSubQty','cSubRelate','dValidDate','dInvalidDate','iScrapt','iOffsetLT','cSupplyMode','cSelect','iPercent','iRetOffsetLT','iRetPercent','cUtterType','cEco','cEcoNote','cNote','cDeductType','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cGetItemType','cWhCode','cScraptExp','dOpeDate','cVenCode','cPrintColor','bSelf','bDaBan','cItemClsNo','cProductSolidSize','cProductPlaneSize','cTypeSetting','iOpenQty','iBanQty','iMolecularQty','iDenominatorQty','cSyncStatus','dqkts','iErpEntryID']
      cCode?:any
iInterID?:any
iEntryID?:any
iSeqID?:any
iSubItemID?:any
cSubInvCode?:any
iBatQty?:any
iParentQty?:any
iSubQty?:any
cSubRelate?:any
dValidDate?:any
dInvalidDate?:any
iScrapt?:any
iOffsetLT?:any
cSupplyMode?:any
cSelect?:any
iPercent?:any
iRetOffsetLT?:any
iRetPercent?:any
cUtterType?:any
cEco?:any
cEcoNote?:any
cNote?:any
cDeductType?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cGetItemType?:any
cWhCode?:any
cScraptExp?:any
dOpeDate?:any
cVenCode?:any
cPrintColor?:any
bSelf?:any
bDaBan?:any
cItemClsNo?:any
cProductSolidSize?:any
cProductPlaneSize?:any
cTypeSetting?:any
iOpenQty?:any
iBanQty?:any
iMolecularQty?:any
iDenominatorQty?:any
cSyncStatus?:any
dqkts?:any
iErpEntryID?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }