export default class m_Person {
      columnArr=['cPsn_Num','cPsn_Name','cDepCode','iRecordID','rPersonType','rSex','dBirthDate','rNativePlace','rNational','rhealthStatus','rMarriStatus','vIDNo','MPicture','rPerResidence','vAliaName','dJoinworkDate','dEnterDate','dRegularDate','vSSNo','rworkAttend','vCardNo','rtbmRule','rCheckInFlag','dLastDate','hrts','vstatus1','nstatus2','bPsnPerson','cPsnMobilePhone','cPsnFPhone','cPsnOPhone','cPsnInPhone','cPsnEmail','cPsnPostAddr','cPsnPostCode','cPsnFAddr','cPsnQQCode','cPsnURL','CpsnOSeat','dEnterUnitDate','cPsnProperty','cPsnBankCode','cPsnAccount','pk_hr_hi_person','bProbation','cDutyclass','bTakeTM','MPictureqpb','rIDType','rCountry','dLeaveDate','rFigure','rWorkStatus','EmploymentForm','rPersonParameters','bDutyLock','bpsnshop','cPosition','cEnglishName','cEducation','cReservefundNo','fCreditQuantity','iCreDate','cCreGrade','iLowRate','cOfferGrade','iOfferRate','dPValidDate','dPInValidDate','cPsnDefine1','cPsnDefine2','cPsnDefine3','cPsnDefine4','cPsnDefine5','cPsnDefine6','cPsnDefine7','cPsnDefine8','cPsnDefine9','cPsnDefine10','cPsnDefine11','cPsnDefine12','cPsnDefine13','cPsnDefine14','cPsnDefine15','cPsnDefine16','cPrvNo','cMemberShip','cClasses','bLacklist','bLacklistNote','cBusDepCode','cSyncStatus']
      cPsn_Num?:any
cPsn_Name?:any
cDepCode?:any
iRecordID?:any
rPersonType?:any
rSex?:any
dBirthDate?:any
rNativePlace?:any
rNational?:any
rhealthStatus?:any
rMarriStatus?:any
vIDNo?:any
MPicture?:any
rPerResidence?:any
vAliaName?:any
dJoinworkDate?:any
dEnterDate?:any
dRegularDate?:any
vSSNo?:any
rworkAttend?:any
vCardNo?:any
rtbmRule?:any
rCheckInFlag?:any
dLastDate?:any
hrts?:any
vstatus1?:any
nstatus2?:any
bPsnPerson?:any
cPsnMobilePhone?:any
cPsnFPhone?:any
cPsnOPhone?:any
cPsnInPhone?:any
cPsnEmail?:any
cPsnPostAddr?:any
cPsnPostCode?:any
cPsnFAddr?:any
cPsnQQCode?:any
cPsnURL?:any
CpsnOSeat?:any
dEnterUnitDate?:any
cPsnProperty?:any
cPsnBankCode?:any
cPsnAccount?:any
pk_hr_hi_person?:any
bProbation?:any
cDutyclass?:any
bTakeTM?:any
MPictureqpb?:any
rIDType?:any
rCountry?:any
dLeaveDate?:any
rFigure?:any
rWorkStatus?:any
EmploymentForm?:any
rPersonParameters?:any
bDutyLock?:any
bpsnshop?:any
cPosition?:any
cEnglishName?:any
cEducation?:any
cReservefundNo?:any
fCreditQuantity?:any
iCreDate?:any
cCreGrade?:any
iLowRate?:any
cOfferGrade?:any
iOfferRate?:any
dPValidDate?:any
dPInValidDate?:any
cPsnDefine1?:any
cPsnDefine2?:any
cPsnDefine3?:any
cPsnDefine4?:any
cPsnDefine5?:any
cPsnDefine6?:any
cPsnDefine7?:any
cPsnDefine8?:any
cPsnDefine9?:any
cPsnDefine10?:any
cPsnDefine11?:any
cPsnDefine12?:any
cPsnDefine13?:any
cPsnDefine14?:any
cPsnDefine15?:any
cPsnDefine16?:any
cPrvNo?:any
cMemberShip?:any
cClasses?:any
bLacklist?:any
bLacklistNote?:any
cBusDepCode?:any
cSyncStatus?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }