export default class m_PurOrderTemp {
      columnArr=['iPOID','cPOCode','dPODate','cVenCode','cDepCode','cPersonCode','cPTCode','cArrivalPlace','cSCCode','cexch_name','nflat','iTaxRate','cPayCode','iCost','iBargain','cChanger','cBusType','cNote','cPeriod','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cLocker','iDiscountTaxType','ireturncount','cStatus','cOperator','dOpeDate','cChecker','dCheckDate','cVenPUOMProtocol','iVT_ID','iAuditTypeID','qkts','cCloser','dCloseDate','iPrintCount','cModifier','dModifyDate','cSyncStatus','cErpWriteBack','cApsWriteBack']
      iPOID?:any
cPOCode?:any
dPODate?:any
cVenCode?:any
cDepCode?:any
cPersonCode?:any
cPTCode?:any
cArrivalPlace?:any
cSCCode?:any
cexch_name?:any
nflat?:any
iTaxRate?:any
cPayCode?:any
iCost?:any
iBargain?:any
cChanger?:any
cBusType?:any
cNote?:any
cPeriod?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cLocker?:any
iDiscountTaxType?:any
ireturncount?:any
cStatus?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cVenPUOMProtocol?:any
iVT_ID?:any
iAuditTypeID?:any
qkts?:any
cCloser?:any
dCloseDate?:any
iPrintCount?:any
cModifier?:any
dModifyDate?:any
cSyncStatus?:any
cErpWriteBack?:any
cApsWriteBack?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }