export default class m_SdOrderEntryTemp {
      columnArr=['iInterID','iSdLineID','cSdOrderNo','cRequireType','iItemID','cInvCode','cInvName','cInvStd','cUnitCode','cInvClass','iInvExchRate','cCustItemNo','iReqQty','iNum','dRequireDate','dDeliveryDate','dEarliestSchDate','cSchStatus','dBegDate','dEndDate','cMiNo','iTaxRate','iQuotedPrice','iUnitPrice','iTaxUnitPrice','iMoney','iTax','iSum','iDiscount','iNatUnitPrice','iNatTaxPrice','iNatMoney','iNatTax','iNatSum','iNatDisCount','KL','KL2','iFHNum','iFHQuantity','iFHMoney','iKPQuantity','iKPNum','iKPMoney','iPreKeepQuantity','iPreKeepNum','fOutquantity','fOutnum','fRetQuantity','fRetNum','cIsMps','cParentItem','iPriority','cSelected','cWoNo','iPlanQty','cNeedSet','cSourceType','cSourceCode','iSourceLineID','cNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cColor','cLineCloser','iPlanNum','iNetQty','iSchSDID','cbCloseDate','WBID','WBPID','cProductNo','iSdLine2ID','cWhCode','dOpeDate','cDCStatus','cPriceType','iReceivedQTY','iReceivedNum','cProMaterialNote','dqkts','cSyncStatus']
      iInterID?:any
iSdLineID?:any
cSdOrderNo?:any
cRequireType?:any
iItemID?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cUnitCode?:any
cInvClass?:any
iInvExchRate?:any
cCustItemNo?:any
iReqQty?:any
iNum?:any
dRequireDate?:any
dDeliveryDate?:any
dEarliestSchDate?:any
cSchStatus?:any
dBegDate?:any
dEndDate?:any
cMiNo?:any
iTaxRate?:any
iQuotedPrice?:any
iUnitPrice?:any
iTaxUnitPrice?:any
iMoney?:any
iTax?:any
iSum?:any
iDiscount?:any
iNatUnitPrice?:any
iNatTaxPrice?:any
iNatMoney?:any
iNatTax?:any
iNatSum?:any
iNatDisCount?:any
KL?:any
KL2?:any
iFHNum?:any
iFHQuantity?:any
iFHMoney?:any
iKPQuantity?:any
iKPNum?:any
iKPMoney?:any
iPreKeepQuantity?:any
iPreKeepNum?:any
fOutquantity?:any
fOutnum?:any
fRetQuantity?:any
fRetNum?:any
cIsMps?:any
cParentItem?:any
iPriority?:any
cSelected?:any
cWoNo?:any
iPlanQty?:any
cNeedSet?:any
cSourceType?:any
cSourceCode?:any
iSourceLineID?:any
cNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cColor?:any
cLineCloser?:any
iPlanNum?:any
iNetQty?:any
iSchSDID?:any
cbCloseDate?:any
WBID?:any
WBPID?:any
cProductNo?:any
iSdLine2ID?:any
cWhCode?:any
dOpeDate?:any
cDCStatus?:any
cPriceType?:any
iReceivedQTY?:any
iReceivedNum?:any
cProMaterialNote?:any
dqkts?:any
cSyncStatus?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }