export default class m_WorkCenter {
      columnArr=['iWcID','cWcNo','cWcName','cWcClsNo','iSchemeID','cAbilityMode','cDeptNo','iHoursPd','iWorkersPd','iShiftPd','iDevCount','iUsage','iEfficient','cEntrustNo','bKeyRes','cStatus','iLaborRate','iFixRate','iFlexRate','iOthRate','bBackflash','bWasteDirect','cDutyor','bFakeRet','cNote','cUtter','bIsSpare','cDutyName','cUtterName','cCapUnit','cLaborRateType','cCapGroupNO','iOverHours','qkts','cWcDefine1','cWcDefine2','cWcDefine3','cWcDefine4','cWcDefine5','cWcDefine6','cWcDefine7','cWcDefine8','cWcDefine9','cWcDefine10','cWcDefine11','cWcDefine12','cWcDefine13','cWcDefine14','cWcDefine15','cWcDefine16','cPrvNo','cSyncStatus','cHostName','dImportDate']
      iWcID?:any
cWcNo?:any
cWcName?:any
cWcClsNo?:any
iSchemeID?:any
cAbilityMode?:any
cDeptNo?:any
iHoursPd?:any
iWorkersPd?:any
iShiftPd?:any
iDevCount?:any
iUsage?:any
iEfficient?:any
cEntrustNo?:any
bKeyRes?:any
cStatus?:any
iLaborRate?:any
iFixRate?:any
iFlexRate?:any
iOthRate?:any
bBackflash?:any
bWasteDirect?:any
cDutyor?:any
bFakeRet?:any
cNote?:any
cUtter?:any
bIsSpare?:any
cDutyName?:any
cUtterName?:any
cCapUnit?:any
cLaborRateType?:any
cCapGroupNO?:any
iOverHours?:any
qkts?:any
cWcDefine1?:any
cWcDefine2?:any
cWcDefine3?:any
cWcDefine4?:any
cWcDefine5?:any
cWcDefine6?:any
cWcDefine7?:any
cWcDefine8?:any
cWcDefine9?:any
cWcDefine10?:any
cWcDefine11?:any
cWcDefine12?:any
cWcDefine13?:any
cWcDefine14?:any
cWcDefine15?:any
cWcDefine16?:any
cPrvNo?:any
cSyncStatus?:any
cHostName?:any
dImportDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }