export default class m_WorkRoute {
      columnArr=['iInterID','cCode','iItemID','cInvCode','cRouteNo','cBegWcNo','cRouteType','cIsDefault','dValidDate','dInvalidDate','iYieldage','cStatus','cSourStatus','cAuditTypeId','cChecker','cOperator','cVersion','iEvenLT','iEvenLot','cNote','dOpeDate','dCheckDate','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cModifier','dModifyDate','cSyncStatus']
      iInterID?:any
cCode?:any
iItemID?:any
cInvCode?:any
cRouteNo?:any
cBegWcNo?:any
cRouteType?:any
cIsDefault?:any
dValidDate?:any
dInvalidDate?:any
iYieldage?:any
cStatus?:any
cSourStatus?:any
cAuditTypeId?:any
cChecker?:any
cOperator?:any
cVersion?:any
iEvenLT?:any
iEvenLot?:any
cNote?:any
dOpeDate?:any
dCheckDate?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cModifier?:any
dModifyDate?:any
cSyncStatus?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }