export default class Sys_TableInfo0706 {
      columnArr=['Table_Id','CnName','ColumnCnName','DBServer','DataTableType','DetailCnName','DetailName','EditorType','Enable','ExpressField','FolderName','Namespace','OrderNo','ParentId','RichText','SortName','TableName','TableTrueName','UploadField','UploadMaxCount','cPageType','cClsTableName','cClsNo','cParentClsNo','cClsTableCnName','cClsKey','cClsTitle','Detail2CnName','Detail2Name','Detail3CnName','Detail3Name','cAddWhere','iBillTypeID','xColumns','xEditFormOptions','xSearchFormOptions','xTableInfo','xTreeMenuData','xExtend','xVueOption','xWheres','cGetMainSql','cMainTableAs','cOrderBy','cKeyColumn','cCodeColumn','TableEntity','cTemplate','xExtendV1','cTemplateV1','sortOrder','tableNote','Createdate','Creator','ModifyDate','Modifier']
      Table_Id?:any
CnName?:any
ColumnCnName?:any
DBServer?:any
DataTableType?:any
DetailCnName?:any
DetailName?:any
EditorType?:any
Enable?:any
ExpressField?:any
FolderName?:any
Namespace?:any
OrderNo?:any
ParentId?:any
RichText?:any
SortName?:any
TableName?:any
TableTrueName?:any
UploadField?:any
UploadMaxCount?:any
cPageType?:any
cClsTableName?:any
cClsNo?:any
cParentClsNo?:any
cClsTableCnName?:any
cClsKey?:any
cClsTitle?:any
Detail2CnName?:any
Detail2Name?:any
Detail3CnName?:any
Detail3Name?:any
cAddWhere?:any
iBillTypeID?:any
xColumns?:any
xEditFormOptions?:any
xSearchFormOptions?:any
xTableInfo?:any
xTreeMenuData?:any
xExtend?:any
xVueOption?:any
xWheres?:any
cGetMainSql?:any
cMainTableAs?:any
cOrderBy?:any
cKeyColumn?:any
cCodeColumn?:any
TableEntity?:any
cTemplate?:any
xExtendV1?:any
cTemplateV1?:any
sortOrder?:any
tableNote?:any
Createdate?:any
Creator?:any
ModifyDate?:any
Modifier?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }