export default class t_APVenDetail {
      columnArr=['iAutoID','cUser','fl','fl1','mx','mx1','ye_f','ye','cexch_name','age0_f','age0','age1_f','age1','age2_f','age2','age3_f','age3','age4_f','age4','age5_f','age5','age6_f','age6','xyed','xyye','xyqx']
      iAutoID?:any
cUser?:any
fl?:any
fl1?:any
mx?:any
mx1?:any
ye_f?:any
ye?:any
cexch_name?:any
age0_f?:any
age0?:any
age1_f?:any
age1?:any
age2_f?:any
age2?:any
age3_f?:any
age3?:any
age4_f?:any
age4?:any
age5_f?:any
age5?:any
age6_f?:any
age6?:any
xyed?:any
xyye?:any
xyqx?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }