export default class t_ApCloseBill {
      columnArr=['iVouchID','cVouchType','cVouchID','dVouchDate','cStatus','iPeriod','cDwCode','cDeptCode','cPerson','cItem_Class','cItemCode','cSSCode','cNoteNo','cCoVouchType','cCoVouchID','cDigest','cBankAccount','cexch_name','iExchRate','iAmount','iAmount_f','iRAmount','iRAmount_f','cOperator','cCancelMan','cRPMan','bPrePay','bStartFlag','cOrderNo','cCode','cPreCode','iPayForOther','cSrcFlag','cPzID','cFlag','bSend','bReceived','csItemCode','cCancelNo','cBank','cNatBank','cNatBankAccount','bFromBank','bToBank','bSure','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','qkts','cItemName','cContractType','cContractID','iAmount_s','IsWfControlled','iSource','sDLCode','RegisterFlag','iverifystate','ireturncount','dOpeDate','cChecker','dCheckDate','dModifyDate','cmodifier','iVT_ID','ibg_overflag','cbg_auditor','cbg_audittime','controlresult','cbg_itemcode','cbg_itemname','cbg_caliberkey1','cbg_caliberkeyname1','cbg_caliberkey2','cbg_caliberkeyname2','cbg_caliberkey3','cbg_caliberkeyname3','cbg_calibercode1','cbg_calibername1','cbg_calibercode2','cbg_calibername2','cbg_calibercode3','cbg_calibername3','ibg_ctrl','cbg_auditopinion','iAuditTypeID','cWhKeeper','cBankVenName','cPOCode','cPayType','iMoney','iSum','iTax','iArrMoney','iArrSum']
      iVouchID?:any
cVouchType?:any
cVouchID?:any
dVouchDate?:any
cStatus?:any
iPeriod?:any
cDwCode?:any
cDeptCode?:any
cPerson?:any
cItem_Class?:any
cItemCode?:any
cSSCode?:any
cNoteNo?:any
cCoVouchType?:any
cCoVouchID?:any
cDigest?:any
cBankAccount?:any
cexch_name?:any
iExchRate?:any
iAmount?:any
iAmount_f?:any
iRAmount?:any
iRAmount_f?:any
cOperator?:any
cCancelMan?:any
cRPMan?:any
bPrePay?:any
bStartFlag?:any
cOrderNo?:any
cCode?:any
cPreCode?:any
iPayForOther?:any
cSrcFlag?:any
cPzID?:any
cFlag?:any
bSend?:any
bReceived?:any
csItemCode?:any
cCancelNo?:any
cBank?:any
cNatBank?:any
cNatBankAccount?:any
bFromBank?:any
bToBank?:any
bSure?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
qkts?:any
cItemName?:any
cContractType?:any
cContractID?:any
iAmount_s?:any
IsWfControlled?:any
iSource?:any
sDLCode?:any
RegisterFlag?:any
iverifystate?:any
ireturncount?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
dModifyDate?:any
cmodifier?:any
iVT_ID?:any
ibg_overflag?:any
cbg_auditor?:any
cbg_audittime?:any
controlresult?:any
cbg_itemcode?:any
cbg_itemname?:any
cbg_caliberkey1?:any
cbg_caliberkeyname1?:any
cbg_caliberkey2?:any
cbg_caliberkeyname2?:any
cbg_caliberkey3?:any
cbg_caliberkeyname3?:any
cbg_calibercode1?:any
cbg_calibername1?:any
cbg_calibercode2?:any
cbg_calibername2?:any
cbg_calibercode3?:any
cbg_calibername3?:any
ibg_ctrl?:any
cbg_auditopinion?:any
iAuditTypeID?:any
cWhKeeper?:any
cBankVenName?:any
cPOCode?:any
cPayType?:any
iMoney?:any
iSum?:any
iTax?:any
iArrMoney?:any
iArrSum?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }