export default class t_APDetail {
      columnArr=['Auto_ID','iPeriod','cVouchType','cVouchSType','cVouchID','dVouchDate','dRegDate','cDwCode','cDeptCode','cPerson','cInvCode','iBVid','cCode','cItem_Class','cItemCode','csign','isignseq','ino_id','cDigest','iPrice','cexch_name','iExchRate','iDAmount','iCAmount','iDAmount_f','iCAmount_f','iDAmount_s','iCAmount_s','cOrderNo','cSSCode','cPayCode','cProcStyle','cCancelNo','cPZid','bPrePay','iFlag','cCoVouchType','cCoVouchID','cFlag','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','iClosesID','iCoClosesID','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cGLSign','iGLno_id','dPZDate','cItemName','cContractType','cContractID','BalancesGuid','dHideDate','cGatheringPlan','dCreditStart','iCreditPeriod','dGatheringDate','bCredit','cOperator','cCheckMan','iOrderType','cDLCode','idlsid','copcode','dVouDate','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','iAmount','iAmount_f','iAmount_s','iVouchAmount','iVouchAmount_f','iVouchAmount_s','dtZbjEndDate','iTax','iMoney']
      Auto_ID?:any
iPeriod?:any
cVouchType?:any
cVouchSType?:any
cVouchID?:any
dVouchDate?:any
dRegDate?:any
cDwCode?:any
cDeptCode?:any
cPerson?:any
cInvCode?:any
iBVid?:any
cCode?:any
cItem_Class?:any
cItemCode?:any
csign?:any
isignseq?:any
ino_id?:any
cDigest?:any
iPrice?:any
cexch_name?:any
iExchRate?:any
iDAmount?:any
iCAmount?:any
iDAmount_f?:any
iCAmount_f?:any
iDAmount_s?:any
iCAmount_s?:any
cOrderNo?:any
cSSCode?:any
cPayCode?:any
cProcStyle?:any
cCancelNo?:any
cPZid?:any
bPrePay?:any
iFlag?:any
cCoVouchType?:any
cCoVouchID?:any
cFlag?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
iClosesID?:any
iCoClosesID?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cGLSign?:any
iGLno_id?:any
dPZDate?:any
cItemName?:any
cContractType?:any
cContractID?:any
BalancesGuid?:any
dHideDate?:any
cGatheringPlan?:any
dCreditStart?:any
iCreditPeriod?:any
dGatheringDate?:any
bCredit?:any
cOperator?:any
cCheckMan?:any
iOrderType?:any
cDLCode?:any
idlsid?:any
copcode?:any
dVouDate?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
iAmount?:any
iAmount_f?:any
iAmount_s?:any
iVouchAmount?:any
iVouchAmount_f?:any
iVouchAmount_s?:any
dtZbjEndDate?:any
iTax?:any
iMoney?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }