export default class t_ApVouchEntry {
      columnArr=['iVouchID','cVouchID','Auto_ID','cLink','cDwCode','cDeptCode','cPerson','cItem_Class','cItemCode','cDigest','cCode','cexch_name','iExchRate','bd_c','iAmount','iAmount_f','cItemName','iAmt_s','cExpCode','iTaxRate','iTax','iNatTax','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37']
      iVouchID?:any
cVouchID?:any
Auto_ID?:any
cLink?:any
cDwCode?:any
cDeptCode?:any
cPerson?:any
cItem_Class?:any
cItemCode?:any
cDigest?:any
cCode?:any
cexch_name?:any
iExchRate?:any
bd_c?:any
iAmount?:any
iAmount_f?:any
cItemName?:any
iAmt_s?:any
cExpCode?:any
iTaxRate?:any
iTax?:any
iNatTax?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }