export default class t_ApNote {
      columnArr=['iVouchID','cLink','cVouchType','cVouchID','cStatus','cBank','cDwCode','cDeptCode','cPerson','cItem_Class','cItemCode','cDigest','cCode','iAmount','iRate','iRAmount','cEndorser','iEndorAmount','dSignDate','dExpireDate','dReceiptDate','cOperator','bStartFlag','cFlag','iCloseID','VT_ID','qkts','cItemName','cReceiver','cReceiveBank','cReceiveAccount','iEndorAmount_Local','iAmount_Local','iRAmount_Local','cSettleCode','cBill','cSuperBank','cexch_name','cEndorserName','cDWName','cPayBillAccount','cPayBillBankID','cPayBillBankAdress','dPayExpireDate','dProxyPayBank','dProxyPayBankID','cRemitAdress','cReceiverCode','cReceiveBankID','cReceiveAdress','cPurpose','cPayMode','dTransferDate','iSettleAmount','iOverAmount','cCompactID','cPayAddress','cAgreementID','cSendDesc','iAccessories','cConsignPayee','cRemark','cAPDesc','nfrat','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','iVT_ID','dOpeDate','cChecker','dCheckDate','dModifyDate','cmodifier']
      iVouchID?:any
cLink?:any
cVouchType?:any
cVouchID?:any
cStatus?:any
cBank?:any
cDwCode?:any
cDeptCode?:any
cPerson?:any
cItem_Class?:any
cItemCode?:any
cDigest?:any
cCode?:any
iAmount?:any
iRate?:any
iRAmount?:any
cEndorser?:any
iEndorAmount?:any
dSignDate?:any
dExpireDate?:any
dReceiptDate?:any
cOperator?:any
bStartFlag?:any
cFlag?:any
iCloseID?:any
VT_ID?:any
qkts?:any
cItemName?:any
cReceiver?:any
cReceiveBank?:any
cReceiveAccount?:any
iEndorAmount_Local?:any
iAmount_Local?:any
iRAmount_Local?:any
cSettleCode?:any
cBill?:any
cSuperBank?:any
cexch_name?:any
cEndorserName?:any
cDWName?:any
cPayBillAccount?:any
cPayBillBankID?:any
cPayBillBankAdress?:any
dPayExpireDate?:any
dProxyPayBank?:any
dProxyPayBankID?:any
cRemitAdress?:any
cReceiverCode?:any
cReceiveBankID?:any
cReceiveAdress?:any
cPurpose?:any
cPayMode?:any
dTransferDate?:any
iSettleAmount?:any
iOverAmount?:any
cCompactID?:any
cPayAddress?:any
cAgreementID?:any
cSendDesc?:any
iAccessories?:any
cConsignPayee?:any
cRemark?:any
cAPDesc?:any
nfrat?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
iVT_ID?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
dModifyDate?:any
cmodifier?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }