export default class t_ARCustLog {
      columnArr=['dDate','dCheckDate','cCode','cVouchType','cInvCode','cUser','iAutoID','iInterID','ID','iUnitPrice','iQuantity','iTaxRate','iTaxUnitPrice','iMoney','iTax','iSum','iNum','cInvName','cInvStd','cItemClsNo','cComUnitCode','cNote','iLineSumID','cCustNo','dBegDate','dEndDate','cDefine1','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cReconciliation','cShipAddress']
      dDate?:any
dCheckDate?:any
cCode?:any
cVouchType?:any
cInvCode?:any
cUser?:any
iAutoID?:any
iInterID?:any
ID?:any
iUnitPrice?:any
iQuantity?:any
iTaxRate?:any
iTaxUnitPrice?:any
iMoney?:any
iTax?:any
iSum?:any
iNum?:any
cInvName?:any
cInvStd?:any
cItemClsNo?:any
cComUnitCode?:any
cNote?:any
iLineSumID?:any
cCustNo?:any
dBegDate?:any
dEndDate?:any
cDefine1?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cReconciliation?:any
cShipAddress?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }