export default class t_BasMaterialType {
      columnArr=['iInterID','cMaterialNo','cMaterialName','cMaterialClsNo','cComUnitCode','cFormula','cFormula2','cMakeup','cAttributeName1','cAttributeName2','cAttributeName3','cAttributeName4','cAttributeName5','cAttributeName6','cAttributeName7','cAttributeName8','cAttributeName9','cAttributeName10','cAttributeValue1','cAttributeValue2','cAttributeValue3','cAttributeValue4','cAttributeValue5','cAttributeValue6','cAttributeValue7','cAttributeValue8','cAttributeValue9','cAttributeValue10','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16']
      iInterID?:any
cMaterialNo?:any
cMaterialName?:any
cMaterialClsNo?:any
cComUnitCode?:any
cFormula?:any
cFormula2?:any
cMakeup?:any
cAttributeName1?:any
cAttributeName2?:any
cAttributeName3?:any
cAttributeName4?:any
cAttributeName5?:any
cAttributeName6?:any
cAttributeName7?:any
cAttributeName8?:any
cAttributeName9?:any
cAttributeName10?:any
cAttributeValue1?:any
cAttributeValue2?:any
cAttributeValue3?:any
cAttributeValue4?:any
cAttributeValue5?:any
cAttributeValue6?:any
cAttributeValue7?:any
cAttributeValue8?:any
cAttributeValue9?:any
cAttributeValue10?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }