export default class t_BomWorkItem {
      columnArr=['cCode','iInterID','iAutoID','cInvCode','cSubInvCode','cGroupNo','iSubQty','bMaster','cMoldNo','cSubMoldNo','cPosition','cProductNo','cMaterialNo','cColorNo','cRelateInvCode','cMixInvCode','iMoldGross','iNetWeight','iGapPercent','iNetWeightDiff','cPrintColor','cProductSolidSize','cProductPlaneSize','cWhCode','cDetailNote','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDefine62','cDefine63','cDefine64','cDefine65','cDefine66','cDefine67','cDefine68','cDefine69','cDefine70','cDefine71','cDefine72','cDefine73','cDefine74','cDefine75','cDefine76','cDefine77']
      cCode?:any
iInterID?:any
iAutoID?:any
cInvCode?:any
cSubInvCode?:any
cGroupNo?:any
iSubQty?:any
bMaster?:any
cMoldNo?:any
cSubMoldNo?:any
cPosition?:any
cProductNo?:any
cMaterialNo?:any
cColorNo?:any
cRelateInvCode?:any
cMixInvCode?:any
iMoldGross?:any
iNetWeight?:any
iGapPercent?:any
iNetWeightDiff?:any
cPrintColor?:any
cProductSolidSize?:any
cProductPlaneSize?:any
cWhCode?:any
cDetailNote?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDefine62?:any
cDefine63?:any
cDefine64?:any
cDefine65?:any
cDefine66?:any
cDefine67?:any
cDefine68?:any
cDefine69?:any
cDefine70?:any
cDefine71?:any
cDefine72?:any
cDefine73?:any
cDefine74?:any
cDefine75?:any
cDefine76?:any
cDefine77?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }