export default class t_BomImport {
      columnArr=['iInterID','cCode','iItemID','cInvCode','cBomType','cBomTypeName','cInvName','cInvStd','cItemClsNo','cComUnitCode','cVersion','cOperator','dOpeDate','cCheckNote','cChecker','dCheckDate','cStatus','cStatusName','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','iAuditTypeID','iVT_ID','qkts','iEntryID','iSeqID','iSubItemID','cSubInvCode','cSubInvName','cSubInvStd','cSubItemClsNo','cSubComUnitCode','iBatQty','iParentQty','iSubQty','iQtyPer','cSubRelate','cSubRelateName','dValidDate','dInvalidDate','iScrapt','iOffsetLT','cSupplyMode','cSupplyModeName','cSelect','cSelectName','iPercent','iRetOffsetLT','iRetPercent','cUtterType','cEco','cEcoNote','cDeductType','cDeductTypeName','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cAddresshead','cEnterprisehead','cLabelhead','cSize1','cSize2','cSize3','cSize4','cSize5','cSize6','cSize7','cSize8','cSize9','cSize10','cSize11','cSize12','cSize13','cSize14','cSize15','cSize16','cBarCode','cSize1Sub','cSize2Sub','cSize3Sub','cSize4Sub','cSize5Sub','cSize6Sub','cSize7Sub','cSize8Sub','cSize9Sub','cSize10Sub','cSize11Sub','cSize12Sub','cSize13Sub','cSize14Sub','cSize15Sub','cSize16Sub','cEnterprise','cAddress','cLabel','cFile','cCheckOut','cLicence','cLinear','cWGroupCode','fGrossWeight','fNetWeight','cVGroupCode','fVolume','flength','fWidth','fHeight','fDiameter','fMinDiameter','fQtyPerBox','fWeightPerM','fPicQtyPer','iInvSCost','iInvSPrice','bService','bSmall','cMaterial','cColor','bModelCompleted','bMps','bProxyForeign','bSelf','bPurchase','bSale','bModelCompletedSub','cDefWhNoSub','bMpsSub','cGetItemType','cWhCode','cNoteSub','cScraptExp','cVenCode','cHostName','cSyncStatus','dImportDate','iErpInterID','iErpEntryID']
      iInterID?:any
cCode?:any
iItemID?:any
cInvCode?:any
cBomType?:any
cBomTypeName?:any
cInvName?:any
cInvStd?:any
cItemClsNo?:any
cComUnitCode?:any
cVersion?:any
cOperator?:any
dOpeDate?:any
cCheckNote?:any
cChecker?:any
dCheckDate?:any
cStatus?:any
cStatusName?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
iAuditTypeID?:any
iVT_ID?:any
qkts?:any
iEntryID?:any
iSeqID?:any
iSubItemID?:any
cSubInvCode?:any
cSubInvName?:any
cSubInvStd?:any
cSubItemClsNo?:any
cSubComUnitCode?:any
iBatQty?:any
iParentQty?:any
iSubQty?:any
iQtyPer?:any
cSubRelate?:any
cSubRelateName?:any
dValidDate?:any
dInvalidDate?:any
iScrapt?:any
iOffsetLT?:any
cSupplyMode?:any
cSupplyModeName?:any
cSelect?:any
cSelectName?:any
iPercent?:any
iRetOffsetLT?:any
iRetPercent?:any
cUtterType?:any
cEco?:any
cEcoNote?:any
cDeductType?:any
cDeductTypeName?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cAddresshead?:any
cEnterprisehead?:any
cLabelhead?:any
cSize1?:any
cSize2?:any
cSize3?:any
cSize4?:any
cSize5?:any
cSize6?:any
cSize7?:any
cSize8?:any
cSize9?:any
cSize10?:any
cSize11?:any
cSize12?:any
cSize13?:any
cSize14?:any
cSize15?:any
cSize16?:any
cBarCode?:any
cSize1Sub?:any
cSize2Sub?:any
cSize3Sub?:any
cSize4Sub?:any
cSize5Sub?:any
cSize6Sub?:any
cSize7Sub?:any
cSize8Sub?:any
cSize9Sub?:any
cSize10Sub?:any
cSize11Sub?:any
cSize12Sub?:any
cSize13Sub?:any
cSize14Sub?:any
cSize15Sub?:any
cSize16Sub?:any
cEnterprise?:any
cAddress?:any
cLabel?:any
cFile?:any
cCheckOut?:any
cLicence?:any
cLinear?:any
cWGroupCode?:any
fGrossWeight?:any
fNetWeight?:any
cVGroupCode?:any
fVolume?:any
flength?:any
fWidth?:any
fHeight?:any
fDiameter?:any
fMinDiameter?:any
fQtyPerBox?:any
fWeightPerM?:any
fPicQtyPer?:any
iInvSCost?:any
iInvSPrice?:any
bService?:any
bSmall?:any
cMaterial?:any
cColor?:any
bModelCompleted?:any
bMps?:any
bProxyForeign?:any
bSelf?:any
bPurchase?:any
bSale?:any
bModelCompletedSub?:any
cDefWhNoSub?:any
bMpsSub?:any
cGetItemType?:any
cWhCode?:any
cNoteSub?:any
cScraptExp?:any
cVenCode?:any
cHostName?:any
cSyncStatus?:any
dImportDate?:any
iErpInterID?:any
iErpEntryID?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }