export default class t_BomEntryOrder {
      columnArr=['cCode','iInterID','iEntryID','iSeqID','iSubItemID','cSubInvCode','iBatQty','iParentQty','iSubQty','cSubRelate','dValidDate','dInvalidDate','iScrapt','iOffsetLT','cSupplyMode','cSelect','iPercent','iRetOffsetLT','iRetPercent','cUtterType','cEco','cEcoNote','cNote','cDeductType','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cGetItemType','cWhCode','cScraptExp','dOpeDate','cVenCode','cPrintColor','bSelf','bDaBan','cItemClsNo','cTypeSetting','cProductSolidSize','cProductPlaneSize','iOpenQty','iBanQty','iMolecularQty','iDenominatorQty','cWorkRouteType','cAttributes1','cAttributes2','cAttributes3','cAttributes4','cAttributes5','cAttributes6','cAttributes7','cAttributes8','cAttributes9','cAttributes10','cAttributes11','cAttributes12','cAttributes13','cAttributes14','cAttributes15','cAttributes16','cInvName','cInvStd','cUnitCode']
      cCode?:any
iInterID?:any
iEntryID?:any
iSeqID?:any
iSubItemID?:any
cSubInvCode?:any
iBatQty?:any
iParentQty?:any
iSubQty?:any
cSubRelate?:any
dValidDate?:any
dInvalidDate?:any
iScrapt?:any
iOffsetLT?:any
cSupplyMode?:any
cSelect?:any
iPercent?:any
iRetOffsetLT?:any
iRetPercent?:any
cUtterType?:any
cEco?:any
cEcoNote?:any
cNote?:any
cDeductType?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cGetItemType?:any
cWhCode?:any
cScraptExp?:any
dOpeDate?:any
cVenCode?:any
cPrintColor?:any
bSelf?:any
bDaBan?:any
cItemClsNo?:any
cTypeSetting?:any
cProductSolidSize?:any
cProductPlaneSize?:any
iOpenQty?:any
iBanQty?:any
iMolecularQty?:any
iDenominatorQty?:any
cWorkRouteType?:any
cAttributes1?:any
cAttributes2?:any
cAttributes3?:any
cAttributes4?:any
cAttributes5?:any
cAttributes6?:any
cAttributes7?:any
cAttributes8?:any
cAttributes9?:any
cAttributes10?:any
cAttributes11?:any
cAttributes12?:any
cAttributes13?:any
cAttributes14?:any
cAttributes15?:any
cAttributes16?:any
cInvName?:any
cInvStd?:any
cUnitCode?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }