export default class t_BomHeadOrder {
      columnArr=['iInterID','cCode','iItemID','cInvCode','cBomType','cVersion','cOperator','dOpeDate','cCheckNote','cChecker','dCheckDate','cStatus','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','iAuditTypeID','iVT_ID','qkts','cModifier','dModifyDate','cCustNo','bNew','bWorkItem','cSdOrderNo','iSdLineID','cCustName','cCusPerson','cBusType','cSTCode','cCusPhoneNum','cPersonCode','cDeptNo','cSCCode','cAddress','cSdOrderType','cSdInvCode','cSdInvName','cDesOrderNo','cSouOrderNo','dDeliveryDate']
      iInterID?:any
cCode?:any
iItemID?:any
cInvCode?:any
cBomType?:any
cVersion?:any
cOperator?:any
dOpeDate?:any
cCheckNote?:any
cChecker?:any
dCheckDate?:any
cStatus?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
iAuditTypeID?:any
iVT_ID?:any
qkts?:any
cModifier?:any
dModifyDate?:any
cCustNo?:any
bNew?:any
bWorkItem?:any
cSdOrderNo?:any
iSdLineID?:any
cCustName?:any
cCusPerson?:any
cBusType?:any
cSTCode?:any
cCusPhoneNum?:any
cPersonCode?:any
cDeptNo?:any
cSCCode?:any
cAddress?:any
cSdOrderType?:any
cSdInvCode?:any
cSdInvName?:any
cDesOrderNo?:any
cSouOrderNo?:any
dDeliveryDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }