export default class t_CostItemDiffDetail {
      columnArr=['iAutoID','iYear','iMonth','cType','cRptNo','cWoNo','dDate','iProcessID','iWoSeqID','cSeqNote','cWcNo','cResourceNo','cCode','cCode2','cCode3','cInvCode','cInvName','cInvStd','cComUnitCode','cItemClsNo','iNormalQty','iActQty','iDiffQty','iNormalAmount','iActAmount','iDiffAmount','iNormalPrice','iActPrice','dBegDate','dEndDate','cWorkItemNo','iQtyPer','iRptQty','cNote','cUser','cMiNo','cStatus','iWoInterID','iWoEntryID','iWoEntrySeqID','iWipInvQty','iDiffWipQty','cWhNo','dSelect']
      iAutoID?:any
iYear?:any
iMonth?:any
cType?:any
cRptNo?:any
cWoNo?:any
dDate?:any
iProcessID?:any
iWoSeqID?:any
cSeqNote?:any
cWcNo?:any
cResourceNo?:any
cCode?:any
cCode2?:any
cCode3?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any
iNormalQty?:any
iActQty?:any
iDiffQty?:any
iNormalAmount?:any
iActAmount?:any
iDiffAmount?:any
iNormalPrice?:any
iActPrice?:any
dBegDate?:any
dEndDate?:any
cWorkItemNo?:any
iQtyPer?:any
iRptQty?:any
cNote?:any
cUser?:any
cMiNo?:any
cStatus?:any
iWoInterID?:any
iWoEntryID?:any
iWoEntrySeqID?:any
iWipInvQty?:any
iDiffWipQty?:any
cWhNo?:any
dSelect?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }