export default class t_CostItemMonth {
      columnArr=['iInterID','cType','cInvCode','cInvName','cInvStd','cComUnitCode','cWhCode','cWcNo','iQuantity','iWeekID','iTaxUnitPrice','iMoney','iYear','iMonth','iProQty','iProAmount','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16']
      iInterID?:any
cType?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cWhCode?:any
cWcNo?:any
iQuantity?:any
iWeekID?:any
iTaxUnitPrice?:any
iMoney?:any
iYear?:any
iMonth?:any
iProQty?:any
iProAmount?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }