export default class t_CostRealLevel {
      columnArr=['iAutoID','iYear','iMonth','cMiNo','cInvCode','iLowCode','cRootNo','bCost','bSelf','bSale','bPurchase','bCommission','cPlanMethod','bMPS','iWorkQty','iInvQty','iNorMatCost','iNorMatAssCost','iNorLabCost','iNorManuCost','iActMatCost','iActMatAssCost','iActLabCost','iActManuCost','iNorCost','iActCost','cItemType','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16']
      iAutoID?:any
iYear?:any
iMonth?:any
cMiNo?:any
cInvCode?:any
iLowCode?:any
cRootNo?:any
bCost?:any
bSelf?:any
bSale?:any
bPurchase?:any
bCommission?:any
cPlanMethod?:any
bMPS?:any
iWorkQty?:any
iInvQty?:any
iNorMatCost?:any
iNorMatAssCost?:any
iNorLabCost?:any
iNorManuCost?:any
iActMatCost?:any
iActMatAssCost?:any
iActLabCost?:any
iActManuCost?:any
iNorCost?:any
iActCost?:any
cItemType?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }