export default class t_CurrentStockDetail {
      columnArr=['cBillType','cBillNo','ID','cInvCode','cInvName','cComUnitCode','cInvStd','cItemClsNo','cAssComUnitCode','cWhCode','cWhName','cBatch','fInQuantity','fInNum','fOutQuantity','fOutNum','cPersonCode','cPersonName','cStatus','cStatusName','cDeptNo','cDeptName','dDate','cUserCode']
      cBillType?:any
cBillNo?:any
ID?:any
cInvCode?:any
cInvName?:any
cComUnitCode?:any
cInvStd?:any
cItemClsNo?:any
cAssComUnitCode?:any
cWhCode?:any
cWhName?:any
cBatch?:any
fInQuantity?:any
fInNum?:any
fOutQuantity?:any
fOutNum?:any
cPersonCode?:any
cPersonName?:any
cStatus?:any
cStatusName?:any
cDeptNo?:any
cDeptName?:any
dDate?:any
cUserCode?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }