export default class t_Customer {
      columnArr=['cCustNo','cCustNo','cCustName','cCustAbbName','cClsNo','cDCCode','cTrade','cGrade','cCusAddress','cCusPostCode','cCusRegCode','cCusBank','cCusAccount','dCusDevDate','cCusLPerson','cCusEmail','cCusPerson','cCusPhone','cCusFax','cCusBP','cCusHand','cCusPPerson','iCusDisRate','cCusCreGrade','iCusCreLine','iCusCreDate','cCusPayCond','cCusOAddress','cCusOType','cCusHeadCode','cCusWhCode','cCusDepart','iARMoney','dLastDate','iLastMoney','dLRDate','iLRMoney','cCusDefine1','cCusDefine2','cCusDefine3','cCreatePerson','cModifyPerson','dModifyDate','cCusDefine4','cCusDefine5','cCusDefine6','cCusDefine7','cCusDefine8','cCusDefine9','cCusDefine10','cCusDefine11','cCusDefine12','cCusDefine13','cCusDefine14','cCusDefine15','cCusDefine16','pubqkts','bCusDomestic','bCusOverseas','cExch_name','cSSCode','cBusType','cPayCode','cBarCode','iRegCapital','iEmployeeNum','iGradeABC','iCostGrade','cRelVendor','iId','cOfferGrade','iOfferRate','cInvoiceCompany','bCredit','bCreditDate','bCreditByHead','bCreditByDept','cCusContactCode','cCusCountryCode','cCusPortCode','cPrimaryVen','fCommisionRate','fInsueRate','bShop','cCusBankCode','cCusSAProtocol','cCusOtherProtocol','cCusSSCode','cCusCreditCompany','fCusDiscountRate','cNote','cPrvNo','cCusSTCode','dEndDate','iFHDays','fFHVolume','iDispatchDays','iShipDays','iManuDays','cZXBCode','iFHCircle','bCustSmall','dReconciliaDate','iCustID','iCusTaxRate','cHostName']
      cCustNo?:any
cCustNo?:any
cCustName?:any
cCustAbbName?:any
cClsNo?:any
cDCCode?:any
cTrade?:any
cGrade?:any
cCusAddress?:any
cCusPostCode?:any
cCusRegCode?:any
cCusBank?:any
cCusAccount?:any
dCusDevDate?:any
cCusLPerson?:any
cCusEmail?:any
cCusPerson?:any
cCusPhone?:any
cCusFax?:any
cCusBP?:any
cCusHand?:any
cCusPPerson?:any
iCusDisRate?:any
cCusCreGrade?:any
iCusCreLine?:any
iCusCreDate?:any
cCusPayCond?:any
cCusOAddress?:any
cCusOType?:any
cCusHeadCode?:any
cCusWhCode?:any
cCusDepart?:any
iARMoney?:any
dLastDate?:any
iLastMoney?:any
dLRDate?:any
iLRMoney?:any
cCusDefine1?:any
cCusDefine2?:any
cCusDefine3?:any
cCreatePerson?:any
cModifyPerson?:any
dModifyDate?:any
cCusDefine4?:any
cCusDefine5?:any
cCusDefine6?:any
cCusDefine7?:any
cCusDefine8?:any
cCusDefine9?:any
cCusDefine10?:any
cCusDefine11?:any
cCusDefine12?:any
cCusDefine13?:any
cCusDefine14?:any
cCusDefine15?:any
cCusDefine16?:any
pubqkts?:any
bCusDomestic?:any
bCusOverseas?:any
cExch_name?:any
cSSCode?:any
cBusType?:any
cPayCode?:any
cBarCode?:any
iRegCapital?:any
iEmployeeNum?:any
iGradeABC?:any
iCostGrade?:any
cRelVendor?:any
iId?:any
cOfferGrade?:any
iOfferRate?:any
cInvoiceCompany?:any
bCredit?:any
bCreditDate?:any
bCreditByHead?:any
bCreditByDept?:any
cCusContactCode?:any
cCusCountryCode?:any
cCusPortCode?:any
cPrimaryVen?:any
fCommisionRate?:any
fInsueRate?:any
bShop?:any
cCusBankCode?:any
cCusSAProtocol?:any
cCusOtherProtocol?:any
cCusSSCode?:any
cCusCreditCompany?:any
fCusDiscountRate?:any
cNote?:any
cPrvNo?:any
cCusSTCode?:any
dEndDate?:any
iFHDays?:any
fFHVolume?:any
iDispatchDays?:any
iShipDays?:any
iManuDays?:any
cZXBCode?:any
iFHCircle?:any
bCustSmall?:any
dReconciliaDate?:any
iCustID?:any
iCusTaxRate?:any
cHostName?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }