export default class t_CusItemPrice {
      columnArr=['iInterID','cCustNo','cInvCode','dEnableDate','dDisableDate','cExch_Name','bSales','iLowerLimit','cSupplyType','bTaxCost','cTermCode','iInvSCost','iInvSalesCost','iCusDisrate','iCusMinPrice','iInvNowCost','iUnitPrice','iTaxRate','iTaxUnitPrice','iCJPInterID','iCJPID','cCJPCode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10']
      iInterID?:any
cCustNo?:any
cInvCode?:any
dEnableDate?:any
dDisableDate?:any
cExch_Name?:any
bSales?:any
iLowerLimit?:any
cSupplyType?:any
bTaxCost?:any
cTermCode?:any
iInvSCost?:any
iInvSalesCost?:any
iCusDisrate?:any
iCusMinPrice?:any
iInvNowCost?:any
iUnitPrice?:any
iTaxRate?:any
iTaxUnitPrice?:any
iCJPInterID?:any
iCJPID?:any
cCJPCode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }