export default class t_CusJustPriceEntry {
      columnArr=['ID','iInterID','cCJPCode','cOperationType','dEnableDate','dDisableDate','bSales','bInvValid','cCustNo','cInvCode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','iLowerLimit','cPriceID','iInvSCost','iInvSalesCost','iCusDisrate','iCusMinPrice','iInvNowCost','iUnitPrice','iTaxRate','iTaxUnitPrice','cExch_Name','cTermCode','cNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cCustName','cCustAbbName','cClsNo']
      ID?:any
iInterID?:any
cCJPCode?:any
cOperationType?:any
dEnableDate?:any
dDisableDate?:any
bSales?:any
bInvValid?:any
cCustNo?:any
cInvCode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
iLowerLimit?:any
cPriceID?:any
iInvSCost?:any
iInvSalesCost?:any
iCusDisrate?:any
iCusMinPrice?:any
iInvNowCost?:any
iUnitPrice?:any
iTaxRate?:any
iTaxUnitPrice?:any
cExch_Name?:any
cTermCode?:any
cNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cCustName?:any
cCustAbbName?:any
cClsNo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }