export default class t_EqptMtPlanEntry {
      columnArr=['iInterID','iMPLineID','cMtPlanNo','cLineCloser','cbCloseDate','cPlanType','cPartCode','cPartName','cPartClsNo','cSpeType','iPartNum','mUnitPrice','mTotalMoney','cNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37']
      iInterID?:any
iMPLineID?:any
cMtPlanNo?:any
cLineCloser?:any
cbCloseDate?:any
cPlanType?:any
cPartCode?:any
cPartName?:any
cPartClsNo?:any
cSpeType?:any
iPartNum?:any
mUnitPrice?:any
mTotalMoney?:any
cNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }