export default class t_HrCerCate {
      columnArr=['iInterID','cCode','cCerCode','iCerValidity','dBeginDate','dExceedDate','fScore','fCerValueNew','bCerStatus','cPersonCode','cProductLine','dOpeDate','cOperator','dCheckDate','cChecker','cCloser','cStatus','cNote','cDefine1','cDefine2','cDefine3','cDefine5','cDefine4','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16']
      iInterID?:any
cCode?:any
cCerCode?:any
iCerValidity?:any
dBeginDate?:any
dExceedDate?:any
fScore?:any
fCerValueNew?:any
bCerStatus?:any
cPersonCode?:any
cProductLine?:any
dOpeDate?:any
cOperator?:any
dCheckDate?:any
cChecker?:any
cCloser?:any
cStatus?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine5?:any
cDefine4?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }