export default class t_HrPerUnemInsure {
      columnArr=['iInterID','cPersonCode','iRecordID','cStartPayDate','bSwitchFlag','dEndDate','cDepCode','dSwitchOutDate','iCorpPullScale','cPersonType','cSwitchInUnit','cSwitchOutUnit','cPerClass','iTotalPayMon','iCorpScale','cAddCause','cDocuYear','cDocuMonth','dStartDate','dOpenDate','dKeepDate','iCustBase','cAccountFlag','dAccountDate','cEnsureCode','cReduCause','cComputercode','dSwitchInDate','dDestroyDate','iInviScale']
      iInterID?:any
cPersonCode?:any
iRecordID?:any
cStartPayDate?:any
bSwitchFlag?:any
dEndDate?:any
cDepCode?:any
dSwitchOutDate?:any
iCorpPullScale?:any
cPersonType?:any
cSwitchInUnit?:any
cSwitchOutUnit?:any
cPerClass?:any
iTotalPayMon?:any
iCorpScale?:any
cAddCause?:any
cDocuYear?:any
cDocuMonth?:any
dStartDate?:any
dOpenDate?:any
dKeepDate?:any
iCustBase?:any
cAccountFlag?:any
dAccountDate?:any
cEnsureCode?:any
cReduCause?:any
cComputercode?:any
dSwitchInDate?:any
dDestroyDate?:any
iInviScale?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }