export default class t_HrRoutineCheckEntry {
      columnArr=['iInterID','iLineID','cCode','cClasses','cDutyclass','bSumUp','cCheckProNum','iCheckNum','cCheckNo','bWriteback','cWalkOrder','cUnusualType','cCheckPro','cCheckDetail','cCheckNorm','iScore','cRewPunNorm','cDepCode','cProductLine','cJobCode','cPersonCode','cPersonName','bQualiFied','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10']
      iInterID?:any
iLineID?:any
cCode?:any
cClasses?:any
cDutyclass?:any
bSumUp?:any
cCheckProNum?:any
iCheckNum?:any
cCheckNo?:any
bWriteback?:any
cWalkOrder?:any
cUnusualType?:any
cCheckPro?:any
cCheckDetail?:any
cCheckNorm?:any
iScore?:any
cRewPunNorm?:any
cDepCode?:any
cProductLine?:any
cJobCode?:any
cPersonCode?:any
cPersonName?:any
bQualiFied?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }