export default class t_HrPerTreInsure {
      columnArr=['iInterID','cPersonCode','iRecordID','cSwitchOutUnit','cDepcode','cPersonType','dKeepDate','cPerClass','bSwitchFlag','cAddCause','cBearCase','dEndDate','iCorpScale','iInviScale','cReduCause','dSwitchOutDate','dStartDate','iCorpPullScale','cPersonName','cDocuYear','dOpenDate','iCustBase','cDocuMonth','cAccountFlag','dAccountDate','cEnsureCode','cMedcardFlag','cPerAccount','cStartPayDate','dSwitchInDate','dDestroyDate','cSwitchInUnit','cWorkType']
      iInterID?:any
cPersonCode?:any
iRecordID?:any
cSwitchOutUnit?:any
cDepcode?:any
cPersonType?:any
dKeepDate?:any
cPerClass?:any
bSwitchFlag?:any
cAddCause?:any
cBearCase?:any
dEndDate?:any
iCorpScale?:any
iInviScale?:any
cReduCause?:any
dSwitchOutDate?:any
dStartDate?:any
iCorpPullScale?:any
cPersonName?:any
cDocuYear?:any
dOpenDate?:any
iCustBase?:any
cDocuMonth?:any
cAccountFlag?:any
dAccountDate?:any
cEnsureCode?:any
cMedcardFlag?:any
cPerAccount?:any
cStartPayDate?:any
dSwitchInDate?:any
dDestroyDate?:any
cSwitchInUnit?:any
cWorkType?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }