export default class t_HrOmJobChange {
      columnArr=['iInterID','cCode','cPersonCode','cJobCode','cJobCodeNew','cJobName','cJobNameNew','cMoveType','iWoSeqIDNew','cDepCode','cDepCodeIn','cClasses','cClassesNew','cWorkStatus','cWorkStatusNew','cMemberShip','cMemberShipNew','cDutyclass','cDutyclassNew','dDate','cAssess','cDeadline','cAllotFactor','cReason','cAllotcReason','bJobChange','bRevaluate','cOperator','dOpeDate','cChecker','dCheckDate','cStatus','cNote','cDefine1','cDefine2','cDefine3','cDefine5','cDefine4','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16']
      iInterID?:any
cCode?:any
cPersonCode?:any
cJobCode?:any
cJobCodeNew?:any
cJobName?:any
cJobNameNew?:any
cMoveType?:any
iWoSeqIDNew?:any
cDepCode?:any
cDepCodeIn?:any
cClasses?:any
cClassesNew?:any
cWorkStatus?:any
cWorkStatusNew?:any
cMemberShip?:any
cMemberShipNew?:any
cDutyclass?:any
cDutyclassNew?:any
dDate?:any
cAssess?:any
cDeadline?:any
cAllotFactor?:any
cReason?:any
cAllotcReason?:any
bJobChange?:any
bRevaluate?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cStatus?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine5?:any
cDefine4?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }