export default class t_IAJustVouch {
      columnArr=['ID','cJVCode','cVouchType','cWhCode','bRdFlag','dJVDate','cUnitCode','cDepCode','cPersonCode','cRdCode','cBusType','cOperator','dOpeDate','cChecker','dCheckDate','cStatus','cHandler','cJVMemo','cJVDefine1','cJVDefine2','cJVDefine3','cAccounter','bPZ','VT_ID','cAuto','dnmaketime','iNetLock','bSale','ufts','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cModifier','dModifyDate']
      ID?:any
cJVCode?:any
cVouchType?:any
cWhCode?:any
bRdFlag?:any
dJVDate?:any
cUnitCode?:any
cDepCode?:any
cPersonCode?:any
cRdCode?:any
cBusType?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cStatus?:any
cHandler?:any
cJVMemo?:any
cJVDefine1?:any
cJVDefine2?:any
cJVDefine3?:any
cAccounter?:any
bPZ?:any
VT_ID?:any
cAuto?:any
dnmaketime?:any
iNetLock?:any
bSale?:any
ufts?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cModifier?:any
dModifyDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }