export default class t_IAGUIDataSettle {
      columnArr=['iAutoID','hselect','bTrack','bAccFlag','cvouchname','cRdName','cComUnitName','cwhname','cvaluetype','cComUnitCode','cInvName','cInvStd','cVenAbbName','iInvRCost','iInvRPrice','cItemClsNo','cSize1','cSize2','cSize3','cSize4','cSize5','cSize6','cSize7','cSize8','cSize9','cSize10','cSize11','cSize12','cSize13','cSize14','cSize15','cSize16','bRdFlag','cBusType','cBusCode','cVouCode','ID','ValueID','JustID','dVouDate','dKeepDate','iMonth','iPZID','iPZDate','cPZtype','cPZdigest','cInvHead','cDifHead','cOppHead','cVouType','cPTCode','cSTCode','cWhCode','cAccDep','cInvCode','cRdCode','cVenCode','cCusCode','cOrderCode','cARVCode','cBillCode','cDLCode','cPSPCode','cProCode','cDepCode','cPersonCode','cHandler','iquantity','iunitcost','iprice','cBatchCode','cAccounter','cMaker','bFlag','bMoneyFlag','bSale','iSQuantity','iSMoney','iSUnitcost','dSDate','cMemo','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cFree1','cFree2','cPZID','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cItem_class','cItemCode','cName','cItemCName','noJustQuantity','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','psvsid','cCXHDcode','cCXFScode','cBatchia','dMadeDateia','iMassDateia','cMassUnit','dVDateia','cproordercode','iproorderid','iproorderids','cworkprocode','cworkprocodedis','cworkcentercode','cworkcentername','cendcode','csaleordercode','cIMOrdercode','isaleorderid','isaleordersid','isaleorderids','centrustordercode','ientrustorderid','ientrustordersid','cpurordercode','ipurordersid','idlsid','strContractCode','inum','cAssUnit','exoCode','iExRowno','consignMentCode','iconsignmentautoid','imaterialfee','iprocessfee','cVerifier','cvmivencode','AutoID','ibg_ctrl','iTrans','iLevel','bEn','bFX','ufts','bCosting','dnOrderTime','cdemandcode','cdemandmemo']
      iAutoID?:any
hselect?:any
bTrack?:any
bAccFlag?:any
cvouchname?:any
cRdName?:any
cComUnitName?:any
cwhname?:any
cvaluetype?:any
cComUnitCode?:any
cInvName?:any
cInvStd?:any
cVenAbbName?:any
iInvRCost?:any
iInvRPrice?:any
cItemClsNo?:any
cSize1?:any
cSize2?:any
cSize3?:any
cSize4?:any
cSize5?:any
cSize6?:any
cSize7?:any
cSize8?:any
cSize9?:any
cSize10?:any
cSize11?:any
cSize12?:any
cSize13?:any
cSize14?:any
cSize15?:any
cSize16?:any
bRdFlag?:any
cBusType?:any
cBusCode?:any
cVouCode?:any
ID?:any
ValueID?:any
JustID?:any
dVouDate?:any
dKeepDate?:any
iMonth?:any
iPZID?:any
iPZDate?:any
cPZtype?:any
cPZdigest?:any
cInvHead?:any
cDifHead?:any
cOppHead?:any
cVouType?:any
cPTCode?:any
cSTCode?:any
cWhCode?:any
cAccDep?:any
cInvCode?:any
cRdCode?:any
cVenCode?:any
cCusCode?:any
cOrderCode?:any
cARVCode?:any
cBillCode?:any
cDLCode?:any
cPSPCode?:any
cProCode?:any
cDepCode?:any
cPersonCode?:any
cHandler?:any
iquantity?:any
iunitcost?:any
iprice?:any
cBatchCode?:any
cAccounter?:any
cMaker?:any
bFlag?:any
bMoneyFlag?:any
bSale?:any
iSQuantity?:any
iSMoney?:any
iSUnitcost?:any
dSDate?:any
cMemo?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cFree1?:any
cFree2?:any
cPZID?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cItem_class?:any
cItemCode?:any
cName?:any
cItemCName?:any
noJustQuantity?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
psvsid?:any
cCXHDcode?:any
cCXFScode?:any
cBatchia?:any
dMadeDateia?:any
iMassDateia?:any
cMassUnit?:any
dVDateia?:any
cproordercode?:any
iproorderid?:any
iproorderids?:any
cworkprocode?:any
cworkprocodedis?:any
cworkcentercode?:any
cworkcentername?:any
cendcode?:any
csaleordercode?:any
cIMOrdercode?:any
isaleorderid?:any
isaleordersid?:any
isaleorderids?:any
centrustordercode?:any
ientrustorderid?:any
ientrustordersid?:any
cpurordercode?:any
ipurordersid?:any
idlsid?:any
strContractCode?:any
inum?:any
cAssUnit?:any
exoCode?:any
iExRowno?:any
consignMentCode?:any
iconsignmentautoid?:any
imaterialfee?:any
iprocessfee?:any
cVerifier?:any
cvmivencode?:any
AutoID?:any
ibg_ctrl?:any
iTrans?:any
iLevel?:any
bEn?:any
bFX?:any
ufts?:any
bCosting?:any
dnOrderTime?:any
cdemandcode?:any
cdemandmemo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }