export default class t_IAJustVouchEntry {
      columnArr=['AutoID','ID','cJVCode','CorID','cCorCode','cInvCode','iJVPrice','cJVBatch','cObjCode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cItemCode','cItem_class','cName','cItemCName','iJustInsId','cBVencode','iMassDate','dMadeDate','cInVouchCode','bCosting','iMoseq','iOpseq','cOpdesc','cbAccounter','cmworkcentercode','cSRcVoutype','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37']
      AutoID?:any
ID?:any
cJVCode?:any
CorID?:any
cCorCode?:any
cInvCode?:any
iJVPrice?:any
cJVBatch?:any
cObjCode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cItemCode?:any
cItem_class?:any
cName?:any
cItemCName?:any
iJustInsId?:any
cBVencode?:any
iMassDate?:any
dMadeDate?:any
cInVouchCode?:any
bCosting?:any
iMoseq?:any
iOpseq?:any
cOpdesc?:any
cbAccounter?:any
cmworkcentercode?:any
cSRcVoutype?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }