export default class t_IAPSISumDetail {
      columnArr=['iInterID','cInvCode','cWhCode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','iQCQuantity','iQCPrice','iQCUnitPrice','iInQuantity','iInPrice','iInUnitPrice','iOutQuantity','iOutPrice','iOutUnitPrice','iEndQuantity','iEndPrice','iEndUnitPrice','iQCDif','iInDif','iOutDif','iEndDif','cUser']
      iInterID?:any
cInvCode?:any
cWhCode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
iQCQuantity?:any
iQCPrice?:any
iQCUnitPrice?:any
iInQuantity?:any
iInPrice?:any
iInUnitPrice?:any
iOutQuantity?:any
iOutPrice?:any
iOutUnitPrice?:any
iEndQuantity?:any
iEndPrice?:any
iEndUnitPrice?:any
iQCDif?:any
iInDif?:any
iOutDif?:any
iEndDif?:any
cUser?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }