export default class t_IASummary {
      columnArr=['AutoID','cWhCode','cInvCode','cDepCode','iYear','iMonth','iFNum','iINum','iONum','iNum','iFMoney','iIMoney','iOMoney','iMoney','iFUnitPrice','iUnitPrice','iDifRate','iIDif','iODif','iDif','fMinInCost','fMaxInCost','iDirect','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','bManual','iperiod','iTrans','fLaborStdCostE','fManuFixStdCostE','fManuVarStdCostE','fOmCostE','cInvName','cInvStd','cComUnitCode','cItemClsNo','cBatchIA','cWhKeeper','iFNumVolume','iINumVolume','iONumVolume','iNumVolume']
      AutoID?:any
cWhCode?:any
cInvCode?:any
cDepCode?:any
iYear?:any
iMonth?:any
iFNum?:any
iINum?:any
iONum?:any
iNum?:any
iFMoney?:any
iIMoney?:any
iOMoney?:any
iMoney?:any
iFUnitPrice?:any
iUnitPrice?:any
iDifRate?:any
iIDif?:any
iODif?:any
iDif?:any
fMinInCost?:any
fMaxInCost?:any
iDirect?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
bManual?:any
iperiod?:any
iTrans?:any
fLaborStdCostE?:any
fManuFixStdCostE?:any
fManuVarStdCostE?:any
fOmCostE?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any
cBatchIA?:any
cWhKeeper?:any
iFNumVolume?:any
iINumVolume?:any
iONumVolume?:any
iNumVolume?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }