export default class t_IAItemLog {
      columnArr=['dDate','dCheckDate','cCode','cWhCode','cWhName','cVouchType','cInvVouchTypeName','cBusType','cRdCode','cRdCodeName','cSource','cBusCode','iInQuantityCount','iInNumCount','iInCost','iInPrice','iOutQuantityCount','iOutNumCount','iOutCost','iOutPrice','iEndQuantityCount','iEndNumCount','iEndCost','iEndPrice','cInvCode','cUserCode','AutoID','cBatch','cStatus','cStatusName','iLineSumID','iYear']
      dDate?:any
dCheckDate?:any
cCode?:any
cWhCode?:any
cWhName?:any
cVouchType?:any
cInvVouchTypeName?:any
cBusType?:any
cRdCode?:any
cRdCodeName?:any
cSource?:any
cBusCode?:any
iInQuantityCount?:any
iInNumCount?:any
iInCost?:any
iInPrice?:any
iOutQuantityCount?:any
iOutNumCount?:any
iOutCost?:any
iOutPrice?:any
iEndQuantityCount?:any
iEndNumCount?:any
iEndCost?:any
iEndPrice?:any
cInvCode?:any
cUserCode?:any
AutoID?:any
cBatch?:any
cStatus?:any
cStatusName?:any
iLineSumID?:any
iYear?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }