export default class t_IASubsidiary {
      columnArr=['AutoID','hselect','bRdFlag','cBusType','cBusCode','cVouCode','ID','ValueID','JustID','dVouDate','dKeepDate','iPeriod','iYear','iMonth','iPZID','iPZDate','cPZtype','cPZdigest','cInvHead','cDifHead','cOppHead','cVouType','cPTCode','cSTCode','cWhCode','cAccDep','cInvCode','cRdCode','cVenCode','cCusCode','cOrderCode','cARVCode','cBillCode','cDLCode','cPSPCode','cProCode','cDepCode','cPersonCode','cHandler','iAInQuantity','iAOutQuantity','iInCost','iOutCost','iAInPrice','iAOutPrice','cBatchCode','iDebitDifCost','iCreditDifCost','cAccounter','cMaker','bFlag','bMoneyFlag','bSale','iSQuantity','iSMoney','iSUnitCost','dSDate','cMemo','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cFree1','cFree2','cPZID','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cItem_class','cItemCode','cName','cItemCName','noJustQuantity','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','psvsid','cCXHDcode','cCXFScode','cBatchia','dMadeDateia','iMassDateia','cMassUnit','dVDateia','cproordercode','iproorderid','iproorderids','cworkprocode','cworkprocodedis','cworkcentercode','cworkcentername','cendcode','csaleordercode','isaleorderid','isaleordersid','isaleorderids','centrustordercode','ientrustorderid','ientrustordersid','cpurordercode','ipurordersid','idlsid','strContractCode','inum','cAssUnit','exoCode','iExRowno','consignMentCode','iconsignmentautoid','iTrans','iLevel','BakID','iBG_Ctrl','cIMOrdercode','imaterialfee','iProcessFee','cMaterialHead','cProcessHead','cSRcVoutype','fLaborStdCostE','fManuFixStdCostE','fManuVarStdCostE','fOmCostE','cdemandcode','cdemandmemo','cInvName','cInvStd','cComUnitCode','cItemClsNo','cWhKeeper']
      AutoID?:any
hselect?:any
bRdFlag?:any
cBusType?:any
cBusCode?:any
cVouCode?:any
ID?:any
ValueID?:any
JustID?:any
dVouDate?:any
dKeepDate?:any
iPeriod?:any
iYear?:any
iMonth?:any
iPZID?:any
iPZDate?:any
cPZtype?:any
cPZdigest?:any
cInvHead?:any
cDifHead?:any
cOppHead?:any
cVouType?:any
cPTCode?:any
cSTCode?:any
cWhCode?:any
cAccDep?:any
cInvCode?:any
cRdCode?:any
cVenCode?:any
cCusCode?:any
cOrderCode?:any
cARVCode?:any
cBillCode?:any
cDLCode?:any
cPSPCode?:any
cProCode?:any
cDepCode?:any
cPersonCode?:any
cHandler?:any
iAInQuantity?:any
iAOutQuantity?:any
iInCost?:any
iOutCost?:any
iAInPrice?:any
iAOutPrice?:any
cBatchCode?:any
iDebitDifCost?:any
iCreditDifCost?:any
cAccounter?:any
cMaker?:any
bFlag?:any
bMoneyFlag?:any
bSale?:any
iSQuantity?:any
iSMoney?:any
iSUnitCost?:any
dSDate?:any
cMemo?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cFree1?:any
cFree2?:any
cPZID?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cItem_class?:any
cItemCode?:any
cName?:any
cItemCName?:any
noJustQuantity?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
psvsid?:any
cCXHDcode?:any
cCXFScode?:any
cBatchia?:any
dMadeDateia?:any
iMassDateia?:any
cMassUnit?:any
dVDateia?:any
cproordercode?:any
iproorderid?:any
iproorderids?:any
cworkprocode?:any
cworkprocodedis?:any
cworkcentercode?:any
cworkcentername?:any
cendcode?:any
csaleordercode?:any
isaleorderid?:any
isaleordersid?:any
isaleorderids?:any
centrustordercode?:any
ientrustorderid?:any
ientrustordersid?:any
cpurordercode?:any
ipurordersid?:any
idlsid?:any
strContractCode?:any
inum?:any
cAssUnit?:any
exoCode?:any
iExRowno?:any
consignMentCode?:any
iconsignmentautoid?:any
iTrans?:any
iLevel?:any
BakID?:any
iBG_Ctrl?:any
cIMOrdercode?:any
imaterialfee?:any
iProcessFee?:any
cMaterialHead?:any
cProcessHead?:any
cSRcVoutype?:any
fLaborStdCostE?:any
fManuFixStdCostE?:any
fManuVarStdCostE?:any
fOmCostE?:any
cdemandcode?:any
cdemandmemo?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any
cWhKeeper?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }