export default class t_InvTransProEntry {
      columnArr=['AutoID','ID','cCode','iItemID','cInvCode','iNum','iQuantity','iUnitCost','iPrice','iAPrice','iPUnitCost','iPPrice','cBatch','cObjCode','cVouchCode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','iFlag','dSDate','iTax','iSQuantity','iSNum','iMoney','iSOutQuantity','iSOutNum','iFNum','iFQuantity','dVDate','iTrIds','cPosition','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','iPOsID','fACost','iDLsID','iSBsID','iSendQuantity','iSendNum','iEnsID','cBarCode','iNQuantity','iNNum','cAssUnit','dMadeDate','iMassDate','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cBatchProperty1','cBatchProperty2','cBatchProperty3','cBatchProperty4','cBatchProperty5','cBatchProperty6','cBatchProperty7','cBatchProperty8','cBatchProperty9','cBatchProperty10','iMPoIds','iCheckIds','cBVencode','cInVouchCode','bGsp','cGspState','iArrsId','cCheckCode','iCheckIdBaks','cRejectCode','iRejectIds','cCheckPersonCode','dCheckDate','iOriTaxCost','iOriCost','iOriMoney','iOriTaxPrice','ioriSum','iTaxRate','iTaxPrice','iSum','bTaxCost','cPOID','cMassUnit','cMoLotCode','iMaterialFee','iProcessCost','iProcessFee','dMSDate','iSMaterialFee','iSProcessFee','iOMoDID','iorderdid','strContractId','strCode','bFilled','bChecked','bRelated','iOMoMID','cmworkcentercode','iMatSettleState','iBillSettleCount','iordertype','cVendorCode','bCosting','iSumBillQuantity','bVMIUsed','iVMISettleQuantity','iVMISettleNum','cvmivencode','iInvSNCount','cwhpersoncode','cwhpersonname','iMaIDs','impcost','cbarvcode','dbarvdate','iinvexchrate','cbdlcode','iordercode','iorderseq','comcode','cmocode','invcode','imoseq','iopseq','copdesc','productinids','isodid','isotype','csocode','isoseq','cNote','iSumBillNum','cbaccounter','cInvName','cInvStd','cComUnitCode','cItemClsNo','iScanQtyBack','iPurTaxPrice','iWorkReQty','iIqcReQty','cbCloseDate','cLineCloser','cMiNo','iPlanQty','iPlanedQty','cReqCode','iReqLineID','cSourType','cSourceCode','iSourceLineID','cDispNo','iDispLineID']
      AutoID?:any
ID?:any
cCode?:any
iItemID?:any
cInvCode?:any
iNum?:any
iQuantity?:any
iUnitCost?:any
iPrice?:any
iAPrice?:any
iPUnitCost?:any
iPPrice?:any
cBatch?:any
cObjCode?:any
cVouchCode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
iFlag?:any
dSDate?:any
iTax?:any
iSQuantity?:any
iSNum?:any
iMoney?:any
iSOutQuantity?:any
iSOutNum?:any
iFNum?:any
iFQuantity?:any
dVDate?:any
iTrIds?:any
cPosition?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
iPOsID?:any
fACost?:any
iDLsID?:any
iSBsID?:any
iSendQuantity?:any
iSendNum?:any
iEnsID?:any
cBarCode?:any
iNQuantity?:any
iNNum?:any
cAssUnit?:any
dMadeDate?:any
iMassDate?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cBatchProperty1?:any
cBatchProperty2?:any
cBatchProperty3?:any
cBatchProperty4?:any
cBatchProperty5?:any
cBatchProperty6?:any
cBatchProperty7?:any
cBatchProperty8?:any
cBatchProperty9?:any
cBatchProperty10?:any
iMPoIds?:any
iCheckIds?:any
cBVencode?:any
cInVouchCode?:any
bGsp?:any
cGspState?:any
iArrsId?:any
cCheckCode?:any
iCheckIdBaks?:any
cRejectCode?:any
iRejectIds?:any
cCheckPersonCode?:any
dCheckDate?:any
iOriTaxCost?:any
iOriCost?:any
iOriMoney?:any
iOriTaxPrice?:any
ioriSum?:any
iTaxRate?:any
iTaxPrice?:any
iSum?:any
bTaxCost?:any
cPOID?:any
cMassUnit?:any
cMoLotCode?:any
iMaterialFee?:any
iProcessCost?:any
iProcessFee?:any
dMSDate?:any
iSMaterialFee?:any
iSProcessFee?:any
iOMoDID?:any
iorderdid?:any
strContractId?:any
strCode?:any
bFilled?:any
bChecked?:any
bRelated?:any
iOMoMID?:any
cmworkcentercode?:any
iMatSettleState?:any
iBillSettleCount?:any
iordertype?:any
cVendorCode?:any
bCosting?:any
iSumBillQuantity?:any
bVMIUsed?:any
iVMISettleQuantity?:any
iVMISettleNum?:any
cvmivencode?:any
iInvSNCount?:any
cwhpersoncode?:any
cwhpersonname?:any
iMaIDs?:any
impcost?:any
cbarvcode?:any
dbarvdate?:any
iinvexchrate?:any
cbdlcode?:any
iordercode?:any
iorderseq?:any
comcode?:any
cmocode?:any
invcode?:any
imoseq?:any
iopseq?:any
copdesc?:any
productinids?:any
isodid?:any
isotype?:any
csocode?:any
isoseq?:any
cNote?:any
iSumBillNum?:any
cbaccounter?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any
iScanQtyBack?:any
iPurTaxPrice?:any
iWorkReQty?:any
iIqcReQty?:any
cbCloseDate?:any
cLineCloser?:any
cMiNo?:any
iPlanQty?:any
iPlanedQty?:any
cReqCode?:any
iReqLineID?:any
cSourType?:any
cSourceCode?:any
iSourceLineID?:any
cDispNo?:any
iDispLineID?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }