export default class t_InvTransEntryBatch {
      columnArr=['iAutoID','cCode','AutoID','bRdFlag','cWhCode','cInvCode','cDepCode','cBatchNo','dDate','iInQty','iInCost','iOutQty','iOutCost','iQty','iInMoney','iOutMoney','iMoney','iUnitPrice','iDirect','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cSourCode','SourAutoID','cNote','dOpedate','cVouchType']
      iAutoID?:any
cCode?:any
AutoID?:any
bRdFlag?:any
cWhCode?:any
cInvCode?:any
cDepCode?:any
cBatchNo?:any
dDate?:any
iInQty?:any
iInCost?:any
iOutQty?:any
iOutCost?:any
iQty?:any
iInMoney?:any
iOutMoney?:any
iMoney?:any
iUnitPrice?:any
iDirect?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cSourCode?:any
SourAutoID?:any
cNote?:any
dOpedate?:any
cVouchType?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }