export default class t_InvTransUpdate {
      columnArr=['AutoID','cBillType','cBillCode','iLineID','bProFlag','cWhCode','cPosition','cInvCode','cBatch','cVMIVenCode','iSoType','iSodid','iQuantity','iNum','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','fOutQuantity','fOutNum','fInQuantity','fInNum','fAvaQuantity','fAvaNum','dDate','dOpeDate','iID','cNote','cmworkcentercode','cVouchType','cBusType','cRdCode','cSource','cSourceCode','cSourceID','cSourceLineID','cSourceCode2','cSourceID2','cSourceLineID2','iPurNum']
      AutoID?:any
cBillType?:any
cBillCode?:any
iLineID?:any
bProFlag?:any
cWhCode?:any
cPosition?:any
cInvCode?:any
cBatch?:any
cVMIVenCode?:any
iSoType?:any
iSodid?:any
iQuantity?:any
iNum?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
fOutQuantity?:any
fOutNum?:any
fInQuantity?:any
fInNum?:any
fAvaQuantity?:any
fAvaNum?:any
dDate?:any
dOpeDate?:any
iID?:any
cNote?:any
cmworkcentercode?:any
cVouchType?:any
cBusType?:any
cRdCode?:any
cSource?:any
cSourceCode?:any
cSourceID?:any
cSourceLineID?:any
cSourceCode2?:any
cSourceID2?:any
cSourceLineID2?:any
iPurNum?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }