export default class t_InvTrans01 {
      columnArr=['ID','ID','bRdFlag','cCode','cCode','cVouchType','cBusType','cRdCode','cSource','cBusCode','cWhCode','dDate','cDepCode','cPersonCode','cWcNo','cPTCode','cSTCode','cCusCode','cVenCode','cOrderCode','cARVCode','cBillCode','cDLCode','cProBatch','cHandler','cOperator','dOpeDate','cChecker','dCheckDate','cStatus','cMemo','bTransFlag','cAccounter','cMaker','iNetLock','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','dKeepDate','dVeriDate','bpufirst','biafirst','iMQuantity','dARVDate','cChkCode','dChkDate','cChkPerson','bIsSTQc','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cPsPcode','cMPoCode','gspcheck','ipurorderid','ipurarriveid','iproorderid','iarriveid','isalebillid','iTaxRate','iExchRate','cExch_Name','cShipAddress','bOMFirst','bFromPreYear','bIsLsQuery','bIsComplement','iDiscountTaxType','iBG_OverFlag','cBG_Auditor','cBG_AuditTime','ControlResult','caddcode','ireturncount','iverifystate','iswfcontrolled','cModifyPerson','dModifyDate','dnmaketime','dnmodifytime','dnverifytime','bredvouch','bmotran','cVenPUOMProtocol','dCreditStart','iCreditPeriod','dGatheringDate','bCredit','iVT_ID','iAuditTypeID','qkts','iPrintCount','cResourceNo','iSourceID','bSysGen','cModifier','iNstructionsCode']
      ID?:any
ID?:any
bRdFlag?:any
cCode?:any
cCode?:any
cVouchType?:any
cBusType?:any
cRdCode?:any
cSource?:any
cBusCode?:any
cWhCode?:any
dDate?:any
cDepCode?:any
cPersonCode?:any
cWcNo?:any
cPTCode?:any
cSTCode?:any
cCusCode?:any
cVenCode?:any
cOrderCode?:any
cARVCode?:any
cBillCode?:any
cDLCode?:any
cProBatch?:any
cHandler?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cStatus?:any
cMemo?:any
bTransFlag?:any
cAccounter?:any
cMaker?:any
iNetLock?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
dKeepDate?:any
dVeriDate?:any
bpufirst?:any
biafirst?:any
iMQuantity?:any
dARVDate?:any
cChkCode?:any
dChkDate?:any
cChkPerson?:any
bIsSTQc?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cPsPcode?:any
cMPoCode?:any
gspcheck?:any
ipurorderid?:any
ipurarriveid?:any
iproorderid?:any
iarriveid?:any
isalebillid?:any
iTaxRate?:any
iExchRate?:any
cExch_Name?:any
cShipAddress?:any
bOMFirst?:any
bFromPreYear?:any
bIsLsQuery?:any
bIsComplement?:any
iDiscountTaxType?:any
iBG_OverFlag?:any
cBG_Auditor?:any
cBG_AuditTime?:any
ControlResult?:any
caddcode?:any
ireturncount?:any
iverifystate?:any
iswfcontrolled?:any
cModifyPerson?:any
dModifyDate?:any
dnmaketime?:any
dnmodifytime?:any
dnverifytime?:any
bredvouch?:any
bmotran?:any
cVenPUOMProtocol?:any
dCreditStart?:any
iCreditPeriod?:any
dGatheringDate?:any
bCredit?:any
iVT_ID?:any
iAuditTypeID?:any
qkts?:any
iPrintCount?:any
cResourceNo?:any
iSourceID?:any
bSysGen?:any
cModifier?:any
iNstructionsCode?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }