export default class t_InvTransVouchEntry {
      columnArr=['AutoId','iInterID','cTVCode','iItemID','cInvCode','iQuantity','iNum','iUnitCost','iPrice','iPUnitCost','iPPrice','cBatch','cOutPosCode','cInPosCode','cMoCode','iMoSeq','iMPoIds','cBarCode','cAssUnitCode','cItemCode','cItem_Class','cName','cItemCName','cVenCode','cInVouchCode','cOutVouchCode','dDate','iinvexchrate','cExpirationdate','dExpirationdate','iExpiratDateCalcu','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cDetailNote','cInBatch','cSourceNo','iSourceLineID','cInvName','cInvStd','cComUnitCode','cItemClsNo']
      AutoId?:any
iInterID?:any
cTVCode?:any
iItemID?:any
cInvCode?:any
iQuantity?:any
iNum?:any
iUnitCost?:any
iPrice?:any
iPUnitCost?:any
iPPrice?:any
cBatch?:any
cOutPosCode?:any
cInPosCode?:any
cMoCode?:any
iMoSeq?:any
iMPoIds?:any
cBarCode?:any
cAssUnitCode?:any
cItemCode?:any
cItem_Class?:any
cName?:any
cItemCName?:any
cVenCode?:any
cInVouchCode?:any
cOutVouchCode?:any
dDate?:any
iinvexchrate?:any
cExpirationdate?:any
dExpirationdate?:any
iExpiratDateCalcu?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cDetailNote?:any
cInBatch?:any
cSourceNo?:any
iSourceLineID?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }