export default class t_InvPurSdSumDetail {
      columnArr=['AutoID','cInvCode','cWhCode','cBatch','cPosition','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','iQCQuantity','iQCNum','iInQuantity','iInNum','iOutQuantity','iOutNum','iQMQuantity','iQMNum','cUser','cInvName','cInvStd','cComUnitCode','cItemClsNo']
      AutoID?:any
cInvCode?:any
cWhCode?:any
cBatch?:any
cPosition?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
iQCQuantity?:any
iQCNum?:any
iInQuantity?:any
iInNum?:any
iOutQuantity?:any
iOutNum?:any
iQMQuantity?:any
iQMNum?:any
cUser?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }