export default class t_InvTransVouch {
      columnArr=['iInterID','cTVCode','cVouchType','dDate','cOWhCode','cIWhCode','cODepCode','cIDepCode','cPersonCode','cStatus','cPSPCode','cMPoCode','iQuantity','bTransFlag','cOperator','dOpeDate','cChecker','dCheckDate','cModifier','dModifyDate','cNote','qkts','VT_ID','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','iproorderid','cOrderType','cTranReqCode','cVersion','iPrintCount']
      iInterID?:any
cTVCode?:any
cVouchType?:any
dDate?:any
cOWhCode?:any
cIWhCode?:any
cODepCode?:any
cIDepCode?:any
cPersonCode?:any
cStatus?:any
cPSPCode?:any
cMPoCode?:any
iQuantity?:any
bTransFlag?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cModifier?:any
dModifyDate?:any
cNote?:any
qkts?:any
VT_ID?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
iproorderid?:any
cOrderType?:any
cTranReqCode?:any
cVersion?:any
iPrintCount?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }