export default class t_Item1231 {
      columnArr=['iItemID','cInvCode','cInvName','cInvStd','cEnglishName','cItemClsNo','cVenCode','cReplaceItem','bSale','bPurchase','bSelf','bProxyForeign','bComsume','bService','bEquipment','bFixExch','iTaxRate','cDefWhNo','cPosition','bCommission','bModelCompleted','iGroupType','cGroupCode','cComUnitCode','cAssComUnitCode','cSAComUnitCode','cPUComUnitCode','cSTComUnitCode','cEnterprise','cAddress','cFile','cLabel','cCheckOut','cLicence','cLevel','cLinear','cWGroupCode','fGrossWeight','fNetWeight','cVGroupCode','fVolume','flength','fWidth','fHeight','cPackingType','fDiameter','fMinDiameter','fQtyPerBox','fPicQtyPer','fWeightPerM','iSafeStock','iTopLot','iLowLot','iIncLot','iAvgLot','cLeadTimeType','iAvgLeadTime','cValueType','iInvSCost','iInvSPrice','iInvNCost','iInvRCost','iInvHSCost','iInvLSCost','iExpSaleRate','bInvType','iInvMPCost','iInvSaleCost','iInvSCost1','iInvSCost2','iInvSCost3','cPriceGroup','cQuality','bBarCode','cBarCode','bSerial','cColor','cTemperature','cMaterial','bPropertyCheck','bPromotSales','iTestStyle','iDTMethod','fDTRate','fDTNum','cDTUnit','iDTStyle','iQTMethod','cPlanMethod','cInvDepCode','cInvPersonCode','cPurPersonCode','cSize1','cSize2','cSize3','cSize4','cSize5','cSize6','cSize7','cSize8','cSize9','cSize10','cSize11','cSize12','cSize13','cSize14','cSize15','cSize16','mItemPicture','mItemPicture2','cItemType','cProductType','qkts','iInterval','cUseStatus','iYieldage','iShrinkage','iPrecision','cBatchTrace','cWcNo','iProTime','iProMin','iProSec','cHorizonType','fMinSplit','iImpTaxRate','iExpTaxRate','bExpSale','bSrvItem','iTestRule','fOrderUpLimit','fOutExcess','fInExcess','cPrvNo','bInvQuality','iMassDate','iWarnDays','cCreatePerson','cModifyPerson','dModifyDate','dSDate','dEDate','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','bFree1','bFree2','bFree3','bFree4','bFree5','bFree6','bFree7','bFree8','bFree9','bFree10','bInvBatch','bCutMantissa','cInvABC','cDTAQL','iDTLevel','fExpensesExch','iOverStock','iTopSum','iLowSum','iAdvanceDate','bMps','bSet','bSchedule','cWorkRouteType','cBarCodeType','iROPMethod','iBatchRule','iRopOverPer','iAssureProvideDays','fSubscribePoint','fVagQuantity','iBarMaxID','cWhKeeper','cWhMan','bSmall','iBarCodeQty','cInjectItemType','cMoldNo','cSubMoldNo','cMoldPosition','iMoldSubQty','cModifyNote','iMadeRate','dLastMadeDate','iPriority','cRouteCode','cTechNo','cPlanMode','cInvCodeId','cRWhMan','fQuota','cKeyResourceNo','bReportItem','cReportWhNo','fSettleCost','cSettleAdress','fManuCost','iDensity','cMaterialType','cMatCode','iMatCost','iLabCost','iManuCost','iOtherCost','iLevelMatCost','iLevelLabCost','iLevelManuCost','iLevelOtherCost','bCost','cBomCode','bUsePriceType','cCustomNo','cCustomInNo','cLabelRemark','cSpeLabelRemark','cSpecialLabelItem','bUVolatile','cROHS','cSampleInvCode','bCustSupply','iXSQty','iJSQty','cCustProductNo','cCustProductName','cCustPrNo','iOutBeiLiang','cPicturePatch','cPicturePatch2','cSafeStockForla','cLowLotForla','cTopSumForla','iPackWaySmallQty','bPeiJian','cRouteTypeSelectExp','cProcessingType','cMiNoType','cAttributes1','cAttributes2','cAttributes3','cAttributes4','cAttributes5','cAttributes6','cAttributes7','cAttributes8','cAttributes9','cAttributes10','cAttributes11','cAttributes12','cAttributes13','cAttributes14','cAttributes15','cAttributes16','cPartPosition','cFileCode','cKnifeTypeSide','cKnifeTypeEnds','cKnifeTypeFace','cPackageNo','cSettleVenCode','cRootNo','iERPPartID','cModelNote','iMoldCount','cBoxBarCode','cChestBarCode','cBoxTemplate','cChestTemplate','cCCCLogo','cSchSNType','iItemDifficulty','iStockPeriod','iProductRate','cCriticalPath','iSafeStockDays','cPurType','iPutItemMaxRate','iPutItemMinRate','bItemPutCtr','iPackWayBigCtn','iPackWayBigQty','iPackWaySmallCtn','bMothly','iMaxOrderQty','iPlanEnlargeRage','cPurExcType']
      iItemID?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cEnglishName?:any
cItemClsNo?:any
cVenCode?:any
cReplaceItem?:any
bSale?:any
bPurchase?:any
bSelf?:any
bProxyForeign?:any
bComsume?:any
bService?:any
bEquipment?:any
bFixExch?:any
iTaxRate?:any
cDefWhNo?:any
cPosition?:any
bCommission?:any
bModelCompleted?:any
iGroupType?:any
cGroupCode?:any
cComUnitCode?:any
cAssComUnitCode?:any
cSAComUnitCode?:any
cPUComUnitCode?:any
cSTComUnitCode?:any
cEnterprise?:any
cAddress?:any
cFile?:any
cLabel?:any
cCheckOut?:any
cLicence?:any
cLevel?:any
cLinear?:any
cWGroupCode?:any
fGrossWeight?:any
fNetWeight?:any
cVGroupCode?:any
fVolume?:any
flength?:any
fWidth?:any
fHeight?:any
cPackingType?:any
fDiameter?:any
fMinDiameter?:any
fQtyPerBox?:any
fPicQtyPer?:any
fWeightPerM?:any
iSafeStock?:any
iTopLot?:any
iLowLot?:any
iIncLot?:any
iAvgLot?:any
cLeadTimeType?:any
iAvgLeadTime?:any
cValueType?:any
iInvSCost?:any
iInvSPrice?:any
iInvNCost?:any
iInvRCost?:any
iInvHSCost?:any
iInvLSCost?:any
iExpSaleRate?:any
bInvType?:any
iInvMPCost?:any
iInvSaleCost?:any
iInvSCost1?:any
iInvSCost2?:any
iInvSCost3?:any
cPriceGroup?:any
cQuality?:any
bBarCode?:any
cBarCode?:any
bSerial?:any
cColor?:any
cTemperature?:any
cMaterial?:any
bPropertyCheck?:any
bPromotSales?:any
iTestStyle?:any
iDTMethod?:any
fDTRate?:any
fDTNum?:any
cDTUnit?:any
iDTStyle?:any
iQTMethod?:any
cPlanMethod?:any
cInvDepCode?:any
cInvPersonCode?:any
cPurPersonCode?:any
cSize1?:any
cSize2?:any
cSize3?:any
cSize4?:any
cSize5?:any
cSize6?:any
cSize7?:any
cSize8?:any
cSize9?:any
cSize10?:any
cSize11?:any
cSize12?:any
cSize13?:any
cSize14?:any
cSize15?:any
cSize16?:any
mItemPicture?:any
mItemPicture2?:any
cItemType?:any
cProductType?:any
qkts?:any
iInterval?:any
cUseStatus?:any
iYieldage?:any
iShrinkage?:any
iPrecision?:any
cBatchTrace?:any
cWcNo?:any
iProTime?:any
iProMin?:any
iProSec?:any
cHorizonType?:any
fMinSplit?:any
iImpTaxRate?:any
iExpTaxRate?:any
bExpSale?:any
bSrvItem?:any
iTestRule?:any
fOrderUpLimit?:any
fOutExcess?:any
fInExcess?:any
cPrvNo?:any
bInvQuality?:any
iMassDate?:any
iWarnDays?:any
cCreatePerson?:any
cModifyPerson?:any
dModifyDate?:any
dSDate?:any
dEDate?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
bFree1?:any
bFree2?:any
bFree3?:any
bFree4?:any
bFree5?:any
bFree6?:any
bFree7?:any
bFree8?:any
bFree9?:any
bFree10?:any
bInvBatch?:any
bCutMantissa?:any
cInvABC?:any
cDTAQL?:any
iDTLevel?:any
fExpensesExch?:any
iOverStock?:any
iTopSum?:any
iLowSum?:any
iAdvanceDate?:any
bMps?:any
bSet?:any
bSchedule?:any
cWorkRouteType?:any
cBarCodeType?:any
iROPMethod?:any
iBatchRule?:any
iRopOverPer?:any
iAssureProvideDays?:any
fSubscribePoint?:any
fVagQuantity?:any
iBarMaxID?:any
cWhKeeper?:any
cWhMan?:any
bSmall?:any
iBarCodeQty?:any
cInjectItemType?:any
cMoldNo?:any
cSubMoldNo?:any
cMoldPosition?:any
iMoldSubQty?:any
cModifyNote?:any
iMadeRate?:any
dLastMadeDate?:any
iPriority?:any
cRouteCode?:any
cTechNo?:any
cPlanMode?:any
cInvCodeId?:any
cRWhMan?:any
fQuota?:any
cKeyResourceNo?:any
bReportItem?:any
cReportWhNo?:any
fSettleCost?:any
cSettleAdress?:any
fManuCost?:any
iDensity?:any
cMaterialType?:any
cMatCode?:any
iMatCost?:any
iLabCost?:any
iManuCost?:any
iOtherCost?:any
iLevelMatCost?:any
iLevelLabCost?:any
iLevelManuCost?:any
iLevelOtherCost?:any
bCost?:any
cBomCode?:any
bUsePriceType?:any
cCustomNo?:any
cCustomInNo?:any
cLabelRemark?:any
cSpeLabelRemark?:any
cSpecialLabelItem?:any
bUVolatile?:any
cROHS?:any
cSampleInvCode?:any
bCustSupply?:any
iXSQty?:any
iJSQty?:any
cCustProductNo?:any
cCustProductName?:any
cCustPrNo?:any
iOutBeiLiang?:any
cPicturePatch?:any
cPicturePatch2?:any
cSafeStockForla?:any
cLowLotForla?:any
cTopSumForla?:any
iPackWaySmallQty?:any
bPeiJian?:any
cRouteTypeSelectExp?:any
cProcessingType?:any
cMiNoType?:any
cAttributes1?:any
cAttributes2?:any
cAttributes3?:any
cAttributes4?:any
cAttributes5?:any
cAttributes6?:any
cAttributes7?:any
cAttributes8?:any
cAttributes9?:any
cAttributes10?:any
cAttributes11?:any
cAttributes12?:any
cAttributes13?:any
cAttributes14?:any
cAttributes15?:any
cAttributes16?:any
cPartPosition?:any
cFileCode?:any
cKnifeTypeSide?:any
cKnifeTypeEnds?:any
cKnifeTypeFace?:any
cPackageNo?:any
cSettleVenCode?:any
cRootNo?:any
iERPPartID?:any
cModelNote?:any
iMoldCount?:any
cBoxBarCode?:any
cChestBarCode?:any
cBoxTemplate?:any
cChestTemplate?:any
cCCCLogo?:any
cSchSNType?:any
iItemDifficulty?:any
iStockPeriod?:any
iProductRate?:any
cCriticalPath?:any
iSafeStockDays?:any
cPurType?:any
iPutItemMaxRate?:any
iPutItemMinRate?:any
bItemPutCtr?:any
iPackWayBigCtn?:any
iPackWayBigQty?:any
iPackWaySmallCtn?:any
bMothly?:any
iMaxOrderQty?:any
iPlanEnlargeRage?:any
cPurExcType?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }