export default class t_ItemTypeSelectExp {
      columnArr=['iInterID','cInvCode','cTechNo','cRouteTypeSelectExp','iDiffCoe','cNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','iMiNoQtyMax','cMiNoType','iMiNoQtyPer','cMiNoUnit','cGroupBySQL','cOrderBySQL','iSchSN','iRangeWidthA','iRangeWidthB','iRangeLengthA','iRangeLengthB','iRangeQtyA','iRangeQtyB','cRouteNo','cDefRoute','cRouteNoRep','cRouteNoRepExp']
      iInterID?:any
cInvCode?:any
cTechNo?:any
cRouteTypeSelectExp?:any
iDiffCoe?:any
cNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
iMiNoQtyMax?:any
cMiNoType?:any
iMiNoQtyPer?:any
cMiNoUnit?:any
cGroupBySQL?:any
cOrderBySQL?:any
iSchSN?:any
iRangeWidthA?:any
iRangeWidthB?:any
iRangeLengthA?:any
iRangeLengthB?:any
iRangeQtyA?:any
iRangeQtyB?:any
cRouteNo?:any
cDefRoute?:any
cRouteNoRep?:any
cRouteNoRepExp?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }