export default class t_MESQcCheckEntry {
      columnArr=['iInterID','iLineID','cCheckItem_ID','cResult_ID','cCode','cData_1','cData_2','cData_3','cData_4','cData_5','cRemark','cdNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cDefine38']
      iInterID?:any
iLineID?:any
cCheckItem_ID?:any
cResult_ID?:any
cCode?:any
cData_1?:any
cData_2?:any
cData_3?:any
cData_4?:any
cData_5?:any
cRemark?:any
cdNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cDefine38?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }