export default class t_MESQcCheck {
      columnArr=['iInterID','cCode','cOperator','dOpeDate','cChecker','dCheckDate','Record_ID','cWoNo','cInvCode','cInvName','iProcessID','iWoSeqID','cSite_ID','cPersonCode','cCheckType','IC_Number','cBarCode','iQuantity','iNum','cQcPerson','Qc_Report','IsPass','Result_Code','cDescribe','cRemark','cCustNo','GUID','cWeight','cBadMemo','cHandle','cNote','cResourceNo','cResourceName','cStatus','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16']
      iInterID?:any
cCode?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
Record_ID?:any
cWoNo?:any
cInvCode?:any
cInvName?:any
iProcessID?:any
iWoSeqID?:any
cSite_ID?:any
cPersonCode?:any
cCheckType?:any
IC_Number?:any
cBarCode?:any
iQuantity?:any
iNum?:any
cQcPerson?:any
Qc_Report?:any
IsPass?:any
Result_Code?:any
cDescribe?:any
cRemark?:any
cCustNo?:any
GUID?:any
cWeight?:any
cBadMemo?:any
cHandle?:any
cNote?:any
cResourceNo?:any
cResourceName?:any
cStatus?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }