export default class t_MrpSdOrderInvTrace {
      columnArr=['iGrossID','cVersionNo','cSourType','cBillNo','iLineID','cParentNo','iParentQty','cMiNo','cProductNo','cSdOrderNo','iSdLineID','dDeliveryDate','iProductQty','dDate','cPriorityType','cCustNo','cCustName','cInvType','cInvCode','iLowCode','iInvQty','iReqQty','iForeInQty','iEndQty','dReqDate','dBegDate','cWhNo','cNote','cExchangeNo','cSubMiNo','cMoldNo','cBatchNo','cSchStatus','cSchStatusDate','cSchStatusNote','cVendor','cVenName','cWcNo','cResourceNo','cPersonCode','cEnough','cCalType','cReType','cReCode','iRelineID','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cProductWo','cHostname','dOpeDate','iProQty','iPlanQty','dActEndDate','dActBegDate']
      iGrossID?:any
cVersionNo?:any
cSourType?:any
cBillNo?:any
iLineID?:any
cParentNo?:any
iParentQty?:any
cMiNo?:any
cProductNo?:any
cSdOrderNo?:any
iSdLineID?:any
dDeliveryDate?:any
iProductQty?:any
dDate?:any
cPriorityType?:any
cCustNo?:any
cCustName?:any
cInvType?:any
cInvCode?:any
iLowCode?:any
iInvQty?:any
iReqQty?:any
iForeInQty?:any
iEndQty?:any
dReqDate?:any
dBegDate?:any
cWhNo?:any
cNote?:any
cExchangeNo?:any
cSubMiNo?:any
cMoldNo?:any
cBatchNo?:any
cSchStatus?:any
cSchStatusDate?:any
cSchStatusNote?:any
cVendor?:any
cVenName?:any
cWcNo?:any
cResourceNo?:any
cPersonCode?:any
cEnough?:any
cCalType?:any
cReType?:any
cReCode?:any
iRelineID?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cProductWo?:any
cHostname?:any
dOpeDate?:any
iProQty?:any
iPlanQty?:any
dActEndDate?:any
dActBegDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }