export default class t_MrpForeInERP {
      columnArr=['iAutoID','cVersionNo','cBillType','cCode','iLineID','cInvCode','iQuantity','iNum','iInvQty','iInvNum','iForeInQty','iDispatchQty','dArriveDate','cSdType','cSdOrderNo','iSdLineID','cMiNo','cProductNo','cParentNo','iBomLevel','cSourType','cCalType','cHostname','dOpeDate']
      iAutoID?:any
cVersionNo?:any
cBillType?:any
cCode?:any
iLineID?:any
cInvCode?:any
iQuantity?:any
iNum?:any
iInvQty?:any
iInvNum?:any
iForeInQty?:any
iDispatchQty?:any
dArriveDate?:any
cSdType?:any
cSdOrderNo?:any
iSdLineID?:any
cMiNo?:any
cProductNo?:any
cParentNo?:any
iBomLevel?:any
cSourType?:any
cCalType?:any
cHostname?:any
dOpeDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }