export default class t_OMMOOrder {
      columnArr=['iMOID','cMoCode','dDate','cVenCode','cDepCode','cPersonCode','cPTCode','cArrivalPlace','cSCCode','cexch_name','nflat','iTaxRate','cPayCode','iCost','iBargain','cNote','cChanger','cBusType','iReturnCount','iVerifyStateNew','IsWfControlled','cStatus','cOperator','dOpeDate','cChecker','dCheckDate','cVenPUOMProtocol','iVT_ID','iAuditTypeID','qkts','cCloser','dCloseDate','iPrintCount','cModifier','dModifyDate','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cHTH','cPrNo','cPONo','cProductNo','iDiscountTaxType','cCHKNote','dCHKDate','cDefine24','dVDate','Material']
      iMOID?:any
cMoCode?:any
dDate?:any
cVenCode?:any
cDepCode?:any
cPersonCode?:any
cPTCode?:any
cArrivalPlace?:any
cSCCode?:any
cexch_name?:any
nflat?:any
iTaxRate?:any
cPayCode?:any
iCost?:any
iBargain?:any
cNote?:any
cChanger?:any
cBusType?:any
iReturnCount?:any
iVerifyStateNew?:any
IsWfControlled?:any
cStatus?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cVenPUOMProtocol?:any
iVT_ID?:any
iAuditTypeID?:any
qkts?:any
cCloser?:any
dCloseDate?:any
iPrintCount?:any
cModifier?:any
dModifyDate?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cHTH?:any
cPrNo?:any
cPONo?:any
cProductNo?:any
iDiscountTaxType?:any
cCHKNote?:any
dCHKDate?:any
cDefine24?:any
dVDate?:any
Material?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }