export default class t_OMArrivalEntry {
      columnArr=['iOMLineID','iInterID','cCode','dLineclosedate','cLineCloser','cWhCode','cciqcode','iInvMPCost','cSdorderCode','cOrdertype','iOrderID','fDTQuantity','fInspectQuantity','fDegradeInQuantity','fSumRefuseQuantity','fInspectNum','fRetNum','cInvCode','cItemClsNo','cInvStd','iQuantity','iNum','iUnitPrice','iTaxUnitPrice','iMoney','iTax','iSum','iQuotedPrice','iNatUnitPrice','iNatTaxPrice','iTaxPrice','iNatMoney','iNatTax','iNatSum','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','iTaxRate','iInvExchRate','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cItemCode','cItemName','cComUnitCode','fValidInQuan','fKPQuantity','fRealQuantity','fValidQuantity','finValidQuantity','fRetQuantity','fInValidInQuan','bGsp','cBatch','fRefuseQuantity','cGspState','fValidNum','fValidInNum','fInValidNum','fRealNum','fRefuseNum','iPQuantity','imassdate','iPTOSeq','iPPartId','cSource','soDId','soType','cupsocode','iorderseq','cDNote','dArriveDate','cPurUnitID','iPurExchRate','iPurNum','fValidInPurNum','fRetPurNum']
      iOMLineID?:any
iInterID?:any
cCode?:any
dLineclosedate?:any
cLineCloser?:any
cWhCode?:any
cciqcode?:any
iInvMPCost?:any
cSdorderCode?:any
cOrdertype?:any
iOrderID?:any
fDTQuantity?:any
fInspectQuantity?:any
fDegradeInQuantity?:any
fSumRefuseQuantity?:any
fInspectNum?:any
fRetNum?:any
cInvCode?:any
cItemClsNo?:any
cInvStd?:any
iQuantity?:any
iNum?:any
iUnitPrice?:any
iTaxUnitPrice?:any
iMoney?:any
iTax?:any
iSum?:any
iQuotedPrice?:any
iNatUnitPrice?:any
iNatTaxPrice?:any
iTaxPrice?:any
iNatMoney?:any
iNatTax?:any
iNatSum?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
iTaxRate?:any
iInvExchRate?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cItemCode?:any
cItemName?:any
cComUnitCode?:any
fValidInQuan?:any
fKPQuantity?:any
fRealQuantity?:any
fValidQuantity?:any
finValidQuantity?:any
fRetQuantity?:any
fInValidInQuan?:any
bGsp?:any
cBatch?:any
fRefuseQuantity?:any
cGspState?:any
fValidNum?:any
fValidInNum?:any
fInValidNum?:any
fRealNum?:any
fRefuseNum?:any
iPQuantity?:any
imassdate?:any
iPTOSeq?:any
iPPartId?:any
cSource?:any
soDId?:any
soType?:any
cupsocode?:any
iorderseq?:any
cDNote?:any
dArriveDate?:any
cPurUnitID?:any
iPurExchRate?:any
iPurNum?:any
fValidInPurNum?:any
fRetPurNum?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }