export default class t_OMMOMaterials {
      columnArr=['iMOMaterialsID','iMOMaterialID','cMOMaterialCode','iMOLineID','iMOID','cMoCode','cInvCode','cInvName','iSubItemID','cSubInvCode','cSubInvName','cComUnitCode','cItemClsNo','cInvStd','iSeqID','cUtterType','cSubRelate','iParentQty','iSubQty','iQtyPer','iScrapt','iNormalQty','iRetPercent','iReqQty','iReqNum','dReqDate','iProQty','iProNum','iScrapQty','iNormalScrapQty','iKeepQty','iPlanQty','cWhNo','cPacNo','iRetOffsetLt','cMNote','cGetItemType','iScraptOut','cScraptExp','cPrintColor','bSelf','bDaBan','cTypeSetting','cProductSolidSize','cProductPlaneSize','iOpenQty','iBanQty','iMolecularQty','iDenominatorQty','iSubBZQty','cResourceNo','cBatch','iInvExchRate','cUnitID','iSdLineID','cSdOrderNo','cMiNo','cProductNo','cWhCode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cBatchProperty1','cBatchProperty2','cBatchProperty3','cBatchProperty4','cBatchProperty5','cBatchProperty6','cBatchProperty7','cBatchProperty8','cBatchProperty9','cBatchProperty10','cLineCloser','iPlanedQty','cSourType','cSourceCode','iSourceLineID','cReqCode','iReqLineID']
      iMOMaterialsID?:any
iMOMaterialID?:any
cMOMaterialCode?:any
iMOLineID?:any
iMOID?:any
cMoCode?:any
cInvCode?:any
cInvName?:any
iSubItemID?:any
cSubInvCode?:any
cSubInvName?:any
cComUnitCode?:any
cItemClsNo?:any
cInvStd?:any
iSeqID?:any
cUtterType?:any
cSubRelate?:any
iParentQty?:any
iSubQty?:any
iQtyPer?:any
iScrapt?:any
iNormalQty?:any
iRetPercent?:any
iReqQty?:any
iReqNum?:any
dReqDate?:any
iProQty?:any
iProNum?:any
iScrapQty?:any
iNormalScrapQty?:any
iKeepQty?:any
iPlanQty?:any
cWhNo?:any
cPacNo?:any
iRetOffsetLt?:any
cMNote?:any
cGetItemType?:any
iScraptOut?:any
cScraptExp?:any
cPrintColor?:any
bSelf?:any
bDaBan?:any
cTypeSetting?:any
cProductSolidSize?:any
cProductPlaneSize?:any
iOpenQty?:any
iBanQty?:any
iMolecularQty?:any
iDenominatorQty?:any
iSubBZQty?:any
cResourceNo?:any
cBatch?:any
iInvExchRate?:any
cUnitID?:any
iSdLineID?:any
cSdOrderNo?:any
cMiNo?:any
cProductNo?:any
cWhCode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cBatchProperty1?:any
cBatchProperty2?:any
cBatchProperty3?:any
cBatchProperty4?:any
cBatchProperty5?:any
cBatchProperty6?:any
cBatchProperty7?:any
cBatchProperty8?:any
cBatchProperty9?:any
cBatchProperty10?:any
cLineCloser?:any
iPlanedQty?:any
cSourType?:any
cSourceCode?:any
iSourceLineID?:any
cReqCode?:any
iReqLineID?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }