export default class t_OMMOEntry {
      columnArr=['iMOLineID','iMOID','cMoCode','cItemClsNo','cInvCode','cInvName','iQuantity','iNum','iQuotedPrice','iUnitPrice','iTaxUnitPrice','iTaxRate','iMoney','iTax','iSum','iDisCount','KL','KL2','iNatUnitPrice','iNatTaxPrice','iNatMoney','iNatTax','iNatSum','iNatDisCount','iOriTotal','iTotal','dStartDate','dArriveDate','iReceivedQTY','iReceivedNum','iReceivedMoney','iInvQTY','iInvNum','iInvMoney','iInvExchRate','cUnitID','iflag','cItemCode','cItem_class','cItemName','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','bGsp','iTaxPrice','iArrQTY','iArrNum','iArrMoney','iNatArrMoney','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','bTaxCost','cSource','cbCloser','SOType','iSODID','iBomID','iMrpdetailsID','fParentScrp','iMaterialSendQty','Tbaseqtyd','dUfts','iVTids','cupsocode','cupsoids','isosid','cdemandcode','cdetailsdemandmemo','dcCloseDate','dcCloseTime','cLineCloser','cVenCode','cDNote','cDetailPrNo','cPurUnitID','iPurExchRate','iPurNum','iArrPurNum','iReceivedPurNum','iInvPurNum','cSdOrderNo','iSdLineID','cMiNo','cProductNo','cPriorityType','cSchStatus','dBegDate','dEndDate','dAgreeDate','cSchStatusDate','cSchStatusNote','cSourType','cSourceCode','iSourceLineID']
      iMOLineID?:any
iMOID?:any
cMoCode?:any
cItemClsNo?:any
cInvCode?:any
cInvName?:any
iQuantity?:any
iNum?:any
iQuotedPrice?:any
iUnitPrice?:any
iTaxUnitPrice?:any
iTaxRate?:any
iMoney?:any
iTax?:any
iSum?:any
iDisCount?:any
KL?:any
KL2?:any
iNatUnitPrice?:any
iNatTaxPrice?:any
iNatMoney?:any
iNatTax?:any
iNatSum?:any
iNatDisCount?:any
iOriTotal?:any
iTotal?:any
dStartDate?:any
dArriveDate?:any
iReceivedQTY?:any
iReceivedNum?:any
iReceivedMoney?:any
iInvQTY?:any
iInvNum?:any
iInvMoney?:any
iInvExchRate?:any
cUnitID?:any
iflag?:any
cItemCode?:any
cItem_class?:any
cItemName?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
bGsp?:any
iTaxPrice?:any
iArrQTY?:any
iArrNum?:any
iArrMoney?:any
iNatArrMoney?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
bTaxCost?:any
cSource?:any
cbCloser?:any
SOType?:any
iSODID?:any
iBomID?:any
iMrpdetailsID?:any
fParentScrp?:any
iMaterialSendQty?:any
Tbaseqtyd?:any
dUfts?:any
iVTids?:any
cupsocode?:any
cupsoids?:any
isosid?:any
cdemandcode?:any
cdetailsdemandmemo?:any
dcCloseDate?:any
dcCloseTime?:any
cLineCloser?:any
cVenCode?:any
cDNote?:any
cDetailPrNo?:any
cPurUnitID?:any
iPurExchRate?:any
iPurNum?:any
iArrPurNum?:any
iReceivedPurNum?:any
iInvPurNum?:any
cSdOrderNo?:any
iSdLineID?:any
cMiNo?:any
cProductNo?:any
cPriorityType?:any
cSchStatus?:any
dBegDate?:any
dEndDate?:any
dAgreeDate?:any
cSchStatusDate?:any
cSchStatusNote?:any
cSourType?:any
cSourceCode?:any
iSourceLineID?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }