export default class t_PriceJustify {
      columnArr=['ID','dDate','cInvCode','iOPrice','iPrice','cMemo','cMaker','iOInvCost1','iNInvCost1','iOInvCost2','iNInvCost2','iOInvCost3','iNInvCost3','iOInvSaleCost','iNInvSaleCost','cCusCCode','cCusCode','cFree1','cFree2','IOSalePrice1','INSalePrice1','IOSalePrice2','INSalePrice2','IOSalePrice3','INSalePrice3','IOInvCost4','iNInvCost4','IOSalePrice4','INSalePrice4','IOInvCost5','iNInvCost5','IOSalePrice5','INSalePrice5','IOInvCost6','iNInvCost6','IOSalePrice6','INSalePrice6','IOInvCost7','iNInvCost7','IOSalePrice7','INSalePrice7','IOInvCost8','iNInvCost8','IOSalePrice8','INSalePrice8','IOInvCost9','iNInvCost9','IOSalePrice9','INSalePrice9','IOInvCost10','iNInvCost10','IOSalePrice10','INSalePrice10','iinvjustautoid','icusjustautoid','iinvpriceautoid','icuspriceautoid','bInValid','ioinvjustautoid','iocusjustautoid','fminquantity','fcusminprice','bsales','cexch_name','cdepcode','cpersoncode','dstartdate','denddate','cdefine22','cdefine23','cdefine24','cdefine25','cdefine26','cdefine27','cdefine28','cdefine29','cdefine30','cdefine31','cdefine32','cdefine33','cdefine34','cdefine35','cdefine36','cdefine37','cCusInvCode','cCusInvName','cfree3','cfree4','cfree5','cfree6','cfree7','cfree8','cfree9','cfree10']
      ID?:any
dDate?:any
cInvCode?:any
iOPrice?:any
iPrice?:any
cMemo?:any
cMaker?:any
iOInvCost1?:any
iNInvCost1?:any
iOInvCost2?:any
iNInvCost2?:any
iOInvCost3?:any
iNInvCost3?:any
iOInvSaleCost?:any
iNInvSaleCost?:any
cCusCCode?:any
cCusCode?:any
cFree1?:any
cFree2?:any
IOSalePrice1?:any
INSalePrice1?:any
IOSalePrice2?:any
INSalePrice2?:any
IOSalePrice3?:any
INSalePrice3?:any
IOInvCost4?:any
iNInvCost4?:any
IOSalePrice4?:any
INSalePrice4?:any
IOInvCost5?:any
iNInvCost5?:any
IOSalePrice5?:any
INSalePrice5?:any
IOInvCost6?:any
iNInvCost6?:any
IOSalePrice6?:any
INSalePrice6?:any
IOInvCost7?:any
iNInvCost7?:any
IOSalePrice7?:any
INSalePrice7?:any
IOInvCost8?:any
iNInvCost8?:any
IOSalePrice8?:any
INSalePrice8?:any
IOInvCost9?:any
iNInvCost9?:any
IOSalePrice9?:any
INSalePrice9?:any
IOInvCost10?:any
iNInvCost10?:any
IOSalePrice10?:any
INSalePrice10?:any
iinvjustautoid?:any
icusjustautoid?:any
iinvpriceautoid?:any
icuspriceautoid?:any
bInValid?:any
ioinvjustautoid?:any
iocusjustautoid?:any
fminquantity?:any
fcusminprice?:any
bsales?:any
cexch_name?:any
cdepcode?:any
cpersoncode?:any
dstartdate?:any
denddate?:any
cdefine22?:any
cdefine23?:any
cdefine24?:any
cdefine25?:any
cdefine26?:any
cdefine27?:any
cdefine28?:any
cdefine29?:any
cdefine30?:any
cdefine31?:any
cdefine32?:any
cdefine33?:any
cdefine34?:any
cdefine35?:any
cdefine36?:any
cdefine37?:any
cCusInvCode?:any
cCusInvName?:any
cfree3?:any
cfree4?:any
cfree5?:any
cfree6?:any
cfree7?:any
cfree8?:any
cfree9?:any
cfree10?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }