export default class t_PubTableDic {
      columnArr=['AutoID','cSysNo','cTableName','cTableDesc','cUftableName','iColOrder','cColName','cColTitle','cDescription','iDatatype','iLength','iScale','bIsPK','bIsIdentity','bAllowNulls','bflag','cDefaultValue','bVisible','bMustInput','cDataSourceType','cDataSource','cDataList','cNote','dOperator','dOpeDate','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16']
      AutoID?:any
cSysNo?:any
cTableName?:any
cTableDesc?:any
cUftableName?:any
iColOrder?:any
cColName?:any
cColTitle?:any
cDescription?:any
iDatatype?:any
iLength?:any
iScale?:any
bIsPK?:any
bIsIdentity?:any
bAllowNulls?:any
bflag?:any
cDefaultValue?:any
bVisible?:any
bMustInput?:any
cDataSourceType?:any
cDataSource?:any
cDataList?:any
cNote?:any
dOperator?:any
dOpeDate?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }