export default class t_PubTask {
      columnArr=['iTaskID','cTaskNo','cTaskName','cDLLName','cFunction','cParams','bAvailable','dDate','cTimerType','cDateValue','iYear','iMonth','iDay','iHour','iMinute','iSecond','dLastRunDate','dBegDate','iRunTime','cResult','cError','cOperator','dOpeDate','cChecker','dCheckDate','cStatus','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','iVTID','iAuditTypeID','cNote']
      iTaskID?:any
cTaskNo?:any
cTaskName?:any
cDLLName?:any
cFunction?:any
cParams?:any
bAvailable?:any
dDate?:any
cTimerType?:any
cDateValue?:any
iYear?:any
iMonth?:any
iDay?:any
iHour?:any
iMinute?:any
iSecond?:any
dLastRunDate?:any
dBegDate?:any
iRunTime?:any
cResult?:any
cError?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cStatus?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
iVTID?:any
iAuditTypeID?:any
cNote?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }