export default class t_PurPlanEntry {
      columnArr=['iReqID','cReqCode','iReqLineID','cVenCode','cInvCode','iQuantity','iUnitPrice','iTaxRate','iTaxUnitPrice','iMoney','iTax','iSum','dRequirDate','dArriveDate','iReceivedQTY','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','bTaxCost','iPPartId','cParentInvCode','iPQuantity','iPTOSeq','cSource','SoDId','SoType','cSdType','iSdLineID','cSdOrderNo','cMiNo','cProductNo','iMrpsid','iRopsid','cbcloser','iNum','cUnitID','iInvExchRate','iReceivedNum','cPersonCodeExec','cDepCodeExec','iInvMPCost','cexch_name','iExchRate','iOriCost','iOriTaxCost','iOriMoney','iOriTax','iOriSum','cdemandcode','cdetailsdemandmemo','dqkts','cDNote','cLineCloser','cPutSelect','cPurPersonCode','cPOCode','iPOLineID','cbCloseDate']
      iReqID?:any
cReqCode?:any
iReqLineID?:any
cVenCode?:any
cInvCode?:any
iQuantity?:any
iUnitPrice?:any
iTaxRate?:any
iTaxUnitPrice?:any
iMoney?:any
iTax?:any
iSum?:any
dRequirDate?:any
dArriveDate?:any
iReceivedQTY?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
bTaxCost?:any
iPPartId?:any
cParentInvCode?:any
iPQuantity?:any
iPTOSeq?:any
cSource?:any
SoDId?:any
SoType?:any
cSdType?:any
iSdLineID?:any
cSdOrderNo?:any
cMiNo?:any
cProductNo?:any
iMrpsid?:any
iRopsid?:any
cbcloser?:any
iNum?:any
cUnitID?:any
iInvExchRate?:any
iReceivedNum?:any
cPersonCodeExec?:any
cDepCodeExec?:any
iInvMPCost?:any
cexch_name?:any
iExchRate?:any
iOriCost?:any
iOriTaxCost?:any
iOriMoney?:any
iOriTax?:any
iOriSum?:any
cdemandcode?:any
cdetailsdemandmemo?:any
dqkts?:any
cDNote?:any
cLineCloser?:any
cPutSelect?:any
cPurPersonCode?:any
cPOCode?:any
iPOLineID?:any
cbCloseDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }