export default class t_PurchaseBidding {
      columnArr=['iInterID','cCode','cItemCode','cItemName','cProductType','cInvCode','cInvName','dBiddingBegin','dBiddingEnd','cQuote','iQuoteInterval','dConditionPrice','cOutline','cDetail','dDate','cOperator','dOpeDate','cChecker','dCheckDate','cStatus','bPublish','cNote','cCloser','dCloseDate','cModifier','dModifyDate','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cCusName','cSize','cMobFactory','cMobType','cMPPlanTime','cPlanOrderQuantity','cMaterial','cAppearance','cQtys','dPriceLevel','dMaxPrice','cPurBidType','cEndTimeFlag','showMinimunPrice']
      iInterID?:any
cCode?:any
cItemCode?:any
cItemName?:any
cProductType?:any
cInvCode?:any
cInvName?:any
dBiddingBegin?:any
dBiddingEnd?:any
cQuote?:any
iQuoteInterval?:any
dConditionPrice?:any
cOutline?:any
cDetail?:any
dDate?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cStatus?:any
bPublish?:any
cNote?:any
cCloser?:any
dCloseDate?:any
cModifier?:any
dModifyDate?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cCusName?:any
cSize?:any
cMobFactory?:any
cMobType?:any
cMPPlanTime?:any
cPlanOrderQuantity?:any
cMaterial?:any
cAppearance?:any
cQtys?:any
dPriceLevel?:any
dMaxPrice?:any
cPurBidType?:any
cEndTimeFlag?:any
showMinimunPrice?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }