export default class t_PubSysMenu {
      columnArr=['cMenu_ID','iMenuKind','iFuncType','cMenu_Name','cMenu_Eng','cButtonName','cSub_ID','iGrade','cSupMenu_ID','bEndGrade','cWinName','cWinFullName','cWinAlias','cParentWin','iOpenType','cOpenArg','iOrder','bIsVisible','cFileName','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','dOpeDate']
      cMenu_ID?:any
iMenuKind?:any
iFuncType?:any
cMenu_Name?:any
cMenu_Eng?:any
cButtonName?:any
cSub_ID?:any
iGrade?:any
cSupMenu_ID?:any
bEndGrade?:any
cWinName?:any
cWinFullName?:any
cWinAlias?:any
cParentWin?:any
iOpenType?:any
cOpenArg?:any
iOrder?:any
bIsVisible?:any
cFileName?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
dOpeDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }