export default class t_PubSeePlateAttr {
      columnArr=['iInterID','cCode','iEntryID','cZiDuan','cBiaoQian','cDetailNote','cWeiZhi','iXSDWeiShu','cDuiQi','cDataType','cDefaultValue','cModelType','iModelSize','cEditable','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','iOrder','iFont','bBold','cIsShow','iHeight','iWidth','cColor']
      iInterID?:any
cCode?:any
iEntryID?:any
cZiDuan?:any
cBiaoQian?:any
cDetailNote?:any
cWeiZhi?:any
iXSDWeiShu?:any
cDuiQi?:any
cDataType?:any
cDefaultValue?:any
cModelType?:any
iModelSize?:any
cEditable?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
iOrder?:any
iFont?:any
bBold?:any
cIsShow?:any
iHeight?:any
iWidth?:any
cColor?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }