export default class t_PurRequire {
      columnArr=['iInterID','cPRNo','cPurType','cDeptNo','cDemander','dDate','cSdOrderNo','cMiNo','cProductNo','cStatus','iAuditID','dOperator','dOpeDate','cChecker','dCheckDate','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16']
      iInterID?:any
cPRNo?:any
cPurType?:any
cDeptNo?:any
cDemander?:any
dDate?:any
cSdOrderNo?:any
cMiNo?:any
cProductNo?:any
cStatus?:any
iAuditID?:any
dOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }