export default class t_PubSeePlateGraphAttr {
      columnArr=['iInterID','cCode','iEntryID','iPosition','cTitle','cDataX','cDataXTitle','cDataY1','cDataY1Title','cDataY1Type','cDataY1Color','cDataY2','cDataY2Title','cDataY2Type','cDataY2Color','cZiDuan','cBiaoQian','cDetailNote','cWeiZhi','iXSDWeiShu','cDuiQi','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','iOrder','iFont','bBold','cIsShow','iHeight','iWidth','cColor']
      iInterID?:any
cCode?:any
iEntryID?:any
iPosition?:any
cTitle?:any
cDataX?:any
cDataXTitle?:any
cDataY1?:any
cDataY1Title?:any
cDataY1Type?:any
cDataY1Color?:any
cDataY2?:any
cDataY2Title?:any
cDataY2Type?:any
cDataY2Color?:any
cZiDuan?:any
cBiaoQian?:any
cDetailNote?:any
cWeiZhi?:any
iXSDWeiShu?:any
cDuiQi?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
iOrder?:any
iFont?:any
bBold?:any
cIsShow?:any
iHeight?:any
iWidth?:any
cColor?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }