export default class t_PurOrderEntry {
      columnArr=['iPOLineID','iPOID','cPOCode','cInvCode','iQuantity','iNum','iQuotedPrice','iUnitPrice','iTaxUnitPrice','iTaxRate','iMoney','iTax','iSum','iDisCount','KL','KL2','iNatUnitPrice','iNatTaxPrice','iNatMoney','iNatTax','iNatSum','iNatDisCount','dArriveDate','iReceivedQTY','iReceivedNum','iReceivedMoney','iInvQTY','iInvNum','iInvMoney','iNatInvMoney','iOriTotal','iTotal','iflag','PPCIds','bGsp','cUnitID','iInvExchRate','iArrQTY','iArrNum','iArrMoney','iNatArrMoney','iReqLineID','cReqCode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','bTaxCost','cbCloser','iPPartId','cParentInvCode','iPQuantity','iPTOSeq','cSource','SoDId','SoType','ContractRowGUID','cupsocode','iInvMPCost','ContractCode','ContractRowNo','fPoValidQuantity','fPoValidNum','fPoArrQuantity','fPoArrNum','fPoRetQuantity','fPoRetNum','fPoRefuseQuantity','fPoRefuseNum','cSdtype','iSdLineID','cSdOrderNo','cMiNo','cProductNo','cbCloseTime','cbCloseDate','dqkts','cDNote','cLineCloser','cProMaterialNote','cInvName','cInvStd','cComUnitCode','cItemClsNo','cDetailPrNo','cPurUnitID','iPurExchRate','iPurNum','iArrPurNum','iReceivedPurNum','iInvPurNum','cSchStatus','dBegDate','dEndDate','dAgreeDate','cSchStatusDate','cSchStatusNote','cPriorityType','cSourType','cSourceCode','iSourceLineID','iBarTtlCnt','iBarPrnCnt','iPackWaySmallQty','iPrintQty']
      iPOLineID?:any
iPOID?:any
cPOCode?:any
cInvCode?:any
iQuantity?:any
iNum?:any
iQuotedPrice?:any
iUnitPrice?:any
iTaxUnitPrice?:any
iTaxRate?:any
iMoney?:any
iTax?:any
iSum?:any
iDisCount?:any
KL?:any
KL2?:any
iNatUnitPrice?:any
iNatTaxPrice?:any
iNatMoney?:any
iNatTax?:any
iNatSum?:any
iNatDisCount?:any
dArriveDate?:any
iReceivedQTY?:any
iReceivedNum?:any
iReceivedMoney?:any
iInvQTY?:any
iInvNum?:any
iInvMoney?:any
iNatInvMoney?:any
iOriTotal?:any
iTotal?:any
iflag?:any
PPCIds?:any
bGsp?:any
cUnitID?:any
iInvExchRate?:any
iArrQTY?:any
iArrNum?:any
iArrMoney?:any
iNatArrMoney?:any
iReqLineID?:any
cReqCode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
bTaxCost?:any
cbCloser?:any
iPPartId?:any
cParentInvCode?:any
iPQuantity?:any
iPTOSeq?:any
cSource?:any
SoDId?:any
SoType?:any
ContractRowGUID?:any
cupsocode?:any
iInvMPCost?:any
ContractCode?:any
ContractRowNo?:any
fPoValidQuantity?:any
fPoValidNum?:any
fPoArrQuantity?:any
fPoArrNum?:any
fPoRetQuantity?:any
fPoRetNum?:any
fPoRefuseQuantity?:any
fPoRefuseNum?:any
cSdtype?:any
iSdLineID?:any
cSdOrderNo?:any
cMiNo?:any
cProductNo?:any
cbCloseTime?:any
cbCloseDate?:any
dqkts?:any
cDNote?:any
cLineCloser?:any
cProMaterialNote?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any
cDetailPrNo?:any
cPurUnitID?:any
iPurExchRate?:any
iPurNum?:any
iArrPurNum?:any
iReceivedPurNum?:any
iInvPurNum?:any
cSchStatus?:any
dBegDate?:any
dEndDate?:any
dAgreeDate?:any
cSchStatusDate?:any
cSchStatusNote?:any
cPriorityType?:any
cSourType?:any
cSourceCode?:any
iSourceLineID?:any
iBarTtlCnt?:any
iBarPrnCnt?:any
iPackWaySmallQty?:any
iPrintQty?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }