export default class t_PurArrivalPlanEntry2 {
      columnArr=['iArrLineID','iArrID','cArrCode','cWhCode','cInvCode','iNum','iQuantity','iUnitPrice','iTaxUnitPrice','iTaxRate','iMoney','iTax','iSum','iNatUnitPrice','iNatTaxPrice','iNatMoney','iNatTax','iNatSum','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cUnitID','fValidInQuan','fKPQuantity','fRealQuantity','fValidQuantity','finValidQuantity','iCorId','fRetQuantity','fInValidInQuan','bGsp','cBatch','dVDate','dPDate','fRefuseQuantity','cGspState','fValidNum','fValidInNum','fInValidNum','fRealNum','bTaxCost','bInspect','fRefuseNum','iPPartId','cParentInvCode','iPQuantity','iPTOSeq','cSource','SoDId','SoType','ContractRowGUID','imassdate','cmassunit','bexigency','cbcloser','fSumRefuseQuantity','FSumRefuseNum','fRetNum','fDTQuantity','fInvalidInNum','fDegradeQuantity','fDegradeNum','fDegradeInQuantity','fDegradeInNum','fInspectQuantity','fInspectNum','iInvMPCost','iInvExchRate','objectid_source','autoid_source','ufts_source','irowno_source','cSdtype','cSdOrderNo','iSdLineID','cMiNo','cProductNo','cPOCode','iPOLineID','dlineclosedate','ContractCode','ContractRowNo','RejectSource','iciqbookid','cciqbookcode','cciqcode','fciqchangrate','irejectautoid','iExpiratDateCalcu','cExpirationdate','dExpirationdate','cupsocode','iorderdid','iordertype','csoordercode','iorderseq','dqkts','cDNote','cLineCloser','cPosition','cbCloseDate','cInvName','cInvStd','cComUnitCode','cItemClsNo','cPurUnitID','iPurExchRate','iPurNum','fValidInPurNum','fRetPurNum','iArrQTY','iArrNum','cProMaterialNote','fRetinValidQuantity','fRetinValidNum','iPackWayBigQty','iPrintQty','dRecDate','cBatchCHKResult','cCHKNote','dCHKDate']
      iArrLineID?:any
iArrID?:any
cArrCode?:any
cWhCode?:any
cInvCode?:any
iNum?:any
iQuantity?:any
iUnitPrice?:any
iTaxUnitPrice?:any
iTaxRate?:any
iMoney?:any
iTax?:any
iSum?:any
iNatUnitPrice?:any
iNatTaxPrice?:any
iNatMoney?:any
iNatTax?:any
iNatSum?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cUnitID?:any
fValidInQuan?:any
fKPQuantity?:any
fRealQuantity?:any
fValidQuantity?:any
finValidQuantity?:any
iCorId?:any
fRetQuantity?:any
fInValidInQuan?:any
bGsp?:any
cBatch?:any
dVDate?:any
dPDate?:any
fRefuseQuantity?:any
cGspState?:any
fValidNum?:any
fValidInNum?:any
fInValidNum?:any
fRealNum?:any
bTaxCost?:any
bInspect?:any
fRefuseNum?:any
iPPartId?:any
cParentInvCode?:any
iPQuantity?:any
iPTOSeq?:any
cSource?:any
SoDId?:any
SoType?:any
ContractRowGUID?:any
imassdate?:any
cmassunit?:any
bexigency?:any
cbcloser?:any
fSumRefuseQuantity?:any
FSumRefuseNum?:any
fRetNum?:any
fDTQuantity?:any
fInvalidInNum?:any
fDegradeQuantity?:any
fDegradeNum?:any
fDegradeInQuantity?:any
fDegradeInNum?:any
fInspectQuantity?:any
fInspectNum?:any
iInvMPCost?:any
iInvExchRate?:any
objectid_source?:any
autoid_source?:any
ufts_source?:any
irowno_source?:any
cSdtype?:any
cSdOrderNo?:any
iSdLineID?:any
cMiNo?:any
cProductNo?:any
cPOCode?:any
iPOLineID?:any
dlineclosedate?:any
ContractCode?:any
ContractRowNo?:any
RejectSource?:any
iciqbookid?:any
cciqbookcode?:any
cciqcode?:any
fciqchangrate?:any
irejectautoid?:any
iExpiratDateCalcu?:any
cExpirationdate?:any
dExpirationdate?:any
cupsocode?:any
iorderdid?:any
iordertype?:any
csoordercode?:any
iorderseq?:any
dqkts?:any
cDNote?:any
cLineCloser?:any
cPosition?:any
cbCloseDate?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any
cPurUnitID?:any
iPurExchRate?:any
iPurNum?:any
fValidInPurNum?:any
fRetPurNum?:any
iArrQTY?:any
iArrNum?:any
cProMaterialNote?:any
fRetinValidQuantity?:any
fRetinValidNum?:any
iPackWayBigQty?:any
iPrintQty?:any
dRecDate?:any
cBatchCHKResult?:any
cCHKNote?:any
dCHKDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }