export default class t_QMInspectVouchEntry {
      columnArr=['iInterID','iAutoID','cInspectCode','cInvCode','cWhCode','cBatchNo','cProBatch','dProDate','dVDate','cUnitCode','iChangeRate','iQuantity','iNum','iSumQuantity','iSumNum','bFlag','cTestStyle','iSourceAutoID','cPoCode','iPoAutoID','cRejectCode','iRejectAutoID','cSdOrderNo','iSdOrderAutoID','cPosition','cByProDuct','iMassDate','cMassUnit','cSoorderCode','iSoorderAuotoID','iWoID','iWoAutoID','cWoNo','cContractCode','bExigency','cPcsTransType','cVMIVenCode','cExpiratDateCalcu','dExpirationdate','cBatchProperty1','cBatchProperty2','cBatchProperty3','cBatchProperty4','cBatchProperty5','cBatchProperty6','cBatchProperty7','cBatchProperty8','cBatchProperty9','cBatchProperty10','cSoorderType','cPFCode','cReturnReasonCode','bMergeChechFlag','cBsysBarcode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cWcNo','cResourceNo','cRptNo']
      iInterID?:any
iAutoID?:any
cInspectCode?:any
cInvCode?:any
cWhCode?:any
cBatchNo?:any
cProBatch?:any
dProDate?:any
dVDate?:any
cUnitCode?:any
iChangeRate?:any
iQuantity?:any
iNum?:any
iSumQuantity?:any
iSumNum?:any
bFlag?:any
cTestStyle?:any
iSourceAutoID?:any
cPoCode?:any
iPoAutoID?:any
cRejectCode?:any
iRejectAutoID?:any
cSdOrderNo?:any
iSdOrderAutoID?:any
cPosition?:any
cByProDuct?:any
iMassDate?:any
cMassUnit?:any
cSoorderCode?:any
iSoorderAuotoID?:any
iWoID?:any
iWoAutoID?:any
cWoNo?:any
cContractCode?:any
bExigency?:any
cPcsTransType?:any
cVMIVenCode?:any
cExpiratDateCalcu?:any
dExpirationdate?:any
cBatchProperty1?:any
cBatchProperty2?:any
cBatchProperty3?:any
cBatchProperty4?:any
cBatchProperty5?:any
cBatchProperty6?:any
cBatchProperty7?:any
cBatchProperty8?:any
cBatchProperty9?:any
cBatchProperty10?:any
cSoorderType?:any
cPFCode?:any
cReturnReasonCode?:any
bMergeChechFlag?:any
cBsysBarcode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cWcNo?:any
cResourceNo?:any
cRptNo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }