export default class t_QMRejectVouchEntry {
      columnArr=['ID','cRejectCode','iAutoID','cReasonCode','fQuantity','fNum','cScrapDisCode','iDisposeFlow','cDIMInvCode','cDIMUnitID','fDIMChangRate','fDIMQuantity','fDIMNum','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cDepCode','bFlag','bSTNextYear','fMATCost','FBADLose','cDIMBatch','dDIMVDate','iDIMMassDate','cDIMMASSUnit','fSumReWorkQTY','fSumReWorkNum','cbVENCode','iDIMExpiratDateCalcu','cDIMExpirationdate','dDIMExpirationdate','cPuPOCode','iPUPODID','MOORDEROPSEQ','CBWHCODE','CBSYSBARCODE','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37']
      ID?:any
cRejectCode?:any
iAutoID?:any
cReasonCode?:any
fQuantity?:any
fNum?:any
cScrapDisCode?:any
iDisposeFlow?:any
cDIMInvCode?:any
cDIMUnitID?:any
fDIMChangRate?:any
fDIMQuantity?:any
fDIMNum?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cDepCode?:any
bFlag?:any
bSTNextYear?:any
fMATCost?:any
FBADLose?:any
cDIMBatch?:any
dDIMVDate?:any
iDIMMassDate?:any
cDIMMASSUnit?:any
fSumReWorkQTY?:any
fSumReWorkNum?:any
cbVENCode?:any
iDIMExpiratDateCalcu?:any
cDIMExpirationdate?:any
dDIMExpirationdate?:any
cPuPOCode?:any
iPUPODID?:any
MOORDEROPSEQ?:any
CBWHCODE?:any
CBSYSBARCODE?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }