export default class t_QMCheckVouchEntry {
      columnArr=['ID','iAutoID','bGuideType','cCHKItemCode','cCHKDuideCode','cInPortGrade','cStandard','fUpperLimit','fLowLimit','cGuideUnit','fQuideRegQuantity','fQuideDisQuantity','fQuideBreakQuantity','dCheckDate','cCheckTime','cPersonCode','cCheckValue','cCHKAPPCode','fTargetQty','cCHKPlaceCode','cCHKEVNCode','cCHKTempCode','iACB','iREB','cISDevCostType','fISDevfee','fISMafee','cISMaType','fISMaRate','cIsManRateType','fISManFee','fTargeTisCost','isShowProof','cInsLevelB','cBUGGrade','fAQLB','cRamisType','fISMaUnitPrice','cTargeTQJug','fIsDevCost','fIsMaCost','fIsManCost','cCHKDrawCode','cDTMethodb','fUpperWarp','fLowerWarp','bRecordDetails','cMaxCheckValue','cMinCheckValue','cGroupCode','cGComunitCode','fGQuantity','fGChangeRate','fCHKQuantity','fCHKValidQty','fCHKInvalidQty','fDTRateB','fDTQuantyB','fRuleCodeB','bBreakCheck','bMustBreak','cRounded','bRounded','bRohs','bRandorProjectB','cCHKStandardProvision','cCHKConclusionB','BatchPropertyB','bMustCHeck','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cCheckCode','cWcNo','cResourceNo','cRptNo','cQMRate','cnote']
      ID?:any
iAutoID?:any
bGuideType?:any
cCHKItemCode?:any
cCHKDuideCode?:any
cInPortGrade?:any
cStandard?:any
fUpperLimit?:any
fLowLimit?:any
cGuideUnit?:any
fQuideRegQuantity?:any
fQuideDisQuantity?:any
fQuideBreakQuantity?:any
dCheckDate?:any
cCheckTime?:any
cPersonCode?:any
cCheckValue?:any
cCHKAPPCode?:any
fTargetQty?:any
cCHKPlaceCode?:any
cCHKEVNCode?:any
cCHKTempCode?:any
iACB?:any
iREB?:any
cISDevCostType?:any
fISDevfee?:any
fISMafee?:any
cISMaType?:any
fISMaRate?:any
cIsManRateType?:any
fISManFee?:any
fTargeTisCost?:any
isShowProof?:any
cInsLevelB?:any
cBUGGrade?:any
fAQLB?:any
cRamisType?:any
fISMaUnitPrice?:any
cTargeTQJug?:any
fIsDevCost?:any
fIsMaCost?:any
fIsManCost?:any
cCHKDrawCode?:any
cDTMethodb?:any
fUpperWarp?:any
fLowerWarp?:any
bRecordDetails?:any
cMaxCheckValue?:any
cMinCheckValue?:any
cGroupCode?:any
cGComunitCode?:any
fGQuantity?:any
fGChangeRate?:any
fCHKQuantity?:any
fCHKValidQty?:any
fCHKInvalidQty?:any
fDTRateB?:any
fDTQuantyB?:any
fRuleCodeB?:any
bBreakCheck?:any
bMustBreak?:any
cRounded?:any
bRounded?:any
bRohs?:any
bRandorProjectB?:any
cCHKStandardProvision?:any
cCHKConclusionB?:any
BatchPropertyB?:any
bMustCHeck?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cCheckCode?:any
cWcNo?:any
cResourceNo?:any
cRptNo?:any
cQMRate?:any
cnote?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }