export default class t_QMCheckProject {
      columnArr=['ID','IVTID','cProjectCode','cProjectName','cCHKNormalCode','dDate','cBuildPerson','cVouchType','cStatus','cOperator','cChecker','cModifier','dOpeDate','dCheckDate','dModifyDate','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','dCostDate','cCostType','cCostMaker','fCost','cDepCode','cCheckPersonCode','bStopUse','iPrintCount','cCleanver','cSysBarCode']
      ID?:any
IVTID?:any
cProjectCode?:any
cProjectName?:any
cCHKNormalCode?:any
dDate?:any
cBuildPerson?:any
cVouchType?:any
cStatus?:any
cOperator?:any
cChecker?:any
cModifier?:any
dOpeDate?:any
dCheckDate?:any
dModifyDate?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
dCostDate?:any
cCostType?:any
cCostMaker?:any
fCost?:any
cDepCode?:any
cCheckPersonCode?:any
bStopUse?:any
iPrintCount?:any
cCleanver?:any
cSysBarCode?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }