export default class t_QMRejectVouch {
      columnArr=['ID','cVouchType','cRejectCode','iSourceAutoID','iSourceID','cSourceCode','cSource','cPoCode','cProBatch','iCheckID','cCheckCode','dArrivalDate','dCHKDate','cWhCode','cCheckPerson','dDate','cInvCode','cVenCode','cInspectDepCode','cItemClass','cItemCode','cItemCName','cItemName','cUnitID','fChangRate','cBatch','dProDate','dVDate','fSumQuantity','fSumNum','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cOrderType','cSoOrderCode','iSoOrderAutoID','iProOrderID','cProOrderCode','iProOrderAutoid','cCusCode','cContractCode','cContractStrCode','cWorkCenter','iProcessAutoID','cByProduct','bExigency','cPosition','iMassDate','cMassUnit','cCheckTypeCode','fInvPrice','fBadLoseAll','PcsTransType','cVmiVenCode','iReturnCount','cSourceProOrderCode','iSourceProOrderRowNo','iSourceProOrderID','iSourceProOrderAUTOID','iExpiratDateCalcu','cExpirationdate','dExpirationdate','cBatchProperty1','cBatchProperty2','cBatchProperty3','cBatchProperty4','cBatchProperty5','cBatchProperty6','cBatchProperty7','cBatchProperty8','cBatchProperty9','cBatchProperty10','iOrderdID','cSoOrderType','cOrderCode','iOrderSeq','cReturnReasonCode','iPrintCount','cCleanVer','cPFCode','bMergeCheckFlag','iMergeCheckAutoID','cSysBarCode','cCurrentAuditor','cStatus','cOperator','cChecker','cModifier','dOpeDate','dCheckDate','dModifyDate','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16']
      ID?:any
cVouchType?:any
cRejectCode?:any
iSourceAutoID?:any
iSourceID?:any
cSourceCode?:any
cSource?:any
cPoCode?:any
cProBatch?:any
iCheckID?:any
cCheckCode?:any
dArrivalDate?:any
dCHKDate?:any
cWhCode?:any
cCheckPerson?:any
dDate?:any
cInvCode?:any
cVenCode?:any
cInspectDepCode?:any
cItemClass?:any
cItemCode?:any
cItemCName?:any
cItemName?:any
cUnitID?:any
fChangRate?:any
cBatch?:any
dProDate?:any
dVDate?:any
fSumQuantity?:any
fSumNum?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cOrderType?:any
cSoOrderCode?:any
iSoOrderAutoID?:any
iProOrderID?:any
cProOrderCode?:any
iProOrderAutoid?:any
cCusCode?:any
cContractCode?:any
cContractStrCode?:any
cWorkCenter?:any
iProcessAutoID?:any
cByProduct?:any
bExigency?:any
cPosition?:any
iMassDate?:any
cMassUnit?:any
cCheckTypeCode?:any
fInvPrice?:any
fBadLoseAll?:any
PcsTransType?:any
cVmiVenCode?:any
iReturnCount?:any
cSourceProOrderCode?:any
iSourceProOrderRowNo?:any
iSourceProOrderID?:any
iSourceProOrderAUTOID?:any
iExpiratDateCalcu?:any
cExpirationdate?:any
dExpirationdate?:any
cBatchProperty1?:any
cBatchProperty2?:any
cBatchProperty3?:any
cBatchProperty4?:any
cBatchProperty5?:any
cBatchProperty6?:any
cBatchProperty7?:any
cBatchProperty8?:any
cBatchProperty9?:any
cBatchProperty10?:any
iOrderdID?:any
cSoOrderType?:any
cOrderCode?:any
iOrderSeq?:any
cReturnReasonCode?:any
iPrintCount?:any
cCleanVer?:any
cPFCode?:any
bMergeCheckFlag?:any
iMergeCheckAutoID?:any
cSysBarCode?:any
cCurrentAuditor?:any
cStatus?:any
cOperator?:any
cChecker?:any
cModifier?:any
dOpeDate?:any
dCheckDate?:any
dModifyDate?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }