export default class t_QMCheckVouch {
      columnArr=['ID','cVouchType','cCheckCode','iInSpectID','cInSpectCode','iInSpectAutoID','iSourceAutoID','iSourceID','cSourceCode','cSource','cPoCode','cInSpectDepCode','dArrivalDate','cInSpectPerson','cItemClass','cItemCode','cItemCName','cItemName','dDate','cDepCode','cVenCode','cInvCode','cUnitId','iTestStyle','iProjectID','cDTMethod','cDTStyle','fDtRate','cCheckUnit','fChangRate','fCheckRate','fQuantity','fNum','fDTQuantity','fDTNum','cBatch','cPROBatch','dProDate','dVDate','CFREE1','CFREE2','CFREE3','CFREE4','CFREE5','CFREE6','CFREE7','CFREE8','CFREE9','CFREE10','fRegBreakQuantity','fRegBreakNum','fReguBreakQuantity','fReguBreakNum','fDisBreakQuantity','fDisBreakNum','dDisuBreakQuantity','dDisuBreakNum','fRegQuantity','fRegNum','fConQuantity','fConNum','fDisQuantity','fDisNum','cCheckPersonCode','bPuInFlag','bProInFlag','bRejFlag','cWhCode','bSTNextYear','cOrderType','ISOORDERAUTOID','IPROORDERID','IPROORDERAUTOID','cCusCode','cContractCode','cPosition','fIsCost','iAC','iRE','cINSLevel','bExigency','cReasonCode','cYielderCode','DYieldDate','cNote','iProcessAutoID','cWorkCenter','cContractStrCode','cByProduct','cCheckTypeCode','fAQL','cCostType','fCost','cMassUnit','iMassDate','cSoorderCode','cProorderCode','cDisBreakQtyDealType','cBatchCHKResult','fSumQuantity','fSumNum','cTestRule','cRuleCode','cPcsTransType','cVMivenCode','iReturnCount','IsWfControlled','fCheckChangRate','fCheckQty','fCheckNum','iFRegBreakQtyDealType','CSOURCEPROORDERCODE','ISOURCEPROORDERROWNO','ISOURCEPROORDERID','ISOURCEPROORDERAUTOID','iExpiratDateCalcu','cExpirationdate','dExpirationdate','cBatchProperty1','cBatchProperty2','cBatchProperty3','cBatchProperty4','cBatchProperty5','cBatchProperty6','cBatchProperty7','cBatchProperty8','cBatchProperty9','cBatchProperty10','IORDERDID','ISOORDERTYPE','CORDERCODE','IORDERSEQ','cCHKNormalCode','cRandorProject','cReturnReasonCode','cCHKConclusion','cChanger','dChangeDate','dInspectDate','dCompleteDate','fCompleteDays','DPLANCOMPLETEDATE','FPLANCOMPLETEDAYS','cCleanVer','cPFCODE','fSampQty','fSampQtyIns','bMergeCheckFlag','cMergeCheckRule','bWithInspectInFo','bProductCheckDetail','cSysBarCode','cCurrentAuditor','cStatus','cOperator','cChecker','cModifier','dOpeDate','dCheckDate','dModifyDate','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cBusType']
      ID?:any
cVouchType?:any
cCheckCode?:any
iInSpectID?:any
cInSpectCode?:any
iInSpectAutoID?:any
iSourceAutoID?:any
iSourceID?:any
cSourceCode?:any
cSource?:any
cPoCode?:any
cInSpectDepCode?:any
dArrivalDate?:any
cInSpectPerson?:any
cItemClass?:any
cItemCode?:any
cItemCName?:any
cItemName?:any
dDate?:any
cDepCode?:any
cVenCode?:any
cInvCode?:any
cUnitId?:any
iTestStyle?:any
iProjectID?:any
cDTMethod?:any
cDTStyle?:any
fDtRate?:any
cCheckUnit?:any
fChangRate?:any
fCheckRate?:any
fQuantity?:any
fNum?:any
fDTQuantity?:any
fDTNum?:any
cBatch?:any
cPROBatch?:any
dProDate?:any
dVDate?:any
CFREE1?:any
CFREE2?:any
CFREE3?:any
CFREE4?:any
CFREE5?:any
CFREE6?:any
CFREE7?:any
CFREE8?:any
CFREE9?:any
CFREE10?:any
fRegBreakQuantity?:any
fRegBreakNum?:any
fReguBreakQuantity?:any
fReguBreakNum?:any
fDisBreakQuantity?:any
fDisBreakNum?:any
dDisuBreakQuantity?:any
dDisuBreakNum?:any
fRegQuantity?:any
fRegNum?:any
fConQuantity?:any
fConNum?:any
fDisQuantity?:any
fDisNum?:any
cCheckPersonCode?:any
bPuInFlag?:any
bProInFlag?:any
bRejFlag?:any
cWhCode?:any
bSTNextYear?:any
cOrderType?:any
ISOORDERAUTOID?:any
IPROORDERID?:any
IPROORDERAUTOID?:any
cCusCode?:any
cContractCode?:any
cPosition?:any
fIsCost?:any
iAC?:any
iRE?:any
cINSLevel?:any
bExigency?:any
cReasonCode?:any
cYielderCode?:any
DYieldDate?:any
cNote?:any
iProcessAutoID?:any
cWorkCenter?:any
cContractStrCode?:any
cByProduct?:any
cCheckTypeCode?:any
fAQL?:any
cCostType?:any
fCost?:any
cMassUnit?:any
iMassDate?:any
cSoorderCode?:any
cProorderCode?:any
cDisBreakQtyDealType?:any
cBatchCHKResult?:any
fSumQuantity?:any
fSumNum?:any
cTestRule?:any
cRuleCode?:any
cPcsTransType?:any
cVMivenCode?:any
iReturnCount?:any
IsWfControlled?:any
fCheckChangRate?:any
fCheckQty?:any
fCheckNum?:any
iFRegBreakQtyDealType?:any
CSOURCEPROORDERCODE?:any
ISOURCEPROORDERROWNO?:any
ISOURCEPROORDERID?:any
ISOURCEPROORDERAUTOID?:any
iExpiratDateCalcu?:any
cExpirationdate?:any
dExpirationdate?:any
cBatchProperty1?:any
cBatchProperty2?:any
cBatchProperty3?:any
cBatchProperty4?:any
cBatchProperty5?:any
cBatchProperty6?:any
cBatchProperty7?:any
cBatchProperty8?:any
cBatchProperty9?:any
cBatchProperty10?:any
IORDERDID?:any
ISOORDERTYPE?:any
CORDERCODE?:any
IORDERSEQ?:any
cCHKNormalCode?:any
cRandorProject?:any
cReturnReasonCode?:any
cCHKConclusion?:any
cChanger?:any
dChangeDate?:any
dInspectDate?:any
dCompleteDate?:any
fCompleteDays?:any
DPLANCOMPLETEDATE?:any
FPLANCOMPLETEDAYS?:any
cCleanVer?:any
cPFCODE?:any
fSampQty?:any
fSampQtyIns?:any
bMergeCheckFlag?:any
cMergeCheckRule?:any
bWithInspectInFo?:any
bProductCheckDetail?:any
cSysBarCode?:any
cCurrentAuditor?:any
cStatus?:any
cOperator?:any
cChecker?:any
cModifier?:any
dOpeDate?:any
dCheckDate?:any
dModifyDate?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cBusType?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }