export default class t_Resource {
      columnArr=['iResourceID','cResourceNo','cResourceName','cResClsNo','cResourceType','iResourceNumber','cResOccupyType','iPreStocks','iPostStocks','iUsage','iEfficient','cResouceInformation','cIsInfinityAbility','mResourcePicture','iWcID','cWcNo','cDeptNo','cDeptName','cStatus','iSchemeID','iCacheTime','iLastBatchPercent','cIsKey','cNeedChanged','cProChaType1Sort','FProChaType1ID','FProChaType2ID','FProChaType3ID','FProChaType4ID','FProChaType5ID','FProChaType6ID','FProChaType7ID','FProChaType8ID','FProChaType9ID','FProChaType10ID','FProChaType11ID','FProChaType12ID','cResDefine1','cResDefine2','cResDefine3','cResDefine4','cResDefine5','cResDefine6','cResDefine7','cResDefine8','cResDefine9','cResDefine10','cResDefine11','cResDefine12','cResDefine13','cResDefine14','cResDefine15','cResDefine16','qkts','iKeySchSN','cNote','cPrvNo','bEndReport','cDayPlanShowType','dMaxExeDate','dCurTaskEndDate','iChangeTime','iResPreTime','cAbilityMode','iTurnsType','iTurnsTime','iPower','iPowerRate','iOtherRate','iLabRate','cTeamNo','cTeamNo2','cTeamNo3','cBatch1Filter','cBatch2Filter','cBatch3Filter','cBatch4Filter','cBatch5Filter','iBatchWoSeqID','cBatch1WorkTime','cBatch2WorkTime','cBatch3WorkTime','cBatch4WorkTime','cBatch5WorkTime','cPriorityType','cResBarCode','cResourceStation','cPLCNo','iResWorkersPd','iResHoursPd','iResOverHoursPd','cTeamResourceNo','bTeamResource','cSuppliyMode','cResOperator','cResManager','X','Y','cFloorNo','cLearnCurvesNo','cSourceStatus','dStatusChangeTime','iOverResourceNumber','iLimitResourceNumber','iOverEfficient','iLimitEfficient','iResDifficulty','iDistributionRate','cEqptCode','cResInspector','cResWorkScopeExp','cCapType','cCycleTime','cResCapacityExp','cPreTimeExp','cPostTimeExp','cResAssItemExp','iGroupPriority','iBatchQty','iBatchMaxQty','cMaterialsConsumeCalcFormula','cWorkHoursCalcFormula','iLongMix','iLongMax','iWideMix','iWideMax','iThickMix','iThickMax','iResWidth','cVenNo','iManufactureRhythm','iMinWorkTime','cSchSelected','cHostIP','cHostPort','cProcessRangeFormula','cAltResourceNo','cProtocol','cStation','cMemoryAddress','cScadaParam','iArtificialCost','cProcessCategory','iResourcePriority','cCapacityCalcMode','cCalculateNo','cResAcquireRule','cRptNo','iDispDays','iPlanHours','iSchHours','cHostName','cTechSchType']
      iResourceID?:any
cResourceNo?:any
cResourceName?:any
cResClsNo?:any
cResourceType?:any
iResourceNumber?:any
cResOccupyType?:any
iPreStocks?:any
iPostStocks?:any
iUsage?:any
iEfficient?:any
cResouceInformation?:any
cIsInfinityAbility?:any
mResourcePicture?:any
iWcID?:any
cWcNo?:any
cDeptNo?:any
cDeptName?:any
cStatus?:any
iSchemeID?:any
iCacheTime?:any
iLastBatchPercent?:any
cIsKey?:any
cNeedChanged?:any
cProChaType1Sort?:any
FProChaType1ID?:any
FProChaType2ID?:any
FProChaType3ID?:any
FProChaType4ID?:any
FProChaType5ID?:any
FProChaType6ID?:any
FProChaType7ID?:any
FProChaType8ID?:any
FProChaType9ID?:any
FProChaType10ID?:any
FProChaType11ID?:any
FProChaType12ID?:any
cResDefine1?:any
cResDefine2?:any
cResDefine3?:any
cResDefine4?:any
cResDefine5?:any
cResDefine6?:any
cResDefine7?:any
cResDefine8?:any
cResDefine9?:any
cResDefine10?:any
cResDefine11?:any
cResDefine12?:any
cResDefine13?:any
cResDefine14?:any
cResDefine15?:any
cResDefine16?:any
qkts?:any
iKeySchSN?:any
cNote?:any
cPrvNo?:any
bEndReport?:any
cDayPlanShowType?:any
dMaxExeDate?:any
dCurTaskEndDate?:any
iChangeTime?:any
iResPreTime?:any
cAbilityMode?:any
iTurnsType?:any
iTurnsTime?:any
iPower?:any
iPowerRate?:any
iOtherRate?:any
iLabRate?:any
cTeamNo?:any
cTeamNo2?:any
cTeamNo3?:any
cBatch1Filter?:any
cBatch2Filter?:any
cBatch3Filter?:any
cBatch4Filter?:any
cBatch5Filter?:any
iBatchWoSeqID?:any
cBatch1WorkTime?:any
cBatch2WorkTime?:any
cBatch3WorkTime?:any
cBatch4WorkTime?:any
cBatch5WorkTime?:any
cPriorityType?:any
cResBarCode?:any
cResourceStation?:any
cPLCNo?:any
iResWorkersPd?:any
iResHoursPd?:any
iResOverHoursPd?:any
cTeamResourceNo?:any
bTeamResource?:any
cSuppliyMode?:any
cResOperator?:any
cResManager?:any
X?:any
Y?:any
cFloorNo?:any
cLearnCurvesNo?:any
cSourceStatus?:any
dStatusChangeTime?:any
iOverResourceNumber?:any
iLimitResourceNumber?:any
iOverEfficient?:any
iLimitEfficient?:any
iResDifficulty?:any
iDistributionRate?:any
cEqptCode?:any
cResInspector?:any
cResWorkScopeExp?:any
cCapType?:any
cCycleTime?:any
cResCapacityExp?:any
cPreTimeExp?:any
cPostTimeExp?:any
cResAssItemExp?:any
iGroupPriority?:any
iBatchQty?:any
iBatchMaxQty?:any
cMaterialsConsumeCalcFormula?:any
cWorkHoursCalcFormula?:any
iLongMix?:any
iLongMax?:any
iWideMix?:any
iWideMax?:any
iThickMix?:any
iThickMax?:any
iResWidth?:any
cVenNo?:any
iManufactureRhythm?:any
iMinWorkTime?:any
cSchSelected?:any
cHostIP?:any
cHostPort?:any
cProcessRangeFormula?:any
cAltResourceNo?:any
cProtocol?:any
cStation?:any
cMemoryAddress?:any
cScadaParam?:any
iArtificialCost?:any
cProcessCategory?:any
iResourcePriority?:any
cCapacityCalcMode?:any
cCalculateNo?:any
cResAcquireRule?:any
cRptNo?:any
iDispDays?:any
iPlanHours?:any
iSchHours?:any
cHostName?:any
cTechSchType?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }