export default class t_ResourceActLog {
      columnArr=['iLogID','cIPAddress','iPort','cSerialPort','cMessage','dRespondTime','dStartTime','dEndTime','cResourceNo','cResourceName','cType','cReason','cNote','cParamDefine1','cParamDefine2','cParamDefine3','cParamDefine4','cParamDefine5','cParamDefine6','cParamDefine7','cParamDefine8','cParamDefine9','cParamDefine10','cParamDefine11','cParamDefine12','cParamDefine13','cParamDefine14','cParamDefine15','cParamDefine16']
      iLogID?:any
cIPAddress?:any
iPort?:any
cSerialPort?:any
cMessage?:any
dRespondTime?:any
dStartTime?:any
dEndTime?:any
cResourceNo?:any
cResourceName?:any
cType?:any
cReason?:any
cNote?:any
cParamDefine1?:any
cParamDefine2?:any
cParamDefine3?:any
cParamDefine4?:any
cParamDefine5?:any
cParamDefine6?:any
cParamDefine7?:any
cParamDefine8?:any
cParamDefine9?:any
cParamDefine10?:any
cParamDefine11?:any
cParamDefine12?:any
cParamDefine13?:any
cParamDefine14?:any
cParamDefine15?:any
cParamDefine16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }