export default class t_ResChaValue {
      columnArr=['FResChaValueID','FResChaValueNo','FResChaValueName','FProChaTypeID','FResChaCycleValue','FResChaRePlaceTime','FResChaMemo','FUseFixedPlaceTime','FSchSN','FUseChaCycleValue','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cWorkRouteType','fScopeBeg','fScopeEnd','fResChaValue']
      FResChaValueID?:any
FResChaValueNo?:any
FResChaValueName?:any
FProChaTypeID?:any
FResChaCycleValue?:any
FResChaRePlaceTime?:any
FResChaMemo?:any
FUseFixedPlaceTime?:any
FSchSN?:any
FUseChaCycleValue?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cWorkRouteType?:any
fScopeBeg?:any
fScopeEnd?:any
fResChaValue?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }