export default class t_ResourceGanttData {
      columnArr=['cUser','cVersionNo','iSchSdID','iModelID','iTaskID','iTaskIDold','cWoNo','cWorkItemNo','cWorkItemName','iProcessID','iWoSeqID','cTechNo','cSeqNote','iNextSeqID','cPreProcessItem','cPostProcessItem','iReqQty','iLaborTime','dBegDate','dEndDate','dActBegDate','dActEndDate','iResProcessID','cResourceNo','cResourceName','iResReqQty','iActResReqQty','dResBegDate','dResEndDate','dActResBegDate','dActResEndDate','iResRationHour','cWorkType','iCapacity','cCapacityExp','iBatchQty','iBatchWorkTime','iBatchInterTime','iResPreTime','iResPostTime','iProcessPassRate','iEfficiency','iSdLineID','cProductNo','cProductName','cSdOrderNo','cColor','cCustNo','cCustName','dRequireDate','dDeliveryDate','cResClsNo','cWcNo','cDeptNo','cIsKey','iKeySchSN','FResChaValue1ID','FResChaValue2ID','FResChaValue3ID','FResChaValue4ID','FResChaValue5ID','FResChaValue6ID','FResChaValue7ID','FResChaValue8ID','FResChaValue9ID','FResChaValue10ID','FResChaValue11ID','FResChaValue12ID','cNextSeqNote','iScrapt','cScraptExp','cDevCountPdExp','iResPreTimeOld','cMiNo','cStatus','cWoStatus','cResourceNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cType','cPriorityType','cRequireType','cBusType','iPriority','cAttributes1','cAttributes2','cAttributes3','cAttributes4','cAttributes5','cAttributes6','cAttributes7','cAttributes8','cAttributes9','cAttributes10','cAttributes11','cAttributes12','cAttributes13','cAttributes14','cAttributes15','cAttributes16']
      cUser?:any
cVersionNo?:any
iSchSdID?:any
iModelID?:any
iTaskID?:any
iTaskIDold?:any
cWoNo?:any
cWorkItemNo?:any
cWorkItemName?:any
iProcessID?:any
iWoSeqID?:any
cTechNo?:any
cSeqNote?:any
iNextSeqID?:any
cPreProcessItem?:any
cPostProcessItem?:any
iReqQty?:any
iLaborTime?:any
dBegDate?:any
dEndDate?:any
dActBegDate?:any
dActEndDate?:any
iResProcessID?:any
cResourceNo?:any
cResourceName?:any
iResReqQty?:any
iActResReqQty?:any
dResBegDate?:any
dResEndDate?:any
dActResBegDate?:any
dActResEndDate?:any
iResRationHour?:any
cWorkType?:any
iCapacity?:any
cCapacityExp?:any
iBatchQty?:any
iBatchWorkTime?:any
iBatchInterTime?:any
iResPreTime?:any
iResPostTime?:any
iProcessPassRate?:any
iEfficiency?:any
iSdLineID?:any
cProductNo?:any
cProductName?:any
cSdOrderNo?:any
cColor?:any
cCustNo?:any
cCustName?:any
dRequireDate?:any
dDeliveryDate?:any
cResClsNo?:any
cWcNo?:any
cDeptNo?:any
cIsKey?:any
iKeySchSN?:any
FResChaValue1ID?:any
FResChaValue2ID?:any
FResChaValue3ID?:any
FResChaValue4ID?:any
FResChaValue5ID?:any
FResChaValue6ID?:any
FResChaValue7ID?:any
FResChaValue8ID?:any
FResChaValue9ID?:any
FResChaValue10ID?:any
FResChaValue11ID?:any
FResChaValue12ID?:any
cNextSeqNote?:any
iScrapt?:any
cScraptExp?:any
cDevCountPdExp?:any
iResPreTimeOld?:any
cMiNo?:any
cStatus?:any
cWoStatus?:any
cResourceNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cType?:any
cPriorityType?:any
cRequireType?:any
cBusType?:any
iPriority?:any
cAttributes1?:any
cAttributes2?:any
cAttributes3?:any
cAttributes4?:any
cAttributes5?:any
cAttributes6?:any
cAttributes7?:any
cAttributes8?:any
cAttributes9?:any
cAttributes10?:any
cAttributes11?:any
cAttributes12?:any
cAttributes13?:any
cAttributes14?:any
cAttributes15?:any
cAttributes16?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }