export default class t_SchProductWorkItem {
      columnArr=['cVersionNo','iSchSdID','iBomNum','iBomAutoID','iInterID','cWoNo','cType','iOrgPlanID','cDeptNo','cRouteNo','cMiNo','cSdOrderNo','iItemID','cInvCode','cInvCodeFull','iReqQty','iReqTime','dPutDate','dBegDate','dEndDate','dRePlanDate','cWhNo','cProductWo','cProductNo','iProductQty','dProductDate','iSdLineID','cCustNo','cParentWo','cParentNo','cParentNoFull','iBomLevel','cLevelInfo','cLevelPath','cEnough','cStatus','dActBeg','dActEnd','iActQty','iInvQty','iGrossQty','iForeInQty','iForeOutQty','iCurInvQty','iKeepQty','iNetQty','iScrapt','dEarlistDate','cOperator','cOpeName','dOpeDate','iLeadTime','cBegWcNo','cNote','cCode','iSeqID','FQty','FAddupQty','iParentQty','dValidDate','dInvalidDate','iRelateLT','iAddupLT','cItemType','cSubRelate','cBomType','cInvName','cInvStd','bSelf','cComUnitCode','cItemClsNo','iBatQty','cSupplyMode','cSelect','iPercent','iRetPercent','iRetOffsetLT','cUtterType','cEco','cVersion','cEcoNote','cDeductType','FBomStatus','cScraptExp','iScraptBaseQuantity','iDispatchedQty','iScraptQty','dCanBegDate','dCanEndDate','iWoPriorityRes','iWoPriorityResLast','cPriorityType','iPriority','cSubMoldNo','iCompletionRate','cHostName','iHeadSelect','cBatchNo','iCustomizeQty','iItemLessSN','hselect','cStatusNote','cReqCodeWo','iReqLineIDWo','cSchSNType','iSchSN','iSchBatch','cSchType','iWorkQtyPd','cColor','cAttributes1','cAttributes2','cAttributes3','cAttributes4','cAttributes5','cAttributes6','cAttributes7','cAttributes8','cAttributes9','cAttributes10','cAttributes11','cAttributes12','dFirstBegDate','dFirstEndDate','cWorkRouteType','cRouteTypeSelectExp','bSetModel','cAttributes13','cAttributes14','cAttributes15','cAttributes16','iNstructionsCode','cBegVenNo','cCalculateNo','cBegResourceNo']
      cVersionNo?:any
iSchSdID?:any
iBomNum?:any
iBomAutoID?:any
iInterID?:any
cWoNo?:any
cType?:any
iOrgPlanID?:any
cDeptNo?:any
cRouteNo?:any
cMiNo?:any
cSdOrderNo?:any
iItemID?:any
cInvCode?:any
cInvCodeFull?:any
iReqQty?:any
iReqTime?:any
dPutDate?:any
dBegDate?:any
dEndDate?:any
dRePlanDate?:any
cWhNo?:any
cProductWo?:any
cProductNo?:any
iProductQty?:any
dProductDate?:any
iSdLineID?:any
cCustNo?:any
cParentWo?:any
cParentNo?:any
cParentNoFull?:any
iBomLevel?:any
cLevelInfo?:any
cLevelPath?:any
cEnough?:any
cStatus?:any
dActBeg?:any
dActEnd?:any
iActQty?:any
iInvQty?:any
iGrossQty?:any
iForeInQty?:any
iForeOutQty?:any
iCurInvQty?:any
iKeepQty?:any
iNetQty?:any
iScrapt?:any
dEarlistDate?:any
cOperator?:any
cOpeName?:any
dOpeDate?:any
iLeadTime?:any
cBegWcNo?:any
cNote?:any
cCode?:any
iSeqID?:any
FQty?:any
FAddupQty?:any
iParentQty?:any
dValidDate?:any
dInvalidDate?:any
iRelateLT?:any
iAddupLT?:any
cItemType?:any
cSubRelate?:any
cBomType?:any
cInvName?:any
cInvStd?:any
bSelf?:any
cComUnitCode?:any
cItemClsNo?:any
iBatQty?:any
cSupplyMode?:any
cSelect?:any
iPercent?:any
iRetPercent?:any
iRetOffsetLT?:any
cUtterType?:any
cEco?:any
cVersion?:any
cEcoNote?:any
cDeductType?:any
FBomStatus?:any
cScraptExp?:any
iScraptBaseQuantity?:any
iDispatchedQty?:any
iScraptQty?:any
dCanBegDate?:any
dCanEndDate?:any
iWoPriorityRes?:any
iWoPriorityResLast?:any
cPriorityType?:any
iPriority?:any
cSubMoldNo?:any
iCompletionRate?:any
cHostName?:any
iHeadSelect?:any
cBatchNo?:any
iCustomizeQty?:any
iItemLessSN?:any
hselect?:any
cStatusNote?:any
cReqCodeWo?:any
iReqLineIDWo?:any
cSchSNType?:any
iSchSN?:any
iSchBatch?:any
cSchType?:any
iWorkQtyPd?:any
cColor?:any
cAttributes1?:any
cAttributes2?:any
cAttributes3?:any
cAttributes4?:any
cAttributes5?:any
cAttributes6?:any
cAttributes7?:any
cAttributes8?:any
cAttributes9?:any
cAttributes10?:any
cAttributes11?:any
cAttributes12?:any
dFirstBegDate?:any
dFirstEndDate?:any
cWorkRouteType?:any
cRouteTypeSelectExp?:any
bSetModel?:any
cAttributes13?:any
cAttributes14?:any
cAttributes15?:any
cAttributes16?:any
iNstructionsCode?:any
cBegVenNo?:any
cCalculateNo?:any
cBegResourceNo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }