export default class t_SchProductRouteItem {
      columnArr=['cVersionNo','iSchSdID','iProcessProductID','iInterID','iEntryID','cWoNo','cInvCode','cInvCodeFull','iBomLevel','cLevelInfo','cLevelPath','iSubItemID','cSubInvCode','cSubInvCodeFull','iSeqID','cUtterType','cSubRelate','iQtyPer','iParentQty','iSubQty','iScrapt','iNormalQty','iRetPercent','iReqQty','dReqDate','iProQty','iScrapQty','iNormalScrapQty','iKeepQty','iPlanQty','cWhNo','cPacNo','iRetOffsetLt','cNote','cGetItemType','bSelf','dForeInDate','iSchBatch','cPrintColor','bDaBan','cTypeSetting','cProductSolidSize','cProductPlaneSize','iOpenQty','iBanQty','iMolecularQty','iDenominatorQty','iCurQtyUse','iCurQtyUseAll','iCurQty','bCurQtyDis','iAdvanceDate','dEarlySubItemDate','iParentReqQty','iParentDispatchedQty','iAvailableQty','cBomCode','cBomEntryID','cCalculateNo']
      cVersionNo?:any
iSchSdID?:any
iProcessProductID?:any
iInterID?:any
iEntryID?:any
cWoNo?:any
cInvCode?:any
cInvCodeFull?:any
iBomLevel?:any
cLevelInfo?:any
cLevelPath?:any
iSubItemID?:any
cSubInvCode?:any
cSubInvCodeFull?:any
iSeqID?:any
cUtterType?:any
cSubRelate?:any
iQtyPer?:any
iParentQty?:any
iSubQty?:any
iScrapt?:any
iNormalQty?:any
iRetPercent?:any
iReqQty?:any
dReqDate?:any
iProQty?:any
iScrapQty?:any
iNormalScrapQty?:any
iKeepQty?:any
iPlanQty?:any
cWhNo?:any
cPacNo?:any
iRetOffsetLt?:any
cNote?:any
cGetItemType?:any
bSelf?:any
dForeInDate?:any
iSchBatch?:any
cPrintColor?:any
bDaBan?:any
cTypeSetting?:any
cProductSolidSize?:any
cProductPlaneSize?:any
iOpenQty?:any
iBanQty?:any
iMolecularQty?:any
iDenominatorQty?:any
iCurQtyUse?:any
iCurQtyUseAll?:any
iCurQty?:any
bCurQtyDis?:any
iAdvanceDate?:any
dEarlySubItemDate?:any
iParentReqQty?:any
iParentDispatchedQty?:any
iAvailableQty?:any
cBomCode?:any
cBomEntryID?:any
cCalculateNo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }