export default class t_SchProductRoute {
      columnArr=['cVersionNo','iSchSdID','iModelID','iProcessProductID','cWoNo','iInterID','iWoProcessID','iItemID','cInvCode','iWorkItemID','cWorkItemNo','cWorkItemNoFull','iProcessID','iWoSeqID','cTechNo','cSeqNote','cWcNo','iNextSeqID','cNextSeqNote','cPreProcessID','cPostProcessID','cPreProcessItem','cPostProcessItem','X','Y','iAutoID','cLevelInfo','cLevelPath','iLevel','iParentItemID','cParentItemNo','cParentItemNoFull','iRouteInterID','iProcessSumQty','iQtyPer','iParentQty','cSourceCode','iSourceInterID','iSourceEntryID','cEasID','cParellelType','cParallelNo','iSeqRatio','cKeyBrantch','cCompSeq','cIsReport','cMoveType','iMoveInterTime','iMoveInterQty','iMoveTime','iSeqPreTime','iSeqPostTime','cWorkType','iBatchQty','iBatchWorkTime','iBatchInterTime','iResPreTime','cResPreTimeExp','iCapacity','cCapacityExp','iResPostTime','cResPostTimeExp','iProcessPassRate','iEfficiency','iHoursPd','iWorkQtyPd','iWorkersPd','iDevCountPd','iLaborTime','iLeadTime','cStatus','iPriority','iReqQty','iActQty','iRealHour','dBegDate','dEndDate','dActBegDate','dActEndDate','cNote','cColor','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','iScrapt','cScraptExp','cDevCountPdExp','iSchBatch','iScraptLevelQty','cNextWcNo','cSeqReq','iCompHourPercent','iDevCountPdMax','dLastEndDate','dCanBegDate','dFirstBegDate','dFirstEndDate','cWorkRouteType','iScraptSeq','iScraptBaseQuantity','iScraptQty','iScraptQtySum','iDispatchedQty','iAvailableQty','iAdvanceDate','dEarlySubItemDate','cSchStatusDate','cSchStatusNote','cTechLevel','cTechSchType','cPhotoPosition','cDemoPosition','cCalculateNo','iInQty','iWipQty','cPreTechNo','cPreSeqNote','iPreWipQty']
      cVersionNo?:any
iSchSdID?:any
iModelID?:any
iProcessProductID?:any
cWoNo?:any
iInterID?:any
iWoProcessID?:any
iItemID?:any
cInvCode?:any
iWorkItemID?:any
cWorkItemNo?:any
cWorkItemNoFull?:any
iProcessID?:any
iWoSeqID?:any
cTechNo?:any
cSeqNote?:any
cWcNo?:any
iNextSeqID?:any
cNextSeqNote?:any
cPreProcessID?:any
cPostProcessID?:any
cPreProcessItem?:any
cPostProcessItem?:any
X?:any
Y?:any
iAutoID?:any
cLevelInfo?:any
cLevelPath?:any
iLevel?:any
iParentItemID?:any
cParentItemNo?:any
cParentItemNoFull?:any
iRouteInterID?:any
iProcessSumQty?:any
iQtyPer?:any
iParentQty?:any
cSourceCode?:any
iSourceInterID?:any
iSourceEntryID?:any
cEasID?:any
cParellelType?:any
cParallelNo?:any
iSeqRatio?:any
cKeyBrantch?:any
cCompSeq?:any
cIsReport?:any
cMoveType?:any
iMoveInterTime?:any
iMoveInterQty?:any
iMoveTime?:any
iSeqPreTime?:any
iSeqPostTime?:any
cWorkType?:any
iBatchQty?:any
iBatchWorkTime?:any
iBatchInterTime?:any
iResPreTime?:any
cResPreTimeExp?:any
iCapacity?:any
cCapacityExp?:any
iResPostTime?:any
cResPostTimeExp?:any
iProcessPassRate?:any
iEfficiency?:any
iHoursPd?:any
iWorkQtyPd?:any
iWorkersPd?:any
iDevCountPd?:any
iLaborTime?:any
iLeadTime?:any
cStatus?:any
iPriority?:any
iReqQty?:any
iActQty?:any
iRealHour?:any
dBegDate?:any
dEndDate?:any
dActBegDate?:any
dActEndDate?:any
cNote?:any
cColor?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
iScrapt?:any
cScraptExp?:any
cDevCountPdExp?:any
iSchBatch?:any
iScraptLevelQty?:any
cNextWcNo?:any
cSeqReq?:any
iCompHourPercent?:any
iDevCountPdMax?:any
dLastEndDate?:any
dCanBegDate?:any
dFirstBegDate?:any
dFirstEndDate?:any
cWorkRouteType?:any
iScraptSeq?:any
iScraptBaseQuantity?:any
iScraptQty?:any
iScraptQtySum?:any
iDispatchedQty?:any
iAvailableQty?:any
iAdvanceDate?:any
dEarlySubItemDate?:any
cSchStatusDate?:any
cSchStatusNote?:any
cTechLevel?:any
cTechSchType?:any
cPhotoPosition?:any
cDemoPosition?:any
cCalculateNo?:any
iInQty?:any
iWipQty?:any
cPreTechNo?:any
cPreSeqNote?:any
iPreWipQty?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }