export default class t_SchProduct {
      columnArr=['iSchSdID','cVersionNo','cType','iInterID','iSdLineID','iSeqID','iModelID','cSdOrderNo','cCustNo','cCustName','cSTCode','cBusType','cPriorityType','cStatus','cPersonCode','cRequireType','iItemID','cInvCode','cInvName','cInvStd','cUnitCode','cProductNo','bModelCompleted','iReqQty','dRequireDate','dDeliveryDate','dEarliestSchDate','cSchStatus','dBegDate','dEndDate','cMiNo','iPriority','cSelected','cWoNo','iCurQty','iPreKeepQuantity','iForeInQty','iNetQty','iSchQty','iSafeStock','fOutquantity','cNeedSet','iFHQuantity','iKPQuantity','iSourceLineID','cColor','cNote','iRopOverPer','iWeekYear','dOpeDate','iLowCode','iSchBatch','iMOutQty','iMSaleQty1','iMSaleQty2','iMSaleQty3','cSourceCode','cDeptNo','cUser','iMSaleQty','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cSchType','cProductNoAll','cScheduled','cProjectNo','iNum','iQtyPerNum','cAttributes1','cAttributes2','cAttributes3','cAttributes4','cAttributes5','cAttributes6','cAttributes7','cAttributes8','cAttributes9','cAttributes10','cAttributes11','cAttributes12','cPlanMode','dFirstBegDate','dFirstEndDate','cWorkRouteType','cRouteTypeSelectExp','cAttributes13','cAttributes14','cAttributes15','cAttributes16','cRootNo','iNstructionsCode','cRouteNo','cItemClsNo','iSchSN','cWcNo','cBatchNo','cGroupNo','cGroupQty','cGroupSN','cCustomize','iWorkQtyPd','iCustomizeQty','cSdOrderType','iAvailableQty','dPutDate','cSchSNType','cSourType','cInvABC','cCalculateNo','iBatchQty','iAvgLeadTime','cPurDateNote','cHostName','iSourceQty','dSourceDate','iSchQtySum']
      iSchSdID?:any
cVersionNo?:any
cType?:any
iInterID?:any
iSdLineID?:any
iSeqID?:any
iModelID?:any
cSdOrderNo?:any
cCustNo?:any
cCustName?:any
cSTCode?:any
cBusType?:any
cPriorityType?:any
cStatus?:any
cPersonCode?:any
cRequireType?:any
iItemID?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cUnitCode?:any
cProductNo?:any
bModelCompleted?:any
iReqQty?:any
dRequireDate?:any
dDeliveryDate?:any
dEarliestSchDate?:any
cSchStatus?:any
dBegDate?:any
dEndDate?:any
cMiNo?:any
iPriority?:any
cSelected?:any
cWoNo?:any
iCurQty?:any
iPreKeepQuantity?:any
iForeInQty?:any
iNetQty?:any
iSchQty?:any
iSafeStock?:any
fOutquantity?:any
cNeedSet?:any
iFHQuantity?:any
iKPQuantity?:any
iSourceLineID?:any
cColor?:any
cNote?:any
iRopOverPer?:any
iWeekYear?:any
dOpeDate?:any
iLowCode?:any
iSchBatch?:any
iMOutQty?:any
iMSaleQty1?:any
iMSaleQty2?:any
iMSaleQty3?:any
cSourceCode?:any
cDeptNo?:any
cUser?:any
iMSaleQty?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cSchType?:any
cProductNoAll?:any
cScheduled?:any
cProjectNo?:any
iNum?:any
iQtyPerNum?:any
cAttributes1?:any
cAttributes2?:any
cAttributes3?:any
cAttributes4?:any
cAttributes5?:any
cAttributes6?:any
cAttributes7?:any
cAttributes8?:any
cAttributes9?:any
cAttributes10?:any
cAttributes11?:any
cAttributes12?:any
cPlanMode?:any
dFirstBegDate?:any
dFirstEndDate?:any
cWorkRouteType?:any
cRouteTypeSelectExp?:any
cAttributes13?:any
cAttributes14?:any
cAttributes15?:any
cAttributes16?:any
cRootNo?:any
iNstructionsCode?:any
cRouteNo?:any
cItemClsNo?:any
iSchSN?:any
cWcNo?:any
cBatchNo?:any
cGroupNo?:any
cGroupQty?:any
cGroupSN?:any
cCustomize?:any
iWorkQtyPd?:any
iCustomizeQty?:any
cSdOrderType?:any
iAvailableQty?:any
dPutDate?:any
cSchSNType?:any
cSourType?:any
cInvABC?:any
cCalculateNo?:any
iBatchQty?:any
iAvgLeadTime?:any
cPurDateNote?:any
cHostName?:any
iSourceQty?:any
dSourceDate?:any
iSchQtySum?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }