export default class t_SchProduct_Deleted {
      columnArr=['dDeletedate','cBakType','cBatchNo','iSchSdID','cVersionNo','cType','iInterID','iSdLineID','iSeqID','iModelID','cSdOrderNo','cCustNo','cCustName','cSTCode','cBusType','cPriorityType','cStatus','cPersonCode','cRequireType','iItemID','cInvCode','cInvName','cInvStd','cUnitCode','cProductNo','bModelCompleted','iReqQty','dRequireDate','dDeliveryDate','dEarliestSchDate','cSchStatus','dBegDate','dEndDate','cMiNo','iPriority','cSelected','cWoNo','iCurQty','iPreKeepQuantity','iForeInQty','iNetQty','iSchQty','iSafeStock','fOutquantity','cNeedSet','iFHQuantity','iKPQuantity','iSourceLineID','cColor','cNote','iRopOverPer','iWeekYear']
      dDeletedate?:any
cBakType?:any
cBatchNo?:any
iSchSdID?:any
cVersionNo?:any
cType?:any
iInterID?:any
iSdLineID?:any
iSeqID?:any
iModelID?:any
cSdOrderNo?:any
cCustNo?:any
cCustName?:any
cSTCode?:any
cBusType?:any
cPriorityType?:any
cStatus?:any
cPersonCode?:any
cRequireType?:any
iItemID?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cUnitCode?:any
cProductNo?:any
bModelCompleted?:any
iReqQty?:any
dRequireDate?:any
dDeliveryDate?:any
dEarliestSchDate?:any
cSchStatus?:any
dBegDate?:any
dEndDate?:any
cMiNo?:any
iPriority?:any
cSelected?:any
cWoNo?:any
iCurQty?:any
iPreKeepQuantity?:any
iForeInQty?:any
iNetQty?:any
iSchQty?:any
iSafeStock?:any
fOutquantity?:any
cNeedSet?:any
iFHQuantity?:any
iKPQuantity?:any
iSourceLineID?:any
cColor?:any
cNote?:any
iRopOverPer?:any
iWeekYear?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }