export default class t_SchProductRouteResTemp {
      columnArr=['cVersionNo','iSchSdID','iProcessProductID','iResProcessID','iResReqQty','dResBegDate','dResEndDate','iResRationHour','iResPreTime','iResPostTime','iCycTime','cDefine35','cDefine24','cDefine25','iResPreTimeOld','cStatus','cDefine26','cTeamResourceNo','cResourceNo','dResCanBegDate','iResWaitTime','cDefine27','cDefine28','cDefine36','cDefine37','cDefine38','cDefine33','iPriority','cSdOrderNo','cProductNo','cWoNo','iPriorityRes','iPriorityResLast','iSchBatch','iSchSN','iTimeCount','cPriorityType','cResourceName','cTaskStatus','dOpeDate']
      cVersionNo?:any
iSchSdID?:any
iProcessProductID?:any
iResProcessID?:any
iResReqQty?:any
dResBegDate?:any
dResEndDate?:any
iResRationHour?:any
iResPreTime?:any
iResPostTime?:any
iCycTime?:any
cDefine35?:any
cDefine24?:any
cDefine25?:any
iResPreTimeOld?:any
cStatus?:any
cDefine26?:any
cTeamResourceNo?:any
cResourceNo?:any
dResCanBegDate?:any
iResWaitTime?:any
cDefine27?:any
cDefine28?:any
cDefine36?:any
cDefine37?:any
cDefine38?:any
cDefine33?:any
iPriority?:any
cSdOrderNo?:any
cProductNo?:any
cWoNo?:any
iPriorityRes?:any
iPriorityResLast?:any
iSchBatch?:any
iSchSN?:any
iTimeCount?:any
cPriorityType?:any
cResourceName?:any
cTaskStatus?:any
dOpeDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }