export default class t_SdMonthlyPlan {
      columnArr=['iInterID','cCode','dDate','PlannedMonth','iQuantity','cComUnitCode','RougeMonth','cStatus','cOperator','dOpeDate','cChecker','dCheckDate','iVT_ID','iAuditTypeID','cNote','cDepCode','cPersonCode','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','dDeliveryStart','dDeliveryEnd']
      iInterID?:any
cCode?:any
dDate?:any
PlannedMonth?:any
iQuantity?:any
cComUnitCode?:any
RougeMonth?:any
cStatus?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
iVT_ID?:any
iAuditTypeID?:any
cNote?:any
cDepCode?:any
cPersonCode?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
dDeliveryStart?:any
dDeliveryEnd?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }