export default class t_SdPreOrder {
      columnArr=['iInterID','cSdPreOrderNo','cCustOrderNo','cSTCode','cBusType','cCustNo','cCustName','cPriorityType','cPayCode','cExch_name','iExchRate','iTaxRate','dDate','cDeptNo','cPersonCode','cSCCode','cAddCode','cAddress','cCusPerson','iDJMoney','cOperator','dOpeDate','cChecker','dCheckDate','cStatus','iAuditTypeID','cMpsed','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cColor','iVTID','qkts','cGatheringplan','cCloser','dCloseDate','iPrintCount','cSaleType','cFxNo','cModifier','dModifyDate']
      iInterID?:any
cSdPreOrderNo?:any
cCustOrderNo?:any
cSTCode?:any
cBusType?:any
cCustNo?:any
cCustName?:any
cPriorityType?:any
cPayCode?:any
cExch_name?:any
iExchRate?:any
iTaxRate?:any
dDate?:any
cDeptNo?:any
cPersonCode?:any
cSCCode?:any
cAddCode?:any
cAddress?:any
cCusPerson?:any
iDJMoney?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cStatus?:any
iAuditTypeID?:any
cMpsed?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cColor?:any
iVTID?:any
qkts?:any
cGatheringplan?:any
cCloser?:any
dCloseDate?:any
iPrintCount?:any
cSaleType?:any
cFxNo?:any
cModifier?:any
dModifyDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }