export default class t_SdValuationEntry {
      columnArr=['iInterID','iLineID','cValuationCode','cProjectType','cContain','cSolution','cInvCode','cInvName','cInvStd','cPaperType','iMinQuantity','iMaxQuantity','iOtherMatMoney1','iOtherMatMoney2','iMatProSum','cTechNo','iOtherMacMoney1','iOtherMacMoney2','iMacMoney','iMatFreightMoney','iMatMacSum','iNatMatMacSum','fMember','fDenominator','cComUnitCode','fRatio1','fRatio2','fRatio3','fRatio4','fRatio5','fRatio6','fPriceAtFactory','iTaxRate','fManage','iProfit','iStreetOut','iStreetOutSum','iNatStreetOutSum','iStreetOutSumUSA','iSum','iNatSum','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cLineCloser','cbCloseDate','cMaterial','cColor','cDNote','mItemPicture','mItemPicture2','iPackQty','iCaseQty']
      iInterID?:any
iLineID?:any
cValuationCode?:any
cProjectType?:any
cContain?:any
cSolution?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cPaperType?:any
iMinQuantity?:any
iMaxQuantity?:any
iOtherMatMoney1?:any
iOtherMatMoney2?:any
iMatProSum?:any
cTechNo?:any
iOtherMacMoney1?:any
iOtherMacMoney2?:any
iMacMoney?:any
iMatFreightMoney?:any
iMatMacSum?:any
iNatMatMacSum?:any
fMember?:any
fDenominator?:any
cComUnitCode?:any
fRatio1?:any
fRatio2?:any
fRatio3?:any
fRatio4?:any
fRatio5?:any
fRatio6?:any
fPriceAtFactory?:any
iTaxRate?:any
fManage?:any
iProfit?:any
iStreetOut?:any
iStreetOutSum?:any
iNatStreetOutSum?:any
iStreetOutSumUSA?:any
iSum?:any
iNatSum?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cLineCloser?:any
cbCloseDate?:any
cMaterial?:any
cColor?:any
cDNote?:any
mItemPicture?:any
mItemPicture2?:any
iPackQty?:any
iCaseQty?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }