export default class t_SdDispatchDetail {
      columnArr=['iLineID','DLID','iAutoID','cDLCode','cWhCode','cPosition','cBarCode','iItemID','cInvCode','cInvName','cInvStd','cUnitCode','iQuantity','iNum','cBatchNo','cCode','iInvLine','cNote','cFree1','cFree2','cFree3','cFree4','cFree5','fOutQuantity','fOutNum','cDefine38','cDefine39','cDefine40','cDefine41','cDefine42']
      iLineID?:any
DLID?:any
iAutoID?:any
cDLCode?:any
cWhCode?:any
cPosition?:any
cBarCode?:any
iItemID?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cUnitCode?:any
iQuantity?:any
iNum?:any
cBatchNo?:any
cCode?:any
iInvLine?:any
cNote?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
fOutQuantity?:any
fOutNum?:any
cDefine38?:any
cDefine39?:any
cDefine40?:any
cDefine41?:any
cDefine42?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }