export default class t_SdMonthUpdate {
      columnArr=['iInterID','cCustNo','cDepCode','cPersonCode','cInvCode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','iSDAmount1','iSaleAmount1','iSaleReceive1','iSaleCost1','iSDAmount2','iSaleAmount2','iSaleReceive2','iSaleCost2','iSDAmount3','iSaleAmount3','iSaleReceive3','iSaleCost3','iSDAmount4','iSaleAmount4','iSaleReceive4','iSaleCost4','iSDAmount5','iSaleAmount5','iSaleReceive5','iSaleCost5','iSDAmount6','iSaleAmount6','iSaleReceive6','iSaleCost6','iSDAmount7','iSaleAmount7','iSaleReceive7','iSaleCost7','iSDAmount8','iSaleAmount8','iSaleReceive8','iSaleCost8','iSDAmount9','iSaleAmount9','iSaleReceive9','iSaleCost9','iSDAmount10','iSaleAmount10','iSaleReceive10','iSaleCost10','iSDAmount11','iSaleAmount11','iSaleReceive11','iSaleCost11','iSDAmount12','iSaleAmount12','iSaleReceive12','iSaleCost12','iSDAmount13','iSaleAmount13','iSaleReceive13','iSaleCost13','iSDAmount14','iSaleAmount14','iSaleReceive14','iSaleCost14','iSDAmount15','iSaleAmount15','iSaleReceive15','iSaleCost15','iSDAmount16','iSaleAmount16','iSaleReceive16','iSaleCost16','iSDAmount17','iSaleAmount17','iSaleReceive17','iSaleCost17','iSDAmount18','iSaleAmount18','iSaleReceive18','iSaleCost18','iSDAmount19','iSaleAmount19','iSaleReceive19','iSaleCost19','iSDAmount20','iSaleAmount20','iSaleReceive20','iSaleCost20','iSDAmount21','iSaleAmount21','iSaleReceive21','iSaleCost21','iSDAmount22','iSaleAmount22','iSaleReceive22','iSaleCost22','iSDAmount23','iSaleAmount23','iSaleReceive23','iSaleCost23','iSDAmount24','iSaleAmount24','iSaleReceive24','iSaleCost24','cUser']
      iInterID?:any
cCustNo?:any
cDepCode?:any
cPersonCode?:any
cInvCode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
iSDAmount1?:any
iSaleAmount1?:any
iSaleReceive1?:any
iSaleCost1?:any
iSDAmount2?:any
iSaleAmount2?:any
iSaleReceive2?:any
iSaleCost2?:any
iSDAmount3?:any
iSaleAmount3?:any
iSaleReceive3?:any
iSaleCost3?:any
iSDAmount4?:any
iSaleAmount4?:any
iSaleReceive4?:any
iSaleCost4?:any
iSDAmount5?:any
iSaleAmount5?:any
iSaleReceive5?:any
iSaleCost5?:any
iSDAmount6?:any
iSaleAmount6?:any
iSaleReceive6?:any
iSaleCost6?:any
iSDAmount7?:any
iSaleAmount7?:any
iSaleReceive7?:any
iSaleCost7?:any
iSDAmount8?:any
iSaleAmount8?:any
iSaleReceive8?:any
iSaleCost8?:any
iSDAmount9?:any
iSaleAmount9?:any
iSaleReceive9?:any
iSaleCost9?:any
iSDAmount10?:any
iSaleAmount10?:any
iSaleReceive10?:any
iSaleCost10?:any
iSDAmount11?:any
iSaleAmount11?:any
iSaleReceive11?:any
iSaleCost11?:any
iSDAmount12?:any
iSaleAmount12?:any
iSaleReceive12?:any
iSaleCost12?:any
iSDAmount13?:any
iSaleAmount13?:any
iSaleReceive13?:any
iSaleCost13?:any
iSDAmount14?:any
iSaleAmount14?:any
iSaleReceive14?:any
iSaleCost14?:any
iSDAmount15?:any
iSaleAmount15?:any
iSaleReceive15?:any
iSaleCost15?:any
iSDAmount16?:any
iSaleAmount16?:any
iSaleReceive16?:any
iSaleCost16?:any
iSDAmount17?:any
iSaleAmount17?:any
iSaleReceive17?:any
iSaleCost17?:any
iSDAmount18?:any
iSaleAmount18?:any
iSaleReceive18?:any
iSaleCost18?:any
iSDAmount19?:any
iSaleAmount19?:any
iSaleReceive19?:any
iSaleCost19?:any
iSDAmount20?:any
iSaleAmount20?:any
iSaleReceive20?:any
iSaleCost20?:any
iSDAmount21?:any
iSaleAmount21?:any
iSaleReceive21?:any
iSaleCost21?:any
iSDAmount22?:any
iSaleAmount22?:any
iSaleReceive22?:any
iSaleCost22?:any
iSDAmount23?:any
iSaleAmount23?:any
iSaleReceive23?:any
iSaleCost23?:any
iSDAmount24?:any
iSaleAmount24?:any
iSaleReceive24?:any
iSaleCost24?:any
cUser?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }