export default class t_SdValuationSum {
      columnArr=['iInterID','iLineID2','cValuationCode','cInvCode','cInvName','cPaperType','iMinQuantity','iMaxQuantity','iOtherMatMoney1','iOtherMatMoney2','iMatProSum','iTechNo','iOtherMacMoney1','iOtherMacMoney2','iMacMoney','iMatFreightMoney','iMatMacSum','iNatMatMacSum','fMember','fDenominator','cComUnitCode','fRatio1','fRatio2','fRatio3','fRatio4','fRatio5','fRatio6','fPriceAtFactory','iTaxRate','fManage','iProfit','iStreetOut','iStreetOutSum','iNatStreetOutSum','iStreetOutSumUSA','iSum','iNatSum','cDefine85','cDefine86','cDefine87','cDefine88','cDefine89','cDefine90','cDefine91','cDefine92','cDefine93','cDefine94','cDefine95','cDefine96','cDefine97','cDefine98','cDefine99','cDefine100','cDNote','cSolution','iPackQty','iCaseQty']
      iInterID?:any
iLineID2?:any
cValuationCode?:any
cInvCode?:any
cInvName?:any
cPaperType?:any
iMinQuantity?:any
iMaxQuantity?:any
iOtherMatMoney1?:any
iOtherMatMoney2?:any
iMatProSum?:any
iTechNo?:any
iOtherMacMoney1?:any
iOtherMacMoney2?:any
iMacMoney?:any
iMatFreightMoney?:any
iMatMacSum?:any
iNatMatMacSum?:any
fMember?:any
fDenominator?:any
cComUnitCode?:any
fRatio1?:any
fRatio2?:any
fRatio3?:any
fRatio4?:any
fRatio5?:any
fRatio6?:any
fPriceAtFactory?:any
iTaxRate?:any
fManage?:any
iProfit?:any
iStreetOut?:any
iStreetOutSum?:any
iNatStreetOutSum?:any
iStreetOutSumUSA?:any
iSum?:any
iNatSum?:any
cDefine85?:any
cDefine86?:any
cDefine87?:any
cDefine88?:any
cDefine89?:any
cDefine90?:any
cDefine91?:any
cDefine92?:any
cDefine93?:any
cDefine94?:any
cDefine95?:any
cDefine96?:any
cDefine97?:any
cDefine98?:any
cDefine99?:any
cDefine100?:any
cDNote?:any
cSolution?:any
iPackQty?:any
iCaseQty?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }