export default class t_SdOrderImport {
      columnArr=['iAutoID','iInterID','iSdLineID','cSdOrderNo','cCustOrderNo','cSTCode','cBusType','cCustNo','cCustName','cPriorityType','cPayCode','cExch_name','iExchRate','dDate','cDeptNo','cPersonCode','cSCCode','cAddCode','cAddress','cCusPerson','iDJMoney','cOperator','dOpeDate','cChecker','dCheckDate','cStatus','iAuditTypeID','cMpsed','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cLastSDOrderNo','iVTID','qkts','cGatheringplan','cCloser','dCloseDate','iPrintCount','cSaleType','cFxNo','cModifier','dModifyDate','cCusPhoneNum','iDiscountAmount','iAfterDisAmount','iRcvAmount','cSdOrderType','cProjectNo','iNstructionsCode','iOriAmount','cRequireType','iItemID','cInvCode','cInvName','cInvStd','cUnitCode','cInvClass','iInvExchRate','cCustItemNo','iReqQty','iNum','dRequireDate','dDeliveryDate','dEarliestSchDate','cSchStatus','dBegDate','dEndDate','cMiNo','iTaxRate','iQuotedPrice','iUnitPrice','iTaxUnitPrice','iMoney','iTax','iSum','iDiscount','iNatUnitPrice','iNatTaxPrice','iNatMoney','iNatTax','iNatSum','iNatDisCount','KL','KL2','iFHNum','iFHQuantity','iFHMoney','iKPQuantity','iKPNum','iKPMoney','iPreKeepQuantity','iPreKeepNum','fOutquantity','fOutnum','fRetQuantity','fRetNum','iReqQtyLast','iReqQtyDiff','cIsMps','cParentItem','iPriority','cSelected','cWoNo','iPlanQty','cNeedSet','cSourceType','cSourceCode','iSourceLineID','cDNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cLineCloser','iPlanNum','iNetQty','iSchSDID','cbCloseDate','WBID','WBPID','cProductNo','iSdLine2ID','cWhCode','cDCStatus','cPriceType','iReceivedQTY','iReceivedNum','cProMaterialNote','cComUnitCode','cItemClsNo','cWorkRouteType','cAttributes1','cAttributes2','cAttributes3','cAttributes4','cAttributes5','cAttributes6','cAttributes7','cAttributes8','cAttributes9','cAttributes10','cAttributes11','cAttributes12','cAttributes13','cAttributes14','cAttributes15','cAttributes16','cSchStatusDate','cSchStatusNote','cHostName','cSynStatus']
      iAutoID?:any
iInterID?:any
iSdLineID?:any
cSdOrderNo?:any
cCustOrderNo?:any
cSTCode?:any
cBusType?:any
cCustNo?:any
cCustName?:any
cPriorityType?:any
cPayCode?:any
cExch_name?:any
iExchRate?:any
dDate?:any
cDeptNo?:any
cPersonCode?:any
cSCCode?:any
cAddCode?:any
cAddress?:any
cCusPerson?:any
iDJMoney?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cStatus?:any
iAuditTypeID?:any
cMpsed?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cLastSDOrderNo?:any
iVTID?:any
qkts?:any
cGatheringplan?:any
cCloser?:any
dCloseDate?:any
iPrintCount?:any
cSaleType?:any
cFxNo?:any
cModifier?:any
dModifyDate?:any
cCusPhoneNum?:any
iDiscountAmount?:any
iAfterDisAmount?:any
iRcvAmount?:any
cSdOrderType?:any
cProjectNo?:any
iNstructionsCode?:any
iOriAmount?:any
cRequireType?:any
iItemID?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cUnitCode?:any
cInvClass?:any
iInvExchRate?:any
cCustItemNo?:any
iReqQty?:any
iNum?:any
dRequireDate?:any
dDeliveryDate?:any
dEarliestSchDate?:any
cSchStatus?:any
dBegDate?:any
dEndDate?:any
cMiNo?:any
iTaxRate?:any
iQuotedPrice?:any
iUnitPrice?:any
iTaxUnitPrice?:any
iMoney?:any
iTax?:any
iSum?:any
iDiscount?:any
iNatUnitPrice?:any
iNatTaxPrice?:any
iNatMoney?:any
iNatTax?:any
iNatSum?:any
iNatDisCount?:any
KL?:any
KL2?:any
iFHNum?:any
iFHQuantity?:any
iFHMoney?:any
iKPQuantity?:any
iKPNum?:any
iKPMoney?:any
iPreKeepQuantity?:any
iPreKeepNum?:any
fOutquantity?:any
fOutnum?:any
fRetQuantity?:any
fRetNum?:any
iReqQtyLast?:any
iReqQtyDiff?:any
cIsMps?:any
cParentItem?:any
iPriority?:any
cSelected?:any
cWoNo?:any
iPlanQty?:any
cNeedSet?:any
cSourceType?:any
cSourceCode?:any
iSourceLineID?:any
cDNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cLineCloser?:any
iPlanNum?:any
iNetQty?:any
iSchSDID?:any
cbCloseDate?:any
WBID?:any
WBPID?:any
cProductNo?:any
iSdLine2ID?:any
cWhCode?:any
cDCStatus?:any
cPriceType?:any
iReceivedQTY?:any
iReceivedNum?:any
cProMaterialNote?:any
cComUnitCode?:any
cItemClsNo?:any
cWorkRouteType?:any
cAttributes1?:any
cAttributes2?:any
cAttributes3?:any
cAttributes4?:any
cAttributes5?:any
cAttributes6?:any
cAttributes7?:any
cAttributes8?:any
cAttributes9?:any
cAttributes10?:any
cAttributes11?:any
cAttributes12?:any
cAttributes13?:any
cAttributes14?:any
cAttributes15?:any
cAttributes16?:any
cSchStatusDate?:any
cSchStatusNote?:any
cHostName?:any
cSynStatus?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }