export default class t_SdBillVouchEntry {
      columnArr=['SBVID','cSBVCode','AutoID','cWhCode','cInvCode','iQuantity','iNum','iQuotedPrice','iUnitPrice','iTaxUnitPrice','iMoney','iTax','iSum','iDisCount','iNatUnitPrice','iNatMoney','iNatTax','iNatSum','iNatDisCount','iSBVID','iMoneySum','iExchSum','cClue','cIncomeSub','cTaxSub','dSignDate','cMemo','iBatch','cBatch','bSettleAll','cFree1','cFree2','RdsID','iTB','dvDate','TBQuantity','TBNum','iSOsID','iDLsID','KL','KL2','cInvName','iTaxRate','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','fOutQuantity','fOutNum','cItemCode','cItem_class','fSaleCost','fSalePrice','cItemName','cItem_CName','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','iInvExchRate','cUnitID','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','dMDate','iPBVsID','cCode','cSoCode','bgsp','iPPartSeqID','iPPartID','iPPartQty','cContractID','cContractTagCode','cContractRowGuid','iMassDate','cMassUnit','bQANeedCheck','bQAUrgency','cCusInvCode','cCusInvName','cbaccounter','bcosting','cordercode','iorderrowno','fcusminprice','cvmivencode','cVenAbbName','irowno','iExpiratDateCalcu','dExpirationdate','cExpirationdate','cbatchproperty1','cbatchproperty2','cbatchproperty3','cbatchproperty4','cbatchproperty5','cbatchproperty6','cbatchproperty7','cbatchproperty8','cbatchproperty9','cbatchproperty10','idemandtype','cdemandcode','cdemandmemo','cdemandid','idemandseq','cbdlcode','cLineCloser','iNatTaxPrice','cbCloseDate','cInvStd','cComUnitCode','cItemClsNo','cReconciliation']
      SBVID?:any
cSBVCode?:any
AutoID?:any
cWhCode?:any
cInvCode?:any
iQuantity?:any
iNum?:any
iQuotedPrice?:any
iUnitPrice?:any
iTaxUnitPrice?:any
iMoney?:any
iTax?:any
iSum?:any
iDisCount?:any
iNatUnitPrice?:any
iNatMoney?:any
iNatTax?:any
iNatSum?:any
iNatDisCount?:any
iSBVID?:any
iMoneySum?:any
iExchSum?:any
cClue?:any
cIncomeSub?:any
cTaxSub?:any
dSignDate?:any
cMemo?:any
iBatch?:any
cBatch?:any
bSettleAll?:any
cFree1?:any
cFree2?:any
RdsID?:any
iTB?:any
dvDate?:any
TBQuantity?:any
TBNum?:any
iSOsID?:any
iDLsID?:any
KL?:any
KL2?:any
cInvName?:any
iTaxRate?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
fOutQuantity?:any
fOutNum?:any
cItemCode?:any
cItem_class?:any
fSaleCost?:any
fSalePrice?:any
cItemName?:any
cItem_CName?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
iInvExchRate?:any
cUnitID?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
dMDate?:any
iPBVsID?:any
cCode?:any
cSoCode?:any
bgsp?:any
iPPartSeqID?:any
iPPartID?:any
iPPartQty?:any
cContractID?:any
cContractTagCode?:any
cContractRowGuid?:any
iMassDate?:any
cMassUnit?:any
bQANeedCheck?:any
bQAUrgency?:any
cCusInvCode?:any
cCusInvName?:any
cbaccounter?:any
bcosting?:any
cordercode?:any
iorderrowno?:any
fcusminprice?:any
cvmivencode?:any
cVenAbbName?:any
irowno?:any
iExpiratDateCalcu?:any
dExpirationdate?:any
cExpirationdate?:any
cbatchproperty1?:any
cbatchproperty2?:any
cbatchproperty3?:any
cbatchproperty4?:any
cbatchproperty5?:any
cbatchproperty6?:any
cbatchproperty7?:any
cbatchproperty8?:any
cbatchproperty9?:any
cbatchproperty10?:any
idemandtype?:any
cdemandcode?:any
cdemandmemo?:any
cdemandid?:any
idemandseq?:any
cbdlcode?:any
cLineCloser?:any
iNatTaxPrice?:any
cbCloseDate?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any
cReconciliation?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }