export default class t_SdInvPriceJusts {
      columnArr=['tid','ddate','ccode','cmaker','cpersoncode','cpersonname','cmainmemo','cverifier','dverifydate','drdate','cdepcode','cdepname','autoid','id','dstartdate','cfree1','cfree2','cfree3','cfree4','cfree5','cfree6','cfree7','cfree8','cfree9','cfree10','denddate','operationtype','ipriceid','cinvcode','iuprice1','isaleprice1','iuprice2','isaleprice2','iuprice3','isaleprice3','iuprice4','isaleprice4','iuprice5','isaleprice5','iuprice6','isaleprice6','iuprice7','isaleprice7','iuprice8','isaleprice8','iuprice9','isaleprice9','iuprice10','cexch_name','isaleprice10','cinvname','cinvaddcode','cinvstd','iinvsprice','iinvncost','iinvscost','cinvccode','cinvcname','ccomunitcode','ccomunitname','iid','cbodymemo','cdefine22','cdefine23','cdefine24','cdefine25','cdefine26','cdefine27','cdefine28','cdefine29','cdefine30','cdefine31','cdefine32','cdefine33','cdefine34','cdefine35','cdefine36','cdefine37','cinvdefine1','cinvdefine2','cinvdefine3','cinvdefine4','cinvdefine5','cinvdefine6','cinvdefine7','cinvdefine8','cinvdefine9','cinvdefine10','cinvdefine11','cinvdefine12','cinvdefine13','cinvdefine14','cinvdefine15','cinvdefine16','cdefine1','cdefine2','cdefine3','cdefine4','cdefine5','cdefine6','cdefine7','cdefine8','cdefine9','cdefine10','cdefine11','cdefine12','cdefine13','cdefine14','cdefine15','cdefine16','bsales','fminquantity','iverifystate','ireturncount','iswfcontrolled','ufts','cmodifier','dmoddate','dcreatesystime','dverifysystime','dmodifysystime']
      tid?:any
ddate?:any
ccode?:any
cmaker?:any
cpersoncode?:any
cpersonname?:any
cmainmemo?:any
cverifier?:any
dverifydate?:any
drdate?:any
cdepcode?:any
cdepname?:any
autoid?:any
id?:any
dstartdate?:any
cfree1?:any
cfree2?:any
cfree3?:any
cfree4?:any
cfree5?:any
cfree6?:any
cfree7?:any
cfree8?:any
cfree9?:any
cfree10?:any
denddate?:any
operationtype?:any
ipriceid?:any
cinvcode?:any
iuprice1?:any
isaleprice1?:any
iuprice2?:any
isaleprice2?:any
iuprice3?:any
isaleprice3?:any
iuprice4?:any
isaleprice4?:any
iuprice5?:any
isaleprice5?:any
iuprice6?:any
isaleprice6?:any
iuprice7?:any
isaleprice7?:any
iuprice8?:any
isaleprice8?:any
iuprice9?:any
isaleprice9?:any
iuprice10?:any
cexch_name?:any
isaleprice10?:any
cinvname?:any
cinvaddcode?:any
cinvstd?:any
iinvsprice?:any
iinvncost?:any
iinvscost?:any
cinvccode?:any
cinvcname?:any
ccomunitcode?:any
ccomunitname?:any
iid?:any
cbodymemo?:any
cdefine22?:any
cdefine23?:any
cdefine24?:any
cdefine25?:any
cdefine26?:any
cdefine27?:any
cdefine28?:any
cdefine29?:any
cdefine30?:any
cdefine31?:any
cdefine32?:any
cdefine33?:any
cdefine34?:any
cdefine35?:any
cdefine36?:any
cdefine37?:any
cinvdefine1?:any
cinvdefine2?:any
cinvdefine3?:any
cinvdefine4?:any
cinvdefine5?:any
cinvdefine6?:any
cinvdefine7?:any
cinvdefine8?:any
cinvdefine9?:any
cinvdefine10?:any
cinvdefine11?:any
cinvdefine12?:any
cinvdefine13?:any
cinvdefine14?:any
cinvdefine15?:any
cinvdefine16?:any
cdefine1?:any
cdefine2?:any
cdefine3?:any
cdefine4?:any
cdefine5?:any
cdefine6?:any
cdefine7?:any
cdefine8?:any
cdefine9?:any
cdefine10?:any
cdefine11?:any
cdefine12?:any
cdefine13?:any
cdefine14?:any
cdefine15?:any
cdefine16?:any
bsales?:any
fminquantity?:any
iverifystate?:any
ireturncount?:any
iswfcontrolled?:any
ufts?:any
cmodifier?:any
dmoddate?:any
dcreatesystime?:any
dverifysystime?:any
dmodifysystime?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }