export default class t_SdOrderDeliveryDetail {
      columnArr=['cSdOrderNo','iInterID','iBomAutoID','iEntryID','cCode','cLevelInfo','cLevelPath','cInvCode','cInvCodeFull','cProductNo','cSubInvCode','cSubInvCodeFull','cSubInvName','cSubInvStd','cSubComUnitCode','iSeqID','iLevel','FQty','FAddupQty','iParentQty','iBomParentQty','iBomSubQty','iInvQty','iForeInQty','iPlanQty','iDispatchedQty','dForeInDate','dReDeliveryDate','iAltSeqID','dValidDate','dInvalidDate','iRelateLT','iAddupLT','cType','cItemType','cSubRelate','cBomType','cInvName','cInvStd','bSelf','cComUnitCode','cNote','cItemClsNo','iBatQty','iScrapt','cSupplyMode','cSelect','iPercent','iRetPercent','iRetOffsetLT','cUtterType','cEco','cVersion','cEcoNote','cDeductType','FBomStatus','cRouteNo','bMPS','bDetail','cCheckError','cGetItemType','cWhCode','cScraptExp','iCurQty']
      cSdOrderNo?:any
iInterID?:any
iBomAutoID?:any
iEntryID?:any
cCode?:any
cLevelInfo?:any
cLevelPath?:any
cInvCode?:any
cInvCodeFull?:any
cProductNo?:any
cSubInvCode?:any
cSubInvCodeFull?:any
cSubInvName?:any
cSubInvStd?:any
cSubComUnitCode?:any
iSeqID?:any
iLevel?:any
FQty?:any
FAddupQty?:any
iParentQty?:any
iBomParentQty?:any
iBomSubQty?:any
iInvQty?:any
iForeInQty?:any
iPlanQty?:any
iDispatchedQty?:any
dForeInDate?:any
dReDeliveryDate?:any
iAltSeqID?:any
dValidDate?:any
dInvalidDate?:any
iRelateLT?:any
iAddupLT?:any
cType?:any
cItemType?:any
cSubRelate?:any
cBomType?:any
cInvName?:any
cInvStd?:any
bSelf?:any
cComUnitCode?:any
cNote?:any
cItemClsNo?:any
iBatQty?:any
iScrapt?:any
cSupplyMode?:any
cSelect?:any
iPercent?:any
iRetPercent?:any
iRetOffsetLT?:any
cUtterType?:any
cEco?:any
cVersion?:any
cEcoNote?:any
cDeductType?:any
FBomStatus?:any
cRouteNo?:any
bMPS?:any
bDetail?:any
cCheckError?:any
cGetItemType?:any
cWhCode?:any
cScraptExp?:any
iCurQty?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }