export default class t_SdPackage {
      columnArr=['iInterID','cWcNo','cInvCode','cZCNum','iBerBZQty','iBZQty','iCurQty','iDifQty','iCanBZQty','dDeliveryDate','cMiNo','dDate','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cOperator','dOpeDate','cSdOrderNoAll','iBZOrderNum','iWoSeqID','bWorkOrder','cWoNo','dBegDate','dEndDate','iForeInQty','iCapacity','cResourceNo']
      iInterID?:any
cWcNo?:any
cInvCode?:any
cZCNum?:any
iBerBZQty?:any
iBZQty?:any
iCurQty?:any
iDifQty?:any
iCanBZQty?:any
dDeliveryDate?:any
cMiNo?:any
dDate?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cOperator?:any
dOpeDate?:any
cSdOrderNoAll?:any
iBZOrderNum?:any
iWoSeqID?:any
bWorkOrder?:any
cWoNo?:any
dBegDate?:any
dEndDate?:any
iForeInQty?:any
iCapacity?:any
cResourceNo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }