export default class t_SdDispatchEntry {
      columnArr=['iLineID','DLID','cDLCode','cCode','cWhCode','iItemID','cInvCode','iQuantity','iNum','iQuotedPrice','iUnitPrice','iTaxUnitPrice','iMoney','iTax','iSum','iDisCount','iNatUnitPrice','iNatTaxPrice','iNatMoney','iNatTax','iNatSum','iNatDisCount','iSettleNum','iSettleQuantity','cBatchNo','bSettleAll','cNote','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','iTB','TBQuantity','TBNum','cSdOrderNo','iSdLineID','iDLsID','KL','KL2','cInvName','cInvStd','cUnitCode','iTaxRate','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','fOutQuantity','fOutNum','iInvExchRate','iRetQuantity','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','bQANeedCheck','iQAQuantity','iQANum','cCustItemNo','fsumsignquantity','fsumsignnum','cvmivencode','iexchsum','imoneysum','frettbquantity','fretsum','cPosition','cLineCloser','iRetNum','cbCloseDate','fSaleCost','fSalePrice','cMiNo','WBID','WBPID','dDeliveryDate','cItemSize7','cFxNo','cSaleType','cProMaterialNote','cComUnitCode','cItemClsNo','iXSQty','iJSQty','iZXS','cQSXH','cZZXH']
      iLineID?:any
DLID?:any
cDLCode?:any
cCode?:any
cWhCode?:any
iItemID?:any
cInvCode?:any
iQuantity?:any
iNum?:any
iQuotedPrice?:any
iUnitPrice?:any
iTaxUnitPrice?:any
iMoney?:any
iTax?:any
iSum?:any
iDisCount?:any
iNatUnitPrice?:any
iNatTaxPrice?:any
iNatMoney?:any
iNatTax?:any
iNatSum?:any
iNatDisCount?:any
iSettleNum?:any
iSettleQuantity?:any
cBatchNo?:any
bSettleAll?:any
cNote?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
iTB?:any
TBQuantity?:any
TBNum?:any
cSdOrderNo?:any
iSdLineID?:any
iDLsID?:any
KL?:any
KL2?:any
cInvName?:any
cInvStd?:any
cUnitCode?:any
iTaxRate?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
fOutQuantity?:any
fOutNum?:any
iInvExchRate?:any
iRetQuantity?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
bQANeedCheck?:any
iQAQuantity?:any
iQANum?:any
cCustItemNo?:any
fsumsignquantity?:any
fsumsignnum?:any
cvmivencode?:any
iexchsum?:any
imoneysum?:any
frettbquantity?:any
fretsum?:any
cPosition?:any
cLineCloser?:any
iRetNum?:any
cbCloseDate?:any
fSaleCost?:any
fSalePrice?:any
cMiNo?:any
WBID?:any
WBPID?:any
dDeliveryDate?:any
cItemSize7?:any
cFxNo?:any
cSaleType?:any
cProMaterialNote?:any
cComUnitCode?:any
cItemClsNo?:any
iXSQty?:any
iJSQty?:any
iZXS?:any
cQSXH?:any
cZZXH?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }