export default class t_SdQuotationEntry {
      columnArr=['iInterID','iLineID','cQuotationNo','iItemID','cInvCode','cInvName','cInvStd','cUnitCode','cInvClass','iInvExchRate','cCustItemNo','iReqQty','iNum','dBegDate','dEndDate','iTaxRate','iQuotedPrice','iUnitPrice','iTaxUnitPrice','iMoney','iTax','iSum','iDiscount','iNatUnitPrice','iNatTaxPrice','iNatMoney','iNatTax','iNatSum','iNatDisCount','KL','KL2','iProQty','cParentItem','cNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','cColor','cLineCloser','cbCloseDate']
      iInterID?:any
iLineID?:any
cQuotationNo?:any
iItemID?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cUnitCode?:any
cInvClass?:any
iInvExchRate?:any
cCustItemNo?:any
iReqQty?:any
iNum?:any
dBegDate?:any
dEndDate?:any
iTaxRate?:any
iQuotedPrice?:any
iUnitPrice?:any
iTaxUnitPrice?:any
iMoney?:any
iTax?:any
iSum?:any
iDiscount?:any
iNatUnitPrice?:any
iNatTaxPrice?:any
iNatMoney?:any
iNatTax?:any
iNatSum?:any
iNatDisCount?:any
KL?:any
KL2?:any
iProQty?:any
cParentItem?:any
cNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
cColor?:any
cLineCloser?:any
cbCloseDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }