export default class t_SdCustShipping {
      columnArr=['iInterID','hselect','cCustNo','cCustName','iDispatchDays','iShipDays','iFHDays','iManuDays','fFHVolume','fVolumeAll','fWeightAll','iQuantityAll','fVolumeWeek1','fWeightWeek1','iQuantityWeek1','fVolumeWeek2','fWeightWeek2','iQuantityWeek2','fVolumeWeek3','fWeightWeek3','iQuantityWeek3','fVolumeWeek4','fWeightWeek4','iQuantityWeek4','fVolumeWeek5','fWeightWeek5','iQuantityWeek5','fVolumeWeek6','fWeightWeek6','iQuantityWeek6','fVolumeWeek7','fWeightWeek7','iQuantityWeek7','fVolumeWeek8','fWeightWeek8','iQuantityWeek8','fVolumeWeek9','fWeightWeek9','iQuantityWeek9','fVolumeWeek10','fWeightWeek10','iQuantityWeek10','fVolumeWeek11','fWeightWeek11','iQuantityWeek11','fVolumeWeek12','fWeightWeek12','iQuantityWeek12','fVolumeWeek13','fWeightWeek13','iQuantityWeek13','fVolumeWeek14','fWeightWeek14','iQuantityWeek14','fVolumeWeek15','fWeightWeek15','iQuantityWeek15','fVolumeWeek16','fWeightWeek16','iQuantityWeek16','fVolumeWeek17','fWeightWeek17','iQuantityWeek17','fVolumeWeek18','fWeightWeek18','iQuantityWeek18','fVolumeWeek19','fWeightWeek19','iQuantityWeek19','fVolumeWeek20','fWeightWeek20','iQuantityWeek20','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','iFHCircle']
      iInterID?:any
hselect?:any
cCustNo?:any
cCustName?:any
iDispatchDays?:any
iShipDays?:any
iFHDays?:any
iManuDays?:any
fFHVolume?:any
fVolumeAll?:any
fWeightAll?:any
iQuantityAll?:any
fVolumeWeek1?:any
fWeightWeek1?:any
iQuantityWeek1?:any
fVolumeWeek2?:any
fWeightWeek2?:any
iQuantityWeek2?:any
fVolumeWeek3?:any
fWeightWeek3?:any
iQuantityWeek3?:any
fVolumeWeek4?:any
fWeightWeek4?:any
iQuantityWeek4?:any
fVolumeWeek5?:any
fWeightWeek5?:any
iQuantityWeek5?:any
fVolumeWeek6?:any
fWeightWeek6?:any
iQuantityWeek6?:any
fVolumeWeek7?:any
fWeightWeek7?:any
iQuantityWeek7?:any
fVolumeWeek8?:any
fWeightWeek8?:any
iQuantityWeek8?:any
fVolumeWeek9?:any
fWeightWeek9?:any
iQuantityWeek9?:any
fVolumeWeek10?:any
fWeightWeek10?:any
iQuantityWeek10?:any
fVolumeWeek11?:any
fWeightWeek11?:any
iQuantityWeek11?:any
fVolumeWeek12?:any
fWeightWeek12?:any
iQuantityWeek12?:any
fVolumeWeek13?:any
fWeightWeek13?:any
iQuantityWeek13?:any
fVolumeWeek14?:any
fWeightWeek14?:any
iQuantityWeek14?:any
fVolumeWeek15?:any
fWeightWeek15?:any
iQuantityWeek15?:any
fVolumeWeek16?:any
fWeightWeek16?:any
iQuantityWeek16?:any
fVolumeWeek17?:any
fWeightWeek17?:any
iQuantityWeek17?:any
fVolumeWeek18?:any
fWeightWeek18?:any
iQuantityWeek18?:any
fVolumeWeek19?:any
fWeightWeek19?:any
iQuantityWeek19?:any
fVolumeWeek20?:any
fWeightWeek20?:any
iQuantityWeek20?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
iFHCircle?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }