export default class t_VenItemPrice {
      columnArr=['iInterID','cVenCode','cInvCode','dEnableDate','dDisableDate','cExch_Name','bSales','iLowerLimit','cSupplyType','bTaxCost','cTermCode','iUnitPrice','iTaxRate','iTaxUnitPrice','iVJPInterID','iVJPID','cVJPCode','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10']
      iInterID?:any
cVenCode?:any
cInvCode?:any
dEnableDate?:any
dDisableDate?:any
cExch_Name?:any
bSales?:any
iLowerLimit?:any
cSupplyType?:any
bTaxCost?:any
cTermCode?:any
iUnitPrice?:any
iTaxRate?:any
iTaxUnitPrice?:any
iVJPInterID?:any
iVJPID?:any
cVJPCode?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }