export default class t_WHItem {
      columnArr=['cWhNo','iItemID','cInvCode','cSeat','cSeatName','cBatchNo','iSoType','iSoDid','iQty','iNum','iOutQty','iOutNum','iInQty','iInNum','cFree1','cFree2','cFree3','cFree4','cFree5','dMadeDate','dDisableDate','dLastCheckDate','dLastDetectDate','dLastModifyDate','cWhName','cInvName','cInvStd','cComUnitCode','cComUnitName','cAssUnit','cAssUnitName','dLastoutDate','cNote','cDistinctNo','cMiNo','iAmount','iPlanPrice','iprice','cSerialNo','iSafeInv','cVersionNo']
      cWhNo?:any
iItemID?:any
cInvCode?:any
cSeat?:any
cSeatName?:any
cBatchNo?:any
iSoType?:any
iSoDid?:any
iQty?:any
iNum?:any
iOutQty?:any
iOutNum?:any
iInQty?:any
iInNum?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
dMadeDate?:any
dDisableDate?:any
dLastCheckDate?:any
dLastDetectDate?:any
dLastModifyDate?:any
cWhName?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cComUnitName?:any
cAssUnit?:any
cAssUnitName?:any
dLastoutDate?:any
cNote?:any
cDistinctNo?:any
cMiNo?:any
iAmount?:any
iPlanPrice?:any
iprice?:any
cSerialNo?:any
iSafeInv?:any
cVersionNo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }