export default class t_WorkOrderGuide {
      columnArr=['iInterID','cWoNo','cCustNo','cCustName','cClsNo','cResourceNo','cColor','cInk','ERPNO','cInvCode','cInvName','cInvStd','fGrossWeight','fNetWeight','cMakeup1','cMakeup2','cMakeup3','cMakeup4','cMakeup5','cMakeup6','cMakeup7','cOpenPaper1','cOpenPaper2','cOpenPaper3','cOpenPaper4','cOpenPaper5','cOpenPaper6','cOpenPaper7','cPaperType','cOpenType','iMakeupPicture','cNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cMakeup1_2','cMakeup2_2','cMakeup3_2','cMakeup4_2','cMakeup5_2','cMakeup6_2','cMakeup7_2','cMakeupNote','cOpenPaperNote','FileNo','cBanType']
      iInterID?:any
cWoNo?:any
cCustNo?:any
cCustName?:any
cClsNo?:any
cResourceNo?:any
cColor?:any
cInk?:any
ERPNO?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
fGrossWeight?:any
fNetWeight?:any
cMakeup1?:any
cMakeup2?:any
cMakeup3?:any
cMakeup4?:any
cMakeup5?:any
cMakeup6?:any
cMakeup7?:any
cOpenPaper1?:any
cOpenPaper2?:any
cOpenPaper3?:any
cOpenPaper4?:any
cOpenPaper5?:any
cOpenPaper6?:any
cOpenPaper7?:any
cPaperType?:any
cOpenType?:any
iMakeupPicture?:any
cNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cMakeup1_2?:any
cMakeup2_2?:any
cMakeup3_2?:any
cMakeup4_2?:any
cMakeup5_2?:any
cMakeup6_2?:any
cMakeup7_2?:any
cMakeupNote?:any
cOpenPaperNote?:any
FileNo?:any
cBanType?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }