export default class t_WorkRouteImport {
      columnArr=['hselect','iInterID','iProcessID','iResourceAbilityID','iEntryID','cCode','cInvCode','cInvName','cInvStd','cComUnitCode','cComUnitName','cRouteNo','cBegWcNo','cRouteType','cRoutetypeName','dValidDate','cIsDefault','dInvalidDate','iYieldage','cStatus','cStatusName','cChecker','cOperator','cVersion','iEvenLT','iEvenLot','dOpeDate','dCheckDate','cDefine1','cDefine2','cDefine3','cDefine4','iWoSeqID','cWcNo','cTechNo','cSeqNote','cParellelType','cParallelNo','iSeqRatio','iNextSeqID','cKeyBrantch','cCompSeq','cIsReport','cMoveType','iMoveInterTime','iMoveInterQty','iMoveTime','iSeqPreTime','iSeqPostTime','cDefine22','cDefine23','cDefine24','cDefine25','iItemID','iResGroupNo','iResGroupPriority','cSelected','iResourceID','cResourceNo','cResourceName','cViceResource1No','iBatchQty','iBatchWorkTime','iBatchInterTime','iResPreTime','cResPreTimeExp','iCapacity','cCapacityExp','iResPostTime','cResPostTimeExp','iProcessPassRate','iEfficiency','iHoursPd','iWorkQtyPd','iWorkersPd','iDevCountPd','iLaborTime','iLeadTime','FResChaValue1ID','FResChaValue2ID','FResChaValue3ID','FResChaValue4ID','FResChaValue5ID','FResChaValue6ID','FResChaValue7ID','FResChaValue8ID','FResChaValue9ID','FResChaValue10ID','FResChaValue11ID','FResChaValue12ID','FResChaValue1Cyc','FResChaValue2Cyc','FResChaValue3Cyc','cResourceNote','cDefine22d','cDefine23d','cDefine24d','cIsInfinityAbility','cWorkType','cNote','cEntryNote','cDefine25d','FResChaValue4Cyc','FResChaValue5Cyc','FResChaValue6Cyc','FResChaValue7Cyc','FResChaValue8Cyc','FResChaValue9Cyc','FResChaValue10Cyc','FResChaValue11Cyc','FResChaValue12Cyc','cViceResource2No','cViceResource3No','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cDefine26d','cDefine27d','cDefine28d','cDefine29d','cDefine30d','cEnterprise','cFile','cLabel','cCheckOut','cLicence','cLinear','cWGroupCode','fGrossWeight','fNetWeight','cVGroupCode','fVolume','flength','fWidth','fHeight','fDiameter','fMinDiameter','fQtyPerBox','fWeightPerM','fPicQtyPer','iInvSCost','iInvSPrice','cMaterial','cColor','cItemClsNo','bEndReport','iChangeTime','iResPreTimeRes','iScrapt','cScraptExp','cDevCountPdExp','iTechValue','fOutRatio','iCompHourPercent','iDevCountPdMax','cPhotoPosition','cDemoPosition','cSeqReq','cResourceSelectExp','iCappacityHr','iCappacityHrExp','cResParam1','cResParam2','cResParam3','cResParam4','cResParam5','cResParam6','cResParam7','cResParam8','cResParam9','cResParam10','cResParam11','cResParam12','cHostName','cSyncStatus','dImportDate']
      hselect?:any
iInterID?:any
iProcessID?:any
iResourceAbilityID?:any
iEntryID?:any
cCode?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cComUnitName?:any
cRouteNo?:any
cBegWcNo?:any
cRouteType?:any
cRoutetypeName?:any
dValidDate?:any
cIsDefault?:any
dInvalidDate?:any
iYieldage?:any
cStatus?:any
cStatusName?:any
cChecker?:any
cOperator?:any
cVersion?:any
iEvenLT?:any
iEvenLot?:any
dOpeDate?:any
dCheckDate?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
iWoSeqID?:any
cWcNo?:any
cTechNo?:any
cSeqNote?:any
cParellelType?:any
cParallelNo?:any
iSeqRatio?:any
iNextSeqID?:any
cKeyBrantch?:any
cCompSeq?:any
cIsReport?:any
cMoveType?:any
iMoveInterTime?:any
iMoveInterQty?:any
iMoveTime?:any
iSeqPreTime?:any
iSeqPostTime?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
iItemID?:any
iResGroupNo?:any
iResGroupPriority?:any
cSelected?:any
iResourceID?:any
cResourceNo?:any
cResourceName?:any
cViceResource1No?:any
iBatchQty?:any
iBatchWorkTime?:any
iBatchInterTime?:any
iResPreTime?:any
cResPreTimeExp?:any
iCapacity?:any
cCapacityExp?:any
iResPostTime?:any
cResPostTimeExp?:any
iProcessPassRate?:any
iEfficiency?:any
iHoursPd?:any
iWorkQtyPd?:any
iWorkersPd?:any
iDevCountPd?:any
iLaborTime?:any
iLeadTime?:any
FResChaValue1ID?:any
FResChaValue2ID?:any
FResChaValue3ID?:any
FResChaValue4ID?:any
FResChaValue5ID?:any
FResChaValue6ID?:any
FResChaValue7ID?:any
FResChaValue8ID?:any
FResChaValue9ID?:any
FResChaValue10ID?:any
FResChaValue11ID?:any
FResChaValue12ID?:any
FResChaValue1Cyc?:any
FResChaValue2Cyc?:any
FResChaValue3Cyc?:any
cResourceNote?:any
cDefine22d?:any
cDefine23d?:any
cDefine24d?:any
cIsInfinityAbility?:any
cWorkType?:any
cNote?:any
cEntryNote?:any
cDefine25d?:any
FResChaValue4Cyc?:any
FResChaValue5Cyc?:any
FResChaValue6Cyc?:any
FResChaValue7Cyc?:any
FResChaValue8Cyc?:any
FResChaValue9Cyc?:any
FResChaValue10Cyc?:any
FResChaValue11Cyc?:any
FResChaValue12Cyc?:any
cViceResource2No?:any
cViceResource3No?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cDefine26d?:any
cDefine27d?:any
cDefine28d?:any
cDefine29d?:any
cDefine30d?:any
cEnterprise?:any
cFile?:any
cLabel?:any
cCheckOut?:any
cLicence?:any
cLinear?:any
cWGroupCode?:any
fGrossWeight?:any
fNetWeight?:any
cVGroupCode?:any
fVolume?:any
flength?:any
fWidth?:any
fHeight?:any
fDiameter?:any
fMinDiameter?:any
fQtyPerBox?:any
fWeightPerM?:any
fPicQtyPer?:any
iInvSCost?:any
iInvSPrice?:any
cMaterial?:any
cColor?:any
cItemClsNo?:any
bEndReport?:any
iChangeTime?:any
iResPreTimeRes?:any
iScrapt?:any
cScraptExp?:any
cDevCountPdExp?:any
iTechValue?:any
fOutRatio?:any
iCompHourPercent?:any
iDevCountPdMax?:any
cPhotoPosition?:any
cDemoPosition?:any
cSeqReq?:any
cResourceSelectExp?:any
iCappacityHr?:any
iCappacityHrExp?:any
cResParam1?:any
cResParam2?:any
cResParam3?:any
cResParam4?:any
cResParam5?:any
cResParam6?:any
cResParam7?:any
cResParam8?:any
cResParam9?:any
cResParam10?:any
cResParam11?:any
cResParam12?:any
cHostName?:any
cSyncStatus?:any
dImportDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }