export default class t_WorkOrderResource_Deleted {
      columnArr=['iAutoID','dDeleteDate','cBatchNo','iInterID','iProcessID','iResProcessID','iResourceAbilityID','cWoNo','iItemID','cInvCode','iWoSeqID','cTechNo','cSeqNote','iResGroupNo','iResGroupPriority','cSelected','iResourceID','cResourceNo','cResourceName','iResReqQty','dResBegDate','dResEndDate','iResRationHour','iResActQty','dResActBegDate','dResActEndDate','iResActRationHour','iResDispatchedQty','iViceResource1ID','cViceResource1No','iViceResource2ID','cViceResource2No','iViceResource3ID','cViceResource3No','cWorkType','iBatchQty','iBatchWorkTime','iBatchInterTime','iResPreTime','cResPreTimeExp','iCapacity','cCapacityExp','iResPostTime','cResPostTimeExp','iCycTime','iProcessPassRate','iEfficiency','iHoursPd','iWorkQtyPd','iWorkersPd','iDevCountPd','iLaborTime','iLeadTime','FResChaValue1ID','FResChaValue2ID','FResChaValue3ID','FResChaValue4ID','FResChaValue5ID','FResChaValue6ID','FResChaValue7ID','FResChaValue8ID','FResChaValue9ID','FResChaValue10ID','FResChaValue11ID','FResChaValue12ID','FResChaValue1Cyc','FResChaValue2Cyc','FResChaValue3Cyc','FResChaValue4Cyc','FResChaValue5Cyc','FResChaValue6Cyc','FResChaValue7Cyc','FResChaValue8Cyc','FResChaValue9Cyc','FResChaValue10Cyc','FResChaValue11Cyc','FResChaValue12Cyc','cResourceNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cIsInfinityAbility','iResSumCompQty']
      iAutoID?:any
dDeleteDate?:any
cBatchNo?:any
iInterID?:any
iProcessID?:any
iResProcessID?:any
iResourceAbilityID?:any
cWoNo?:any
iItemID?:any
cInvCode?:any
iWoSeqID?:any
cTechNo?:any
cSeqNote?:any
iResGroupNo?:any
iResGroupPriority?:any
cSelected?:any
iResourceID?:any
cResourceNo?:any
cResourceName?:any
iResReqQty?:any
dResBegDate?:any
dResEndDate?:any
iResRationHour?:any
iResActQty?:any
dResActBegDate?:any
dResActEndDate?:any
iResActRationHour?:any
iResDispatchedQty?:any
iViceResource1ID?:any
cViceResource1No?:any
iViceResource2ID?:any
cViceResource2No?:any
iViceResource3ID?:any
cViceResource3No?:any
cWorkType?:any
iBatchQty?:any
iBatchWorkTime?:any
iBatchInterTime?:any
iResPreTime?:any
cResPreTimeExp?:any
iCapacity?:any
cCapacityExp?:any
iResPostTime?:any
cResPostTimeExp?:any
iCycTime?:any
iProcessPassRate?:any
iEfficiency?:any
iHoursPd?:any
iWorkQtyPd?:any
iWorkersPd?:any
iDevCountPd?:any
iLaborTime?:any
iLeadTime?:any
FResChaValue1ID?:any
FResChaValue2ID?:any
FResChaValue3ID?:any
FResChaValue4ID?:any
FResChaValue5ID?:any
FResChaValue6ID?:any
FResChaValue7ID?:any
FResChaValue8ID?:any
FResChaValue9ID?:any
FResChaValue10ID?:any
FResChaValue11ID?:any
FResChaValue12ID?:any
FResChaValue1Cyc?:any
FResChaValue2Cyc?:any
FResChaValue3Cyc?:any
FResChaValue4Cyc?:any
FResChaValue5Cyc?:any
FResChaValue6Cyc?:any
FResChaValue7Cyc?:any
FResChaValue8Cyc?:any
FResChaValue9Cyc?:any
FResChaValue10Cyc?:any
FResChaValue11Cyc?:any
FResChaValue12Cyc?:any
cResourceNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cIsInfinityAbility?:any
iResSumCompQty?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }