export default class t_WorkOrderResource {
      columnArr=['iInterID','iProcessID','iResProcessID','iResourceAbilityID','cWoNo','iItemID','cInvCode','iWoSeqID','cTechNo','cSeqNote','iResGroupNo','iResGroupPriority','cSelected','iResourceID','cResourceNo','cResourceName','iResReqQty','dResBegDate','dResEndDate','iResRationHour','iResActQty','dResActBegDate','dResActEndDate','iResActRationHour','iResDispatchedQty','iViceResource1ID','cViceResource1No','iViceResource2ID','cViceResource2No','iViceResource3ID','cViceResource3No','cWorkType','iBatchQty','iBatchWorkTime','iBatchInterTime','iResPreTime','cResPreTimeExp','iCapacity','cCapacityExp','iResPostTime','cResPostTimeExp','iCycTime','iProcessPassRate','iEfficiency','iHoursPd','iWorkQtyPd','iWorkersPd','iDevCountPd','iLaborTime','iLeadTime','FResChaValue1ID','FResChaValue2ID','FResChaValue3ID','FResChaValue4ID','FResChaValue5ID','FResChaValue6ID','FResChaValue7ID','FResChaValue8ID','FResChaValue9ID','FResChaValue10ID','FResChaValue11ID','FResChaValue12ID','FResChaValue1Cyc','FResChaValue2Cyc','FResChaValue3Cyc','FResChaValue4Cyc','FResChaValue5Cyc','FResChaValue6Cyc','FResChaValue7Cyc','FResChaValue8Cyc','FResChaValue9Cyc','FResChaValue10Cyc','FResChaValue11Cyc','FResChaValue12Cyc','cResourceNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cIsInfinityAbility','iResSumCompQty','iResPreTimeOld','iScanResourceID','iSumBadQty','cResourceNoOld','dResReplaceDate','cTeamResourceNo','cLearnCurvesNo','cResourceSelectExp','dFirstResBegDate','dFirstResEndDate','dResCanBegDate','iResWaitTime','iPriorityRes','cShift','cVenNo','iPlanedQty','cReqCode','iReqLineID','iFirstResRationHour','iFirstResPreTime','cSchSNType','iSchSN','dResCanEndDate','iPriorityResLast','iCurDispatchQty','iShiftType1A','iShiftType1B','iShiftType1C','iShiftType2A','iShiftType2B','iShiftType2C','iShiftType3A','iShiftType3B','iShiftType3C','dLastDispatchDate','iResReqQtyNo','iResRationHourNo','cResParam1','cResParam2','cResParam3','cResParam4','cResParam5','cResParam6','cResParam7','cResParam8','cResParam9','cResParam10','cResParam11','cResParam12','iCappacityHr','iCappacityHrExp','cBatchQtyExp','iLaborHour','iBatchQtyBase','iBatchQtyMul','iBatchQtyDiv','iInQty','iWipQty','iResReqNum','iResActNum','iResDispatchedNum','iCurDispatchNum','cItemGroup']
      iInterID?:any
iProcessID?:any
iResProcessID?:any
iResourceAbilityID?:any
cWoNo?:any
iItemID?:any
cInvCode?:any
iWoSeqID?:any
cTechNo?:any
cSeqNote?:any
iResGroupNo?:any
iResGroupPriority?:any
cSelected?:any
iResourceID?:any
cResourceNo?:any
cResourceName?:any
iResReqQty?:any
dResBegDate?:any
dResEndDate?:any
iResRationHour?:any
iResActQty?:any
dResActBegDate?:any
dResActEndDate?:any
iResActRationHour?:any
iResDispatchedQty?:any
iViceResource1ID?:any
cViceResource1No?:any
iViceResource2ID?:any
cViceResource2No?:any
iViceResource3ID?:any
cViceResource3No?:any
cWorkType?:any
iBatchQty?:any
iBatchWorkTime?:any
iBatchInterTime?:any
iResPreTime?:any
cResPreTimeExp?:any
iCapacity?:any
cCapacityExp?:any
iResPostTime?:any
cResPostTimeExp?:any
iCycTime?:any
iProcessPassRate?:any
iEfficiency?:any
iHoursPd?:any
iWorkQtyPd?:any
iWorkersPd?:any
iDevCountPd?:any
iLaborTime?:any
iLeadTime?:any
FResChaValue1ID?:any
FResChaValue2ID?:any
FResChaValue3ID?:any
FResChaValue4ID?:any
FResChaValue5ID?:any
FResChaValue6ID?:any
FResChaValue7ID?:any
FResChaValue8ID?:any
FResChaValue9ID?:any
FResChaValue10ID?:any
FResChaValue11ID?:any
FResChaValue12ID?:any
FResChaValue1Cyc?:any
FResChaValue2Cyc?:any
FResChaValue3Cyc?:any
FResChaValue4Cyc?:any
FResChaValue5Cyc?:any
FResChaValue6Cyc?:any
FResChaValue7Cyc?:any
FResChaValue8Cyc?:any
FResChaValue9Cyc?:any
FResChaValue10Cyc?:any
FResChaValue11Cyc?:any
FResChaValue12Cyc?:any
cResourceNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cIsInfinityAbility?:any
iResSumCompQty?:any
iResPreTimeOld?:any
iScanResourceID?:any
iSumBadQty?:any
cResourceNoOld?:any
dResReplaceDate?:any
cTeamResourceNo?:any
cLearnCurvesNo?:any
cResourceSelectExp?:any
dFirstResBegDate?:any
dFirstResEndDate?:any
dResCanBegDate?:any
iResWaitTime?:any
iPriorityRes?:any
cShift?:any
cVenNo?:any
iPlanedQty?:any
cReqCode?:any
iReqLineID?:any
iFirstResRationHour?:any
iFirstResPreTime?:any
cSchSNType?:any
iSchSN?:any
dResCanEndDate?:any
iPriorityResLast?:any
iCurDispatchQty?:any
iShiftType1A?:any
iShiftType1B?:any
iShiftType1C?:any
iShiftType2A?:any
iShiftType2B?:any
iShiftType2C?:any
iShiftType3A?:any
iShiftType3B?:any
iShiftType3C?:any
dLastDispatchDate?:any
iResReqQtyNo?:any
iResRationHourNo?:any
cResParam1?:any
cResParam2?:any
cResParam3?:any
cResParam4?:any
cResParam5?:any
cResParam6?:any
cResParam7?:any
cResParam8?:any
cResParam9?:any
cResParam10?:any
cResParam11?:any
cResParam12?:any
iCappacityHr?:any
iCappacityHrExp?:any
cBatchQtyExp?:any
iLaborHour?:any
iBatchQtyBase?:any
iBatchQtyMul?:any
iBatchQtyDiv?:any
iInQty?:any
iWipQty?:any
iResReqNum?:any
iResActNum?:any
iResDispatchedNum?:any
iCurDispatchNum?:any
cItemGroup?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }