export default class t_WorkRouteImportTemp {
      columnArr=['iInterID','iProcessID','cResourceNote','cCode','iResourceAbilityID','cInvCode','cResourceNo','cResourceName','iCapacity','iCapacity2','cDefine35','cViceResource1No','cViceResource2No','iWoSeqID','cTechNo','cWcNo','iNextSeqID','iBatchQty','cWorkType','FResChaValue1ID','FResChaValue1Cyc','FResChaValue4ID','FResChaValue4Cyc','FResChaValue5ID','FResChaValue5Cyc','FResChaValue6ID','FResChaValue6Cyc','iResPreTime','iSeqPreTime','iSeqPostTime','iMoveInterTime','iMoveInterQty','iMoveTime','cComUnitCode','cIsReport','iDevCountPd','iResGroupNo','iResGroupPriority','cSelected','iBatchInterTime','iResPostTime','iProcessPassRate','iEfficiency','cRouteNo','cRouteType','dValidDate','cIsDefault','dInvalidDate','iYieldage','cStatus','cOperator','cVersion','dOpeDate','dCheckDate','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cResParam1','cResParam2','cResParam3','cResParam4','cResParam5','cResParam6','cResParam7','cResParam8','cResParam9','cResParam10','cResParam11','cResParam12','cDefine31']
      iInterID?:any
iProcessID?:any
cResourceNote?:any
cCode?:any
iResourceAbilityID?:any
cInvCode?:any
cResourceNo?:any
cResourceName?:any
iCapacity?:any
iCapacity2?:any
cDefine35?:any
cViceResource1No?:any
cViceResource2No?:any
iWoSeqID?:any
cTechNo?:any
cWcNo?:any
iNextSeqID?:any
iBatchQty?:any
cWorkType?:any
FResChaValue1ID?:any
FResChaValue1Cyc?:any
FResChaValue4ID?:any
FResChaValue4Cyc?:any
FResChaValue5ID?:any
FResChaValue5Cyc?:any
FResChaValue6ID?:any
FResChaValue6Cyc?:any
iResPreTime?:any
iSeqPreTime?:any
iSeqPostTime?:any
iMoveInterTime?:any
iMoveInterQty?:any
iMoveTime?:any
cComUnitCode?:any
cIsReport?:any
iDevCountPd?:any
iResGroupNo?:any
iResGroupPriority?:any
cSelected?:any
iBatchInterTime?:any
iResPostTime?:any
iProcessPassRate?:any
iEfficiency?:any
cRouteNo?:any
cRouteType?:any
dValidDate?:any
cIsDefault?:any
dInvalidDate?:any
iYieldage?:any
cStatus?:any
cOperator?:any
cVersion?:any
dOpeDate?:any
dCheckDate?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cResParam1?:any
cResParam2?:any
cResParam3?:any
cResParam4?:any
cResParam5?:any
cResParam6?:any
cResParam7?:any
cResParam8?:any
cResParam9?:any
cResParam10?:any
cResParam11?:any
cResParam12?:any
cDefine31?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }