export default class t_WorkRouteEntry {
      columnArr=['iInterID','cCode','iEntryID','iProcessID','iItemID','cInvCode','iWoSeqID','iWoSeqID','cWcNo','cTechNo','cSeqNote','cParellelType','cParallelNo','iSeqRatio','iNextSeqID','cKeyBrantch','cCompSeq','cIsReport','cMoveType','iMoveInterTime','iMoveInterQty','iMoveTime','iSeqPreTime','iSeqPostTime','cWorkType','iBatchQty','iBatchWorkTime','iBatchInterTime','iResPreTime','cResPreTimeExp','iCapacity','cCapacityExp','iResPostTime','cResPostTimeExp','iProcessPassRate','iEfficiency','iHoursPd','iWorkQtyPd','iWorkersPd','iDevCountPd','iLaborTime','iLeadTime','cEntryNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','iScrapt','cScraptExp','cSeqReq','cDevCountPdExp','cNextSeqNote','dOpeDate','fOutRatio','cNextWcNo','iCompHourPercent','iDevCountPdMax','iTechValue','cPhotoPosition','cDemoPosition','cPreProcessItem','cPostProcessItem','X','Y']
      iInterID?:any
cCode?:any
iEntryID?:any
iProcessID?:any
iItemID?:any
cInvCode?:any
iWoSeqID?:any
iWoSeqID?:any
cWcNo?:any
cTechNo?:any
cSeqNote?:any
cParellelType?:any
cParallelNo?:any
iSeqRatio?:any
iNextSeqID?:any
cKeyBrantch?:any
cCompSeq?:any
cIsReport?:any
cMoveType?:any
iMoveInterTime?:any
iMoveInterQty?:any
iMoveTime?:any
iSeqPreTime?:any
iSeqPostTime?:any
cWorkType?:any
iBatchQty?:any
iBatchWorkTime?:any
iBatchInterTime?:any
iResPreTime?:any
cResPreTimeExp?:any
iCapacity?:any
cCapacityExp?:any
iResPostTime?:any
cResPostTimeExp?:any
iProcessPassRate?:any
iEfficiency?:any
iHoursPd?:any
iWorkQtyPd?:any
iWorkersPd?:any
iDevCountPd?:any
iLaborTime?:any
iLeadTime?:any
cEntryNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
iScrapt?:any
cScraptExp?:any
cSeqReq?:any
cDevCountPdExp?:any
cNextSeqNote?:any
dOpeDate?:any
fOutRatio?:any
cNextWcNo?:any
iCompHourPercent?:any
iDevCountPdMax?:any
iTechValue?:any
cPhotoPosition?:any
cDemoPosition?:any
cPreProcessItem?:any
cPostProcessItem?:any
X?:any
Y?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }