export default class t_WorkOrderResourceDayCap {
      columnArr=['iInterID','cResourceNo','cWcNo','iSchemeID','dDate1','iResRationHour1','iResCap1','iPer1','dDate2','iResRationHour2','iResCap2','iPer2','dDate3','iResRationHour3','iResCap3','iPer3','dDate4','iResRationHour4','iResCap4','iPer4','dDate5','iResRationHour5','iResCap5','iPer5','dDate6','iResRationHour6','iResCap6','iPer6','dDate7','iResRationHour7','iResCap7','iPer7','dDate8','iResRationHour8','iResCap8','iPer8','dDate9','iResRationHour9','iResCap9','iPer9','dDate10','iResRationHour10','iResCap10','iPer10','cUser','cDefine1','iResWorkersPd']
      iInterID?:any
cResourceNo?:any
cWcNo?:any
iSchemeID?:any
dDate1?:any
iResRationHour1?:any
iResCap1?:any
iPer1?:any
dDate2?:any
iResRationHour2?:any
iResCap2?:any
iPer2?:any
dDate3?:any
iResRationHour3?:any
iResCap3?:any
iPer3?:any
dDate4?:any
iResRationHour4?:any
iResCap4?:any
iPer4?:any
dDate5?:any
iResRationHour5?:any
iResCap5?:any
iPer5?:any
dDate6?:any
iResRationHour6?:any
iResCap6?:any
iPer6?:any
dDate7?:any
iResRationHour7?:any
iResCap7?:any
iPer7?:any
dDate8?:any
iResRationHour8?:any
iResCap8?:any
iPer8?:any
dDate9?:any
iResRationHour9?:any
iResCap9?:any
iPer9?:any
dDate10?:any
iResRationHour10?:any
iResCap10?:any
iPer10?:any
cUser?:any
cDefine1?:any
iResWorkersPd?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }