export default class t_WorkOrderLessEntry {
      columnArr=['iInterID','cCode','iAutoID','iItemLessSN','iCompletionRate','cWoNo','iEntryID','cInvCode','cSubInvCode','cSubInvName','cSubInvStd','cComUnitCode','iSeqID','dReqDate','iReqQty','iProQty','iAllocateQty','iPlanQty','iAvailableQty','iCurQty','iForeInQty','iLessQty','dForeInDate','cForeNo','cLessNote','iDispatchedQty','iGrossReqQty','cHostName','cDefine22','cDefine23']
      iInterID?:any
cCode?:any
iAutoID?:any
iItemLessSN?:any
iCompletionRate?:any
cWoNo?:any
iEntryID?:any
cInvCode?:any
cSubInvCode?:any
cSubInvName?:any
cSubInvStd?:any
cComUnitCode?:any
iSeqID?:any
dReqDate?:any
iReqQty?:any
iProQty?:any
iAllocateQty?:any
iPlanQty?:any
iAvailableQty?:any
iCurQty?:any
iForeInQty?:any
iLessQty?:any
dForeInDate?:any
cForeNo?:any
cLessNote?:any
iDispatchedQty?:any
iGrossReqQty?:any
cHostName?:any
cDefine22?:any
cDefine23?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }