export default class t_WorkOrderLessEntrys {
      columnArr=['iAutoID','iPriority','cSdOrderNo','iSdLineID','cWoNo','iInterID','iEntryID','cInvCode','cSubInvCode','cSubInvName','cSubInvStd','cComUnitCode','dReqDate','iReqQty','iProQty','iAllocateQty','iPlanQty','iAvailableQty','iCurQty','iForeInQty','iLessQty','cProductWo','cProductNo','bomLeveL','iItemLessSN','iCompletionRate','iSeqID','dForeInDate','cForeNo','cLessNote','iDispatchedQty','iGrossReqQty','cHostName','cDefine22','cDefine23','unitqty','wQty']
      iAutoID?:any
iPriority?:any
cSdOrderNo?:any
iSdLineID?:any
cWoNo?:any
iInterID?:any
iEntryID?:any
cInvCode?:any
cSubInvCode?:any
cSubInvName?:any
cSubInvStd?:any
cComUnitCode?:any
dReqDate?:any
iReqQty?:any
iProQty?:any
iAllocateQty?:any
iPlanQty?:any
iAvailableQty?:any
iCurQty?:any
iForeInQty?:any
iLessQty?:any
cProductWo?:any
cProductNo?:any
bomLeveL?:any
iItemLessSN?:any
iCompletionRate?:any
iSeqID?:any
dForeInDate?:any
cForeNo?:any
cLessNote?:any
iDispatchedQty?:any
iGrossReqQty?:any
cHostName?:any
cDefine22?:any
cDefine23?:any
unitqty?:any
wQty?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }