export default class t_WorkOrderRoute_Deleted {
      columnArr=['dDeleteDate','cBatchNo','iInterID','iModelID','iProcessProductID','iProcessID','cWoNo','cInvCode','iRouteProcessID','iWoSeqID','cWcNo','cTechNo','cSeqNote','cParellelType','cParallelNo','iSeqRatio','iNextSeqID','cNextSeqNote','cPreProcessID','cPostProcessID','cPreProcessItem','cPostProcessItem','X','Y','iAutoID','cLevelInfo','iLevel','iParentItemID','cParentItemNo','iRouteInterID','iProcessSumQty','iQtyPer','iParentQty','cSourceCode','cKeyBrantch','cCompSeq','cIsReport','cMoveType','iMoveInterTime','iMoveInterQty','iMoveTime','iSeqPreTime','iSeqPostTime','cWorkType','iBatchQty','iBatchWorkTime','iBatchInterTime','iResPreTime','cResPreTimeExp','iCapacity','cCapacityExp','iResPostTime','cResPostTimeExp','iProcessPassRate','iEfficiency','iHoursPd','iWorkQtyPd','iWorkersPd','iDevCountPd','iLaborTime','iLeadTime','cStatus','cSourStatus','iPriority','iReqQty','iActQty','iRealHour','dBegDate','dEndDate','dActBegDate','dActEndDate','cNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','iScrapt','cScraptExp','cDevCountPdExp']
      dDeleteDate?:any
cBatchNo?:any
iInterID?:any
iModelID?:any
iProcessProductID?:any
iProcessID?:any
cWoNo?:any
cInvCode?:any
iRouteProcessID?:any
iWoSeqID?:any
cWcNo?:any
cTechNo?:any
cSeqNote?:any
cParellelType?:any
cParallelNo?:any
iSeqRatio?:any
iNextSeqID?:any
cNextSeqNote?:any
cPreProcessID?:any
cPostProcessID?:any
cPreProcessItem?:any
cPostProcessItem?:any
X?:any
Y?:any
iAutoID?:any
cLevelInfo?:any
iLevel?:any
iParentItemID?:any
cParentItemNo?:any
iRouteInterID?:any
iProcessSumQty?:any
iQtyPer?:any
iParentQty?:any
cSourceCode?:any
cKeyBrantch?:any
cCompSeq?:any
cIsReport?:any
cMoveType?:any
iMoveInterTime?:any
iMoveInterQty?:any
iMoveTime?:any
iSeqPreTime?:any
iSeqPostTime?:any
cWorkType?:any
iBatchQty?:any
iBatchWorkTime?:any
iBatchInterTime?:any
iResPreTime?:any
cResPreTimeExp?:any
iCapacity?:any
cCapacityExp?:any
iResPostTime?:any
cResPostTimeExp?:any
iProcessPassRate?:any
iEfficiency?:any
iHoursPd?:any
iWorkQtyPd?:any
iWorkersPd?:any
iDevCountPd?:any
iLaborTime?:any
iLeadTime?:any
cStatus?:any
cSourStatus?:any
iPriority?:any
iReqQty?:any
iActQty?:any
iRealHour?:any
dBegDate?:any
dEndDate?:any
dActBegDate?:any
dActEndDate?:any
cNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
iScrapt?:any
cScraptExp?:any
cDevCountPdExp?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }