export default class t_WorkOrder_Deleted {
      columnArr=['iAutoID','dDeleteDate','cBatchNo','cBakType','iInterID','cWoNo','cType','iOrgPlanID','cDeptNo','cRouteNo','cMiNo','cSdOrderNo','iItemID','cInvCode','iReqQty','iReqTime','dPutDate','dBegDate','dEndDate','dRePlanDate','cWhNo','cProductWo','cProductNo','iProductQty','dProductDate','iSdLineID','iSchSdID','cCustNo','cParentWo','cParentNo','iBomLevel','cLevelInfo','cLevelPath','cEnough','cStatus','dActBeg','dActEnd','iActQty','iInvQty','iActTime','iLostQty','iItemScrapQty','iWorkScrapQty','cOperator','cOpeName','dOpeDate','iLeadTime','cSourStatus','cBegWcNo','cNote','iVT_ID','qkts','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cChecker','dCheckDate','cCloser','dCloseDate']
      iAutoID?:any
dDeleteDate?:any
cBatchNo?:any
cBakType?:any
iInterID?:any
cWoNo?:any
cType?:any
iOrgPlanID?:any
cDeptNo?:any
cRouteNo?:any
cMiNo?:any
cSdOrderNo?:any
iItemID?:any
cInvCode?:any
iReqQty?:any
iReqTime?:any
dPutDate?:any
dBegDate?:any
dEndDate?:any
dRePlanDate?:any
cWhNo?:any
cProductWo?:any
cProductNo?:any
iProductQty?:any
dProductDate?:any
iSdLineID?:any
iSchSdID?:any
cCustNo?:any
cParentWo?:any
cParentNo?:any
iBomLevel?:any
cLevelInfo?:any
cLevelPath?:any
cEnough?:any
cStatus?:any
dActBeg?:any
dActEnd?:any
iActQty?:any
iInvQty?:any
iActTime?:any
iLostQty?:any
iItemScrapQty?:any
iWorkScrapQty?:any
cOperator?:any
cOpeName?:any
dOpeDate?:any
iLeadTime?:any
cSourStatus?:any
cBegWcNo?:any
cNote?:any
iVT_ID?:any
qkts?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cChecker?:any
dCheckDate?:any
cCloser?:any
dCloseDate?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }