export default class t_WorkResWaitAnalysis {
      columnArr=['iInterID','cUser','cVersionNo','iSchSdID','iProcessProductID','iResProcessID','cSeqNote','cProjectNo','cSdOrderNo','cMiNo','cInvCode','cInvName','cWorkItemNo','cWorkItemName','cResourceNo','cResourceName','cWcNo','cWcName','cWoNo','iWoSeqID','dResBegDate','dResEndDate','dCanBegDate','iResWaitTime','bIsDelay','cDelayType','cPOCode','dArriveDate','cNote','iResReqQty','iResRationhour','iResPreTime','iResPostTime','iCapacity']
      iInterID?:any
cUser?:any
cVersionNo?:any
iSchSdID?:any
iProcessProductID?:any
iResProcessID?:any
cSeqNote?:any
cProjectNo?:any
cSdOrderNo?:any
cMiNo?:any
cInvCode?:any
cInvName?:any
cWorkItemNo?:any
cWorkItemName?:any
cResourceNo?:any
cResourceName?:any
cWcNo?:any
cWcName?:any
cWoNo?:any
iWoSeqID?:any
dResBegDate?:any
dResEndDate?:any
dCanBegDate?:any
iResWaitTime?:any
bIsDelay?:any
cDelayType?:any
cPOCode?:any
dArriveDate?:any
cNote?:any
iResReqQty?:any
iResRationhour?:any
iResPreTime?:any
iResPostTime?:any
iCapacity?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }