export default class t_WorkOrderEntryTemp {
      columnArr=['iInterID','iEntryID','cWoNo','cInvCode','iSubItemID','cSubInvCode','iSeqID','cUtterType','cSubRelate','iParentQty','iSubQty','iQtyPer','iScrapt','iNormalQty','iRetPercent','iReqQty','dReqDate','iProQty','iScrapQty','iNormalScrapQty','iKeepQty','iPlanQty','cWhNo','cPacNo','iRetOffsetLt','cNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cGetItemType','cScraptExp','cPrintColor','bSelf','bDaBan','cTypeSetting','cProductSolidSize','cProductPlaneSize','iOpenQty','iBanQty','iMolecularQty','iDenominatorQty','iSubBZQty','cResourceNo','iTechValue','iAvailableQty','iCurQty','iForeInQty','idIsPatchedQty','iLessQty','iGrossReqQty','dForeInDate','cForeNo','cLessNote','iScraptOut','iNum','iTaxUnitPrice','cUnitCode','bItemPutCtr','iLLOutQty','iLLOutRetQty','iLLInQty','iLLQty','iKeepRetQty','iAllocateQty','dselect','iDetailSelect','iPlanedQty','iAdvanceDate','dEarlySubItemDate','cSourType','cSourceCode','iSourceLineID','cReqCode','iReqLineID','cBomCode','cBomEntryID','cReplaceInvCode','Transferredqty','cSubInvName','cSubInvStd','cSubComUnitCode','cSubItemClsNo']
      iInterID?:any
iEntryID?:any
cWoNo?:any
cInvCode?:any
iSubItemID?:any
cSubInvCode?:any
iSeqID?:any
cUtterType?:any
cSubRelate?:any
iParentQty?:any
iSubQty?:any
iQtyPer?:any
iScrapt?:any
iNormalQty?:any
iRetPercent?:any
iReqQty?:any
dReqDate?:any
iProQty?:any
iScrapQty?:any
iNormalScrapQty?:any
iKeepQty?:any
iPlanQty?:any
cWhNo?:any
cPacNo?:any
iRetOffsetLt?:any
cNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cGetItemType?:any
cScraptExp?:any
cPrintColor?:any
bSelf?:any
bDaBan?:any
cTypeSetting?:any
cProductSolidSize?:any
cProductPlaneSize?:any
iOpenQty?:any
iBanQty?:any
iMolecularQty?:any
iDenominatorQty?:any
iSubBZQty?:any
cResourceNo?:any
iTechValue?:any
iAvailableQty?:any
iCurQty?:any
iForeInQty?:any
idIsPatchedQty?:any
iLessQty?:any
iGrossReqQty?:any
dForeInDate?:any
cForeNo?:any
cLessNote?:any
iScraptOut?:any
iNum?:any
iTaxUnitPrice?:any
cUnitCode?:any
bItemPutCtr?:any
iLLOutQty?:any
iLLOutRetQty?:any
iLLInQty?:any
iLLQty?:any
iKeepRetQty?:any
iAllocateQty?:any
dselect?:any
iDetailSelect?:any
iPlanedQty?:any
iAdvanceDate?:any
dEarlySubItemDate?:any
cSourType?:any
cSourceCode?:any
iSourceLineID?:any
cReqCode?:any
iReqLineID?:any
cBomCode?:any
cBomEntryID?:any
cReplaceInvCode?:any
Transferredqty?:any
cSubInvName?:any
cSubInvStd?:any
cSubComUnitCode?:any
cSubItemClsNo?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }