export default class t_WoRpt {
      columnArr=['iInterID','cRptNo','cType','cWoNo','iWoInterID','iProcessID','iResProcessID','iDisInterID','cDispNo','iDisLineID','cBarCode','iItemID','cInvCode','cInvName','cInvStd','cComUnitCode','iWoSeqID','cTechNo','cSeqNote','cDeptNo','cWcNo','cResourceNo','iNextSeqID','iCapacity','iCompQty','iResReqQty','iSumCompQty','iBadQty','iCompHour','iOtherHour','iStandardQty','iEfficiency','dRptDate','dActBeg','dActEnd','cBatchNo','iInvQty','cTeam','cDutyor','cInspector','cStatus','iAuditID','cOperator','dOpeDate','cChecker','dCheckDate','cNote','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cFree1','cFree2','cFree3','cFree4','cFree5','iAuditTypeID','iVT_ID','qkts','iResPreTime','iCycTime','cMiNo','iScanResourceID','cNewID','cBadReason','cBadPro','iBadProTime','dBadProTime','cProductNo','cProductNoName','cModifier','dModifyDate','bItemFlag','iLastSeqID','cRptPersonCode','iNstructionsCode','cCustPoCode','cCustWorkID','cCustPoCodeQty','cCustdeliveryQty','iPrintCount','dPutStartDate','dPutStopDate','iPutInNumSum','cProductionStatus','cMoldNo','iBatchQty','iQcBadQty','iLineID','iTaskID','cProcessQty','dStartWorkTime','dLastRptTime','iWipInvID','iPkgQty']
      iInterID?:any
cRptNo?:any
cType?:any
cWoNo?:any
iWoInterID?:any
iProcessID?:any
iResProcessID?:any
iDisInterID?:any
cDispNo?:any
iDisLineID?:any
cBarCode?:any
iItemID?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
iWoSeqID?:any
cTechNo?:any
cSeqNote?:any
cDeptNo?:any
cWcNo?:any
cResourceNo?:any
iNextSeqID?:any
iCapacity?:any
iCompQty?:any
iResReqQty?:any
iSumCompQty?:any
iBadQty?:any
iCompHour?:any
iOtherHour?:any
iStandardQty?:any
iEfficiency?:any
dRptDate?:any
dActBeg?:any
dActEnd?:any
cBatchNo?:any
iInvQty?:any
cTeam?:any
cDutyor?:any
cInspector?:any
cStatus?:any
iAuditID?:any
cOperator?:any
dOpeDate?:any
cChecker?:any
dCheckDate?:any
cNote?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
iAuditTypeID?:any
iVT_ID?:any
qkts?:any
iResPreTime?:any
iCycTime?:any
cMiNo?:any
iScanResourceID?:any
cNewID?:any
cBadReason?:any
cBadPro?:any
iBadProTime?:any
dBadProTime?:any
cProductNo?:any
cProductNoName?:any
cModifier?:any
dModifyDate?:any
bItemFlag?:any
iLastSeqID?:any
cRptPersonCode?:any
iNstructionsCode?:any
cCustPoCode?:any
cCustWorkID?:any
cCustPoCodeQty?:any
cCustdeliveryQty?:any
iPrintCount?:any
dPutStartDate?:any
dPutStopDate?:any
iPutInNumSum?:any
cProductionStatus?:any
cMoldNo?:any
iBatchQty?:any
iQcBadQty?:any
iLineID?:any
iTaskID?:any
cProcessQty?:any
dStartWorkTime?:any
dLastRptTime?:any
iWipInvID?:any
iPkgQty?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }