export default class t_WorkOrderEntry_Deleted {
      columnArr=['iAutoID','dDeleteDate','cBatchNo','iInterID','iEntryID','cWoNo','cInvCode','iSubItemID','cSubInvCode','iSeqID','cUtterType','cSubRelate','iParentQty','iSubQty','iQtyPer','iScrapt','iNormalQty','iRetPercent','iReqQty','dReqDate','iProQty','iScrapQty','iNormalScrapQty','iKeepQty','iPlanQty','cWhNo','cPacNo','iRetOffsetLt','cNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37','cGetItemType','cScraptExp']
      iAutoID?:any
dDeleteDate?:any
cBatchNo?:any
iInterID?:any
iEntryID?:any
cWoNo?:any
cInvCode?:any
iSubItemID?:any
cSubInvCode?:any
iSeqID?:any
cUtterType?:any
cSubRelate?:any
iParentQty?:any
iSubQty?:any
iQtyPer?:any
iScrapt?:any
iNormalQty?:any
iRetPercent?:any
iReqQty?:any
dReqDate?:any
iProQty?:any
iScrapQty?:any
iNormalScrapQty?:any
iKeepQty?:any
iPlanQty?:any
cWhNo?:any
cPacNo?:any
iRetOffsetLt?:any
cNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any
cGetItemType?:any
cScraptExp?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }