export default class t_WorkOrderSerial {
      columnArr=['cSerialCode','cInvCode','cWoNo','iWoInterID','iScanResourceID','iQuantity','cTechNo','cNextTechNo','iWoSeqID','iNextSeqID','cResourceNo','cNextResorceNo','iProcessID','iResProcessID','bInWhCode','iCompRate','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cDefine37']
      cSerialCode?:any
cInvCode?:any
cWoNo?:any
iWoInterID?:any
iScanResourceID?:any
iQuantity?:any
cTechNo?:any
cNextTechNo?:any
iWoSeqID?:any
iNextSeqID?:any
cResourceNo?:any
cNextResorceNo?:any
iProcessID?:any
iResProcessID?:any
bInWhCode?:any
iCompRate?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cDefine37?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }