export default class t_WoSeqDispatchEntry {
      columnArr=['iInterID','cDispNo','iLineID','cWoNo','iWoInterID','iItemID','iProcessID','iResProcessID','cResourceNo','cBarCode','iWoSeqID','cTechNo','cSeqNote','iNextSeqID','dResBegDate','dResEndDate','dActBegDate','dActEndDate','iResReqQty','iResRationHour','iResActQty','iResActHour','cInvCode','cInvName','cInvStd','cComUnitCode','bComplete','cDetailNote','cDefine22','cDefine23','cDefine24','cDefine25','cDefine26','cDefine27','cDefine28','cDefine29','cDefine30','cDefine31','cDefine32','cDefine33','cDefine34','cDefine35','cDefine36','cBatchNo','dPeriodDay','cShiftType','cNextSeqNote','iResPreTime','iResActPreTime','iBatchQty','iActBatchQty','iCapacity','cViceResource1No','cViceResource2No','cViceResource3No','cPriorityType','iCompRate','iShiftType1A','iShiftType1B','iShiftType1C','iShiftType2A','iShiftType2B','iShiftType2C','iShiftType3A','iShiftType3B','iShiftType3C','iShiftTypeAct1A','iShiftTypeAct1B','iShiftTypeAct1C','iShiftTypeAct2A','iShiftTypeAct2B','iShiftTypeAct2C','iShiftTypeAct3A','iShiftTypeAct3B','iShiftTypeAct3C','iShiftTypeRate1A','iShiftTypeRate1B','iShiftTypeRate1C','iShiftTypeRate2A','iShiftTypeRate2B','iShiftTypeRate2C','iShiftTypeRate3A','iShiftTypeRate3B','iShiftTypeRate3C','cTaskStatus','iNoCompQty','iTransProQty','iResReqQtySum','iScanResourceID','iTaskID','FResChaValue1ID','FResChaValue2ID','FResChaValue3ID','FResChaValue4ID','FResChaValue5ID','FResChaValue6ID','FResChaValue7ID','FResChaValue8ID','FResChaValue9ID','FResChaValue10ID','FResChaValue11ID','FResChaValue12ID','cTechSchType','cSchStatusDate','cRouteStopType','cSchStatusNote','cTaskSourStatus','iCycTime','cWorkType','cResourceName','iBatchQtyBase','WBID','WBPID','iResReqNum','iResReqNumSum','iResActNum','cItemGroup','iWorkQtyPd']
      iInterID?:any
cDispNo?:any
iLineID?:any
cWoNo?:any
iWoInterID?:any
iItemID?:any
iProcessID?:any
iResProcessID?:any
cResourceNo?:any
cBarCode?:any
iWoSeqID?:any
cTechNo?:any
cSeqNote?:any
iNextSeqID?:any
dResBegDate?:any
dResEndDate?:any
dActBegDate?:any
dActEndDate?:any
iResReqQty?:any
iResRationHour?:any
iResActQty?:any
iResActHour?:any
cInvCode?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
bComplete?:any
cDetailNote?:any
cDefine22?:any
cDefine23?:any
cDefine24?:any
cDefine25?:any
cDefine26?:any
cDefine27?:any
cDefine28?:any
cDefine29?:any
cDefine30?:any
cDefine31?:any
cDefine32?:any
cDefine33?:any
cDefine34?:any
cDefine35?:any
cDefine36?:any
cBatchNo?:any
dPeriodDay?:any
cShiftType?:any
cNextSeqNote?:any
iResPreTime?:any
iResActPreTime?:any
iBatchQty?:any
iActBatchQty?:any
iCapacity?:any
cViceResource1No?:any
cViceResource2No?:any
cViceResource3No?:any
cPriorityType?:any
iCompRate?:any
iShiftType1A?:any
iShiftType1B?:any
iShiftType1C?:any
iShiftType2A?:any
iShiftType2B?:any
iShiftType2C?:any
iShiftType3A?:any
iShiftType3B?:any
iShiftType3C?:any
iShiftTypeAct1A?:any
iShiftTypeAct1B?:any
iShiftTypeAct1C?:any
iShiftTypeAct2A?:any
iShiftTypeAct2B?:any
iShiftTypeAct2C?:any
iShiftTypeAct3A?:any
iShiftTypeAct3B?:any
iShiftTypeAct3C?:any
iShiftTypeRate1A?:any
iShiftTypeRate1B?:any
iShiftTypeRate1C?:any
iShiftTypeRate2A?:any
iShiftTypeRate2B?:any
iShiftTypeRate2C?:any
iShiftTypeRate3A?:any
iShiftTypeRate3B?:any
iShiftTypeRate3C?:any
cTaskStatus?:any
iNoCompQty?:any
iTransProQty?:any
iResReqQtySum?:any
iScanResourceID?:any
iTaskID?:any
FResChaValue1ID?:any
FResChaValue2ID?:any
FResChaValue3ID?:any
FResChaValue4ID?:any
FResChaValue5ID?:any
FResChaValue6ID?:any
FResChaValue7ID?:any
FResChaValue8ID?:any
FResChaValue9ID?:any
FResChaValue10ID?:any
FResChaValue11ID?:any
FResChaValue12ID?:any
cTechSchType?:any
cSchStatusDate?:any
cRouteStopType?:any
cSchStatusNote?:any
cTaskSourStatus?:any
iCycTime?:any
cWorkType?:any
cResourceName?:any
iBatchQtyBase?:any
WBID?:any
WBPID?:any
iResReqNum?:any
iResReqNumSum?:any
iResActNum?:any
cItemGroup?:any
iWorkQtyPd?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }