export default class t_WorkOrder {
      columnArr=['iInterID','iInterID','cWoNo','cType','iOrgPlanID','cDeptNo','cRouteNo','cMiNo','cSdOrderNo','iItemID','cInvCode','iReqQty','iReqTime','dPutDate','dBegDate','dEndDate','dRePlanDate','cWhNo','cProductWo','cProductNo','iProductQty','dProductDate','iSdLineID','iSchSdID','cCustNo','cParentWo','cParentNo','iBomLevel','cLevelInfo','cLevelPath','cEnough','cStatus','dActBeg','dActEnd','iActQty','iInvQty','iActTime','iLostQty','iItemScrapQty','iWorkScrapQty','cOperator','cOpeName','dOpeDate','iLeadTime','cSourStatus','cBegWcNo','cNote','iVT_ID','qkts','cDefine1','cDefine2','cDefine3','cDefine4','cDefine5','cDefine6','cDefine7','cDefine8','cDefine9','cDefine10','cDefine11','cDefine12','cDefine13','cDefine14','cDefine15','cDefine16','cChecker','dCheckDate','cCloser','dCloseDate','cModifier','dModifyDate','bCost','iCostQty','iBZQty','bBZPrint','dBZPrintDate','bWorkItem','cFree1','cFree2','cFree3','cFree4','cFree5','cFree6','cFree7','cFree8','cFree9','cFree10','iMegQty','cProMaterialNote','cProductNoAll','cProjectNo','iNum','iQtyPerNum','cAttributes1','cAttributes2','cAttributes3','cAttributes4','cAttributes5','cAttributes6','cAttributes7','cAttributes8','cAttributes9','cAttributes10','cAttributes11','cAttributes12','dFirstBegDate','dFirstEndDate','cWorkRouteType','cRouteTypeSelectExp','bSetModel','cAttributes13','cAttributes14','cAttributes15','cAttributes16','iNstructionsCode','cPriorityType','iPriority','cBatchNo','iHeadSelect','cSelect','cHostName','iCustomizeQty','cInvName','cInvStd','cComUnitCode','cItemClsNo','iPrintCount','dPrintDate','iDispatchedQty','iCompletionRate','iItemLessSN','hselect','bSynStatus','cStatusNote','cSchSNType','iSchSN','dCanBegDate','dCanEndDate','iWoPriorityRes','iWoPriorityResLast','cReqCodeWo','iReqLineIDWo','cBegResourceNo','cSubMoldNo','cBegVenNo','cSchType','iBatchQty','WBID','WBPID','iSourceQty','dSourceDate','iQtyBefore','iLessQty','cLessQtyNote','iBegWeek','iEndWeek']
      iInterID?:any
iInterID?:any
cWoNo?:any
cType?:any
iOrgPlanID?:any
cDeptNo?:any
cRouteNo?:any
cMiNo?:any
cSdOrderNo?:any
iItemID?:any
cInvCode?:any
iReqQty?:any
iReqTime?:any
dPutDate?:any
dBegDate?:any
dEndDate?:any
dRePlanDate?:any
cWhNo?:any
cProductWo?:any
cProductNo?:any
iProductQty?:any
dProductDate?:any
iSdLineID?:any
iSchSdID?:any
cCustNo?:any
cParentWo?:any
cParentNo?:any
iBomLevel?:any
cLevelInfo?:any
cLevelPath?:any
cEnough?:any
cStatus?:any
dActBeg?:any
dActEnd?:any
iActQty?:any
iInvQty?:any
iActTime?:any
iLostQty?:any
iItemScrapQty?:any
iWorkScrapQty?:any
cOperator?:any
cOpeName?:any
dOpeDate?:any
iLeadTime?:any
cSourStatus?:any
cBegWcNo?:any
cNote?:any
iVT_ID?:any
qkts?:any
cDefine1?:any
cDefine2?:any
cDefine3?:any
cDefine4?:any
cDefine5?:any
cDefine6?:any
cDefine7?:any
cDefine8?:any
cDefine9?:any
cDefine10?:any
cDefine11?:any
cDefine12?:any
cDefine13?:any
cDefine14?:any
cDefine15?:any
cDefine16?:any
cChecker?:any
dCheckDate?:any
cCloser?:any
dCloseDate?:any
cModifier?:any
dModifyDate?:any
bCost?:any
iCostQty?:any
iBZQty?:any
bBZPrint?:any
dBZPrintDate?:any
bWorkItem?:any
cFree1?:any
cFree2?:any
cFree3?:any
cFree4?:any
cFree5?:any
cFree6?:any
cFree7?:any
cFree8?:any
cFree9?:any
cFree10?:any
iMegQty?:any
cProMaterialNote?:any
cProductNoAll?:any
cProjectNo?:any
iNum?:any
iQtyPerNum?:any
cAttributes1?:any
cAttributes2?:any
cAttributes3?:any
cAttributes4?:any
cAttributes5?:any
cAttributes6?:any
cAttributes7?:any
cAttributes8?:any
cAttributes9?:any
cAttributes10?:any
cAttributes11?:any
cAttributes12?:any
dFirstBegDate?:any
dFirstEndDate?:any
cWorkRouteType?:any
cRouteTypeSelectExp?:any
bSetModel?:any
cAttributes13?:any
cAttributes14?:any
cAttributes15?:any
cAttributes16?:any
iNstructionsCode?:any
cPriorityType?:any
iPriority?:any
cBatchNo?:any
iHeadSelect?:any
cSelect?:any
cHostName?:any
iCustomizeQty?:any
cInvName?:any
cInvStd?:any
cComUnitCode?:any
cItemClsNo?:any
iPrintCount?:any
dPrintDate?:any
iDispatchedQty?:any
iCompletionRate?:any
iItemLessSN?:any
hselect?:any
bSynStatus?:any
cStatusNote?:any
cSchSNType?:any
iSchSN?:any
dCanBegDate?:any
dCanEndDate?:any
iWoPriorityRes?:any
iWoPriorityResLast?:any
cReqCodeWo?:any
iReqLineIDWo?:any
cBegResourceNo?:any
cSubMoldNo?:any
cBegVenNo?:any
cSchType?:any
iBatchQty?:any
WBID?:any
WBPID?:any
iSourceQty?:any
dSourceDate?:any
iQtyBefore?:any
iLessQty?:any
cLessQtyNote?:any
iBegWeek?:any
iEndWeek?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }