export default class t_WorkReport {
      columnArr=['ID','cNewID','iScanResourceID','cInvCode','cInvName','dReportDate','cReportMan','cMiNo','iQuantity','cTeam','cCode','cTeamNo','cReportManCode','cRptNo','cResourceNo','cResourceName','iBadQty','cBadReason','cBadPro','iBadProTime','cProductNo','cProductNoName','iCompHour']
      ID?:any
cNewID?:any
iScanResourceID?:any
cInvCode?:any
cInvName?:any
dReportDate?:any
cReportMan?:any
cMiNo?:any
iQuantity?:any
cTeam?:any
cCode?:any
cTeamNo?:any
cReportManCode?:any
cRptNo?:any
cResourceNo?:any
cResourceName?:any
iBadQty?:any
cBadReason?:any
cBadPro?:any
iBadProTime?:any
cProductNo?:any
cProductNoName?:any
iCompHour?:any 
      constructor() {}
      insert(){}
      update(){} 
      delete(){}    
    }